### ISSUE TITLE
Secondary application

### ISSUE THREAD

**Issue by donete7** [rhunk/SnapEnhance#1004]
### Description

I'm using google translator
I don't think it's necessarily a mistake. But yes, I just don't know if there is this function and if there is a way to do it, I don't know how to enable it. I would like to know if there is a way to use the SnapEnhance module on my cell phone's secondary account (I'm using the Samsung A11) because my account was banned and so was my device, preventing me from creating or logging into new accounts through the root app, but I can log in to the secondary app. Is there a way to activate this option? I hope you help me! Thanks!

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by donete7** [comment]
*using Google translator
And the only options I want are to just save photos/videos from friends and send photos/videos from my gallery. Help me please!

**Comment by bocajthomas** [comment]
@donete7 your second snapchat account ?

**Comment by donete7** [comment]
*Using Google translator
No! I will explain again. My cell phone has the option to duplicate apps called "Dual Apps". With this I can have 2 different Snapchat accounts active on my cell phone. My account on the primary (root) app has been banned and I can't log in with any primary Snapchat account. I can only log in to the secondary Snapchat. But right now I can't activate Snapenhance, and that's what I wanted to do. At least I wanted to be able to send photos/videos from the gallery and save my friends' photos/videos. I hope you understood!

**Comment by donete7** [comment]
My cekular has the app that I downloaded from the app store. After downloading, I can duplicate the SC app and that way I have 2 Snapchats on my phone. I want to activate Snapenhance functions in my Snapchat secondary app. Does it work?

**Comment by bocajthomas** [comment]
> My cekular has the app that I downloaded from the app store. After downloading, I can duplicate the SC app and that way I have 2 Snapchats on my phone. I want to activate Snapenhance functions in my Snapchat secondary app. Does it work?

no
