### ISSUE TITLE
Chats fail to load, and not getting notifications 

### ISSUE THREAD

**Issue by brog-io** [rhunk/SnapEnhance#1015]
### Description

Sometimes, seemingly randomly. Chats don't load, only my pinned friends show up but I can't open their Snaps. I've also noticed I don't get notifications anymore, sometimes they work but usually they don't. 

Haven't experienced either issues with the last beta build. Might be a base issue but a user in the telegram group said they fixed these issues when downgrading to the previous build.

![Screenshot_20240512_132330_Snapchat](https://github.com/rhunk/SnapEnhance/assets/141176104/84cf9267-c45d-4f2c-a06e-61b83a0a459d)

### Reproduction steps

This happens randomly,  not sure how to reproduce.  

### Snapchat Version

12.85.1.0

### SnapEnhance Version

2.1.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by brog-io** [comment]
I'm currently testing Snapchat without SnapEnhance to see if I can replicate the bug. I'll update you incase I notice it's a base issue

**Comment by JWHC1** [comment]
How often would you say this problem occurs?

**Comment by brog-io** [comment]
> How often would you say this problem occurs?

Very frequently, the base app doesn't seem to have this issue at all

**Comment by bocajthomas** [comment]
@brog-io I have no logs 

Please do this issue properly and provide logs !!

**Comment by brog-io** [comment]
> @brog-io I have no logs 
> 
> Please do this issue properly and provide logs !!

There were no errors in the logs, but if you want I can still post them

**Comment by bocajthomas** [comment]
> There were no errors in the logs, but if you want I can still post them
> Logs: https://drive.proton.me/urls/WEQHW2RBF0#7ckkFJHXgJi3

@brog-io please upload the zip via github 

![Screenshot_20240512_153950_Chrome](https://github.com/rhunk/SnapEnhance/assets/41988041/63ae3ed2-3638-4890-9939-b168d1a3e407)

**Comment by brog-io** [comment]
![snapenhance-logs-1715523895690.zip](https://github.com/rhunk/SnapEnhance/files/15286651/snapenhance-logs-1715523895690.zip)

**Comment by brog-io** [comment]
Just noticed video snaps send way faster without SnapEnhance. I'm not sure if it's related to this bug.

**Comment by JWHC1** [comment]
i wouldn't say its part of the same problem. This specific problem might be caused by some Enhance settings you might have enabled in the camera tab.

**Comment by bocajthomas** [comment]
@brog-io i see Failed to find ANDROID_ACTION_MENU_V2 in ConfigRule

try turning off `New Chat Action Menu`

**Comment by brog-io** [comment]
> @brog-io i see Failed to find ANDROID_ACTION_MENU_V2 in ConfigRule
> 
> try turning off `New Chat Action Menu`
> 

I also saw that and turned it off since it didn't work. Experienced the same issue with it disabled

**Comment by brog-io** [comment]
Just repatched the same build with the latest Snapchat version. I still experience the same issue. 

Checked my logs if anything changed, and I got ``Failed to find ANDROID_ACTION_MENU_V2 in ConfigRule``

I'm not sure why I got this error message, I didn't even import my settings this time, and I made sure that toggle is disabled.

**Comment by bocajthomas** [comment]
> Failed to find ANDROID_ACTION_MENU_V2 in ConfigRule`

I don't think this has anything to do with new chat menu

**Comment by bocajthomas** [comment]
> > Failed to find ANDROID_ACTION_MENU_V2 in ConfigRule`

> I don't think this has anything to do with new chat menu idk why I said it 🤣🤦‍♂️

**Comment by brog-io** [comment]
Installed this latest beta build, I'm no longer experiencing this issue. Not sure what exactly the issue was, I patched the exact same way as I always do (Exact steps of the guide.)
