### ISSUE TITLE
Snapchat keeps stopping

### ISSUE THREAD

**Issue by Ezrat95** [rhunk/SnapEnhance#1018]
### Description

snapchat keeps stopping I can't open the App.
I have 2.0.1
![WhatsApp Bild 2024-05-12 um 22 43 20_84940662](https://github.com/rhunk/SnapEnhance/assets/169616717/956cc4ba-9b9a-4d7e-9c29-652d421723d0)
![image](https://github.com/rhunk/SnapEnhance/assets/169616717/ca1fa12a-b17f-4712-bc0e-b4e2f3bef73f) snap
![image](https://github.com/rhunk/SnapEnhance/assets/169616717/cda95be8-d490-4535-95b8-a61d3d5a030f) se

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.85.1.0

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
No logs !

**Comment by Ezrat95** [comment]
I don't know how to do that I'm new man
