### ISSUE TITLE
Snapchat keeps stopping

### ISSUE THREAD

**Issue by Ezrat95** [rhunk/SnapEnhance#1019]
### Description

snapchat keeps stopping I can't open the App.
I have 2.0.1

![image](https://github.com/rhunk/SnapEnhance/assets/169616717/be3276e4-6e85-4a75-9437-ab13929a82e4)
![image](https://github.com/rhunk/SnapEnhance/assets/169616717/477ec2b4-3224-42e3-b716-4b569c5aa8ca)
![image](https://github.com/rhunk/SnapEnhance/assets/169616717/872342bd-7cca-4552-aa2a-66de2d4a6025)

### Reproduction steps

install ls patch from browser
install snap from playstore
install shizuku from playstore
install snap enhance from browser
https://www.youtube.com/watch?v=SN2WjEEAoKg
watch the video and do everything he says + the override version code.
open snap and see this error

i also tried
se manager updating snap and snap enhance
idk why

### Logs

```markdown
|V/2024-05-12 21:04:40/manager/Loading RemoteSideContext
|V/2024-05-12 21:13:27/manager/Loading RemoteSideContext
|V/2024-05-12 21:13:37/manager/Loading RemoteSideContext
|V/2024-05-12 21:14:02/manager/saved config!
|V/2024-05-12 21:14:33/manager/saved config!
|V/2024-05-12 21:14:36/manager/saved config!
|D/2024-05-12 21:14:50/manager/Speichern von Protokollen, das kann eine Weile dauern ...


Device info:
{
  "modInfo": {
    "buildIssuer": "C\u003dUS, O\u003dAndroid, CN\u003dAndroid Debug",
    "buildPackageName": "me.rhunk.snapenhance",
    "buildVersion": "2.0.2",
    "buildVersionCode": 202,
    "isDebugBuild": true,
    "loaderPackageName": "me.rhunk.snapenhance.ui.manager",
    "mappingVersion": -991243894,
    "mappingsOutdated": false
  },
  "platformInfo": {
    "androidVersion": "14",
    "device": "emu64xa",
    "systemAbi": "x86_64"
  },
  "snapchatInfo": {
    "isLSPatched": true,
    "isSplitApk": false,
    "packageName": "com.snapchat.android",
    "version": "12.85.1.0",
    "versionCode": 131222
  }
}
```

### Snapchat Version

12.85.1.0

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
@Ezrat95 we have an official [Insrallation Guide](https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide). 

please try the `Installation Guide (LSPatch & SAI) ( Best For New Users )`

**Comment by Ezrat95** [comment]
![image](https://github.com/rhunk/SnapEnhance/assets/169616717/6562c94b-99ae-450b-b950-1962b9ba9b69)
i cant download SAI

**Comment by Ezrat95** [comment]
![image](https://github.com/rhunk/SnapEnhance/assets/169616717/c2d140ec-fcf0-4f9a-8d33-283e1e88ef22)

**Comment by bocajthomas** [comment]
> ![image](https://private-user-images.githubusercontent.com/169616717/329882252-6562c94b-99ae-450b-b950-1962b9ba9b69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NTIyMzIsIm5iZiI6MTcxNTU1MTkzMiwicGF0aCI6Ii8xNjk2MTY3MTcvMzI5ODgyMjUyLTY1NjJjOTRiLTk5YWUtNDUwYi1iOTUwLTE5NjJiOWJhOWI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQyMjEyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTIxMzQwZDRmZGM1ZWNhZTM2NzI3Yzc4ODk0MTJkNzk4ZDBlYmNkZDU1MmUwMzAyNjg5ZGJhMWJmOTk0MjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZQcMB948C2QDBe7AbfPPeRJe_AJApnMKAkleLU3VwFM) i cant download SAI

thats because its nolonger supported on google play 

https://github.com/Aefyr/SAI/releases/tag/4.5

**Comment by bocajthomas** [comment]
> ![image](https://private-user-images.githubusercontent.com/169616717/329883174-c2d140ec-fcf0-4f9a-8d33-283e1e88ef22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NTIyMzIsIm5iZiI6MTcxNTU1MTkzMiwicGF0aCI6Ii8xNjk2MTY3MTcvMzI5ODgzMTc0LWMyZDE0MGVjLWZjZjAtNGY5YS04ZDMzLTI4M2UxZTg4ZWYyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQyMjEyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTNlMDcxMTNhMTU5M2NjY2EzMGRiMzE5ZGNkZGY5ZWQ0MTBlYzJmYWE4NmVhYTVkODE5ZDA2OWQ5NjUwNTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E8FvTS2SVE3cWorq4NgTrocuRjIubcpUDzBuy0YVR-w)

dont use Shizuku

**Comment by Ezrat95** [comment]
I just told you I can't download SAI
My android too new
![image](https://github.com/rhunk/SnapEnhance/assets/169616717/f6c874f8-4824-4f9d-9c59-915dc66dbe5d)
