### ISSUE TITLE
Image sent in low quality even when Force Upload Source Quality is turned on

### ISSUE THREAD

**Issue by amangupta711** [rhunk/SnapEnhance#1027]
### Description

Turn on Force Upload Source Quality and Gallery Media send override

Choose a photo from gallery and send it as savable snap

the sent snap is of very less size and quality is degraded (in kb)

### Reproduction steps

1. Enable Force Upload Source Quality
2. Enable Gallery Media send override
3. Send an image as savable snap from gallery
4. Image not of source quality
5. Sent image is of very less size and quality is also degraded (in KB's)

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Can't reproduce unfortunately 

### Steps you could take
- update SnapEnhance To v2.1.0 ( debug ) 
- update Snapchat to v12.86

**Comment by authorisation** [comment]
@bocajthomas The 'invalid' tag only applies to issues with invalid metadata, such as missing info, wrong formatted or issues missing those confirmation boxes.

**Comment by bocajthomas** [comment]
> @bocajthomas The 'invalid' tag only applies to issues with invalid metadata, such as missing info, wrong formatted or issues missing those confirmation boxes.

@authorisation he or she tick the "I have attached a log if deemed necessary." 

And he or she did not provide them 
Your comment fits that 👍
