### ISSUE TITLE
Upload custom snap

### ISSUE THREAD

**Issue by DominikP78** [rhunk/SnapEnhance#1042]
### Description

You could add the ability to upload pictures to send as snaps. Maybe it's already there and I just overlooked it but would be nice if that was added if it's possible to do so. 

### Agreement

- [ ] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
This has already been implemented

**Comment by DominikP78** [comment]
> This has already been implemented

Thanks! I didn't see that. Can you please tell me here I can find it?

**Comment by bocajthomas** [comment]
> Thanks! I didn't see that. Can you please tell me here I can find it?

https://github.com/rhunk/SnapEnhance/wiki/Features-Explained

**Comment by DominikP78** [comment]
> > Thanks! I didn't see that. Can you please tell me here I can find it?
> 
> https://github.com/rhunk/SnapEnhance/wiki/Features-Explained

Thanks! I've been searching for some kind of wiki but I didn't find one.

**Comment by DominikP78** [comment]
> @DominikP78 https://github.com/rhunk/SnapEnhance/wiki/Features-Explained#gallery-media-send-override

But I already tried that and it sent it as a normal image not as a snap you can see only 1 time

**Comment by bocajthomas** [comment]
> Thanks But I already tried that and it sent it as a normal image not as a snap you can see only 1 time. Maybe I did something wrong

You press send as Snap and it sends as a snap it's not difficult at all very simple

**Comment by DominikP78** [comment]
> > Thanks But I already tried that and it sent it as a normal image not as a snap you can see only 1 time. Maybe I did something wrong
> 
> You press send as Snap and it sends as a snap it's not difficult at all very simple

For me this button wasn't there and it just sent as a picture automatically. I'll try it again later

**Comment by bocajthomas** [comment]
@DominikP78 you select a photo from your cam roll then press send then it pops up
