### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by Ezrat95** [rhunk/SnapEnhance#1050]
### Description

i did everything and snapchat aint enhanced ig

### Reproduction steps

https://github.com/Aefyr/SAI/releases/tag/4.5 SAI

https://github.com/LSPosed/LSPatch/releases/tag/v0.6 LS patch

https://t.me/snapenhance_chat/1/75102 snap enhance 2.0.2

[snapenhance-logs-1716201745893.zip](https://github.com/rhunk/SnapEnhance/files/15376061/snapenhance-logs-1716201745893.zip)

What's Needed
SnapEnhance
LSPatch
SAI
Snapchat From Google Play
LSPatch Patching Guide
Open " LSPatch " (It Should Say Shizuku Is Not Running This Is Fine)
Press The " Manage " Tab
Press The " Plus " Icon

choose path: i chose a folder i put in downloads > folder
allow accesss to folder

"new patch"
Press " Select An Installed App "
Find Snapchat (You Can Do This By search or scrolling)
Press Snapchat
Press " Integrated "
Press " Embed Modules "
Press " Select apk(s) From Storage "
Find " SnapEnhance " You Just Download
Press " Start Patch "
Wait For " LSPatch " To Patch Snapchat

it says go back or install and i click none of both

Now Follow " SAI Installation Guide "
SAI Installation Guide
Open " SAI "
Press " Install Apks "
Press " System File Picker "
Select all 4 apks That Have Just Been Patched

thers 8!
i pick the ones Jacob Thomas tells me to
![WhatsApp Bild 2024-05-20 um 12 21 20_79ff5b05](https://github.com/rhunk/SnapEnhance/assets/169616717/d07de2da-ebab-4663-a8b3-976e82df6cdb)

Press " Install "

i allow SAI to install unknown apps
i press update snapchat

Now Follow " SnapEnhance Setup Guide "
SnapEnhance Setup Guide
Open SnapEnhance
Set Your Language ( If Supported )
Press " > "
Allow All Requests
Press " Select Folder "
Create A Folder For SnapEnhance ( This Will Allow SnapEnhance To Read And Write )
Press " > "
Press " Generate "
Wait For It To Map
Press " Ok "
Press " Tick "

open Snapchat

nothing changed lol

![Screenshot_20240520_124620_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/169616717/6f97190a-7141-4294-a95b-fddb46b70426)

### Logs

```markdown
|V/2024-05-20 12:23:19/manager/Loading RemoteSideContext
|V/2024-05-20 12:25:31/manager/Loading RemoteSideContext
|V/2024-05-20 12:26:50/manager/Loading RemoteSideContext
|V/2024-05-20 12:27:09/manager/saved config!
|V/2024-05-20 12:28:34/manager/Loading RemoteSideContext
|V/2024-05-20 12:28:39/manager/saved config!
|V/2024-05-20 12:28:40/manager/saved config!
|V/2024-05-20 12:29:27/manager/saved config!
|V/2024-05-20 12:29:27/manager/saved config!
|V/2024-05-20 12:29:31/manager/saved config!
|V/2024-05-20 12:29:31/manager/saved config!
|V/2024-05-20 12:30:54/manager/saved config!
|V/2024-05-20 12:32:52/manager/saved config!
|V/2024-05-20 12:32:52/manager/saved config!
|V/2024-05-20 12:40:22/manager/saved config!
|V/2024-05-20 12:40:22/manager/saved config!
|V/2024-05-20 12:40:27/manager/saved config!
|V/2024-05-20 12:40:28/manager/saved config!
|V/2024-05-20 12:40:40/manager/saved config!
|V/2024-05-20 12:40:40/manager/saved config!
|V/2024-05-20 12:42:04/manager/saved config!
|V/2024-05-20 12:42:05/manager/saved config!
|V/2024-05-20 12:42:16/manager/saved config!
|V/2024-05-20 12:42:17/manager/saved config!
|V/2024-05-20 12:42:21/manager/saved config!
|D/2024-05-20 12:42:41/manager/Speichern von Protokollen, das kann eine Weile dauern ...
```

### Snapchat Version

12.86.0.44

### SnapEnhance Version

2.0.2

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by Ezrat95** [comment]
okay I didn't know that I will try again real quick

**Comment by bocajthomas** [comment]
> [snapenhance-logs-1716201745893.zip](https://github.com/rhunk/SnapEnhance/files/15376061/snapenhance-logs-1716201745893.zip)

This is corrupted, we can't view it !

**Comment by Ezrat95** [comment]
uh but idk what to do its just the one i exported. how do i share logs??

**Comment by bocajthomas** [comment]
You also said there was 8 apks 
While the Screenshot has 9 

That Screenshot was not ment for you

**Comment by Ezrat95** [comment]
yes that screenshot was for me lol it was MY screenshot and he added the red stuff. I meant 9 sorry

**Comment by bocajthomas** [comment]
> uh but idk what to do its just the one i exported. how do i share logs??

Redo the logs by export and resend sometimes stuff gets corrupted

**Comment by bocajthomas** [comment]
> yes that screenshot was for me lol it was MY screenshot and he added the red stuff. I meant 9 sorry

Read my name 😁

**Comment by Ezrat95** [comment]
![SmartSelect_20240520_131426_SAI](https://github.com/rhunk/SnapEnhance/assets/169616717/979e75e2-2344-4074-9278-7b0b623ed355)

Now i uninstalled snapchat after the 9 apks where ready and then went in SAI but now it dont work

**Comment by bocajthomas** [comment]
> Now i uninstalled snapchat after the 9 apks where ready and then went in SAI but now it dont work

Did you press keep app data ?

**Comment by bocajthomas** [comment]
> > Did you press keep app data ?
> 
> If so your gonna need a pc or an app called termux to use adb
> 
> Command:
> 
> adb uninstall com.snapchat.android

Am also gonna close this 
But you can still comment

**Comment by Ezrat95** [comment]
My snap is fresh installed always when i just uninstall they dont ask me to keep anything

**Comment by Ezrat95** [comment]
i have a pc but i dont understand what u mean

**Comment by bocajthomas** [comment]
> My snap is fresh installed always when i just uninstall they dont ask me to keep anything

Unfortunately if you don't know how to install then don't use

**Comment by Ezrat95** [comment]
What?
I said when I uninstall snapchat they do not ask me if i want to keep or not.

**Comment by bocajthomas** [comment]
> What? I said when I uninstall snapchat they do not ask me if i want to keep or not.

I don't have any logs ?

**Comment by bocajthomas** [comment]
Please redo the guide following the LSPatch + Shizuku

**Comment by Ezrat95** [comment]
that didnt work so someone told me to use SAI


+ I cant give logs because when I try to setup enhance it tells me to allow displaying on top but i cant flip that switch in settings.

**Comment by bocajthomas** [comment]
> is it even correct that in the beginning I install the apks? because in lspatch i tap on apk not installed app.
> 
> even tho enhance is already installed

You haven't followed the guidelines correctly

**Comment by Ezrat95** [comment]
they said whats needed and i installed whats needed. Since they dont mention installing apks in the process i just installed everything in the beginning!
![image](https://github.com/rhunk/SnapEnhance/assets/169616717/b3d75fdd-17bc-4e78-9ea7-9ce64fefd8aa)

**Comment by bocajthomas** [comment]
https://t.me/snapenhance_chat
