### ISSUE TITLE
Display over other Apps Permission 

### ISSUE THREAD

**Issue by Okice28** [rhunk/SnapEnhance#1057]
### Description

Phone does not allow me to grant permission to 'draw over other apps'.
![Screenshot_20240521-172202](https://github.com/rhunk/SnapEnhance/assets/170175854/d0d3e3c3-bfd9-482d-8db6-dd9cfd637a24)

![Screenshot_20240521-172151](https://github.com/rhunk/SnapEnhance/assets/170175854/b0220761-5d8f-4f27-b758-437cb4d38fce)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.87.0.44

### SnapEnhance Version

2.1.0

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Press `learn how to allow access`
