### ISSUE TITLE
feat: Save folder directory

### ISSUE THREAD

**Issue by ReSo7200** [rhunk/SnapEnhance#107]
### Description

It would be nice and easier if the Save file directory option was improved to use the system's pick folder UI instead of the current manual "type the path"

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/04985a8a9a6bfeb1c28eb432496e9dd774a82d0d
