### ISSUE TITLE
Weblate Warning

### ISSUE THREAD

**Issue by finnbusse** [rhunk/SnapEnhance#1072]
### Description

Weblate shows a warning notification if I open it and I cannnot translate. 
Notification:
The VCS repository has many changes from upstream. Please merge the changes manually or set up a push to automate this.

### Reproduction steps

https://hosted.weblate.org/projects/snapenhance/app/#alerts

### Snapchat Version

-

### SnapEnhance Version

-

### Agreement

- [x] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
Should be fixed now, thanks for reporting.
