### ISSUE TITLE
feat: Hide suggestions for adding friends at top of  screen

### ISSUE THREAD

**Issue by iBasim** [rhunk/SnapEnhance#109]
### Description

Hi!

I hope that with the next updates, you will add a feature to hide the suggestion of adding a friend.

![Screenshot_20230627_215434_com snapchat android_edit_56344189912230](https://github.com/rhunk/SnapEnhance/assets/57762287/883aeb2a-77e6-4729-86e9-7b0a71c01100)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/8e06039e8ff035c1995b6058771aaa0571a73945
