### ISSUE TITLE
Debug builds

### ISSUE THREAD

**Issue by LucarioDaBosse** [rhunk/SnapEnhance#1097]
### Description

Hi I just wrote about the snap expiration issue, and waw told to download a debug build. How do I do that through github?

### Reproduction steps

N/A

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
https://github.com/rhunk/SnapEnhance/actions
