### ISSUE TITLE
CANT GET PASSED SELECTING FOLDER

### ISSUE THREAD

**Issue by yoy123** [rhunk/SnapEnhance#1101]
### Description

![Screenshot_2024-06-05-00-01-48-
67_b67b977fc2b52a869888b6127c98edbc](https://github.com/rhunk/SnapEnhance/assets/32031720/b2bd298e-76d8-4b47-a983-83675f3f529b)

![Screenshot_2024-06-05-00-01-57-93_5734e8eb49b4234b62f913f831715b0f](https://github.com/rhunk/SnapEnhance/assets/32031720/d368d491-4661-4956-a52b-4899de266a57)

IM ON ANDROID 14 USING SNAPCHAT VERSION 12.89.0.40.

I TRIED MULTIPLE VERSIONS OF SNAP ENHANCE INCLUDING THE CL VERSION 2.1.0 AND PROPERLY PATCHED. I EVEN WENT TO THE EXTENT TO GIVE STORAGE PERMISSIONS TO THE APP HOPING SOMETHING WOULD APPEAR. NO LUCK 

### Reproduction steps

Install Snapchat 
Login to Snapchat
Download snap enhance 
Enable and add Snapchat to the scope
Restart system
Open snap enhance 
When it gets to choosing a folder, nothing to select 

### Snapchat Version

12.89.0.40

### SnapEnhance Version

2.1.0 and stable versions as well. 

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
INTERESTING ISSUE.

**Comment by yoy123** [comment]
[Log_2024-06-05_17-39-09.txt](https://github.com/user-attachments/files/15596915/Log_2024-06-05_17-39-09.txt)

**Comment by yoy123** [comment]
Let me know if those logs are enough

**Comment by bocajthomas** [comment]
> Let me know if those logs are enough

There not SnapEnhance logs

**Comment by yoy123** [comment]
[snapenhance-logs-1717634264587.zip](https://github.com/user-attachments/files/15598052/snapenhance-logs-1717634264587.zip)

**Comment by bocajthomas** [comment]
> [snapenhance-logs-1717634264587.zip](https://github.com/user-attachments/files/15598052/snapenhance-logs-1717634264587.zip)

There's nothing in the log, try redoing the "error" then resending the .zip

**Comment by yoy123** [comment]
I fixed it somehow. I honestly just uninstalled snapemhance again and since my Snapchat was still patched, when i reinstalled it worked this time. Odd glitch
