### ISSUE TITLE
bug: <Amoled theme doesn't theme 5th Tab>

### ISSUE THREAD

**Issue by tycoon420** [rhunk/SnapEnhance#111]
### Description

Even after enabling amoled theme in Snapenhance and dark mode in App appearance. 5th tab had white portion and not fully dark theme.

### Screenshots

```bash
https://github.com/rhunk/SnapEnhance/assets/11652113/4c1b6c8d-608c-445c-9f26-600029139bbf
https://github.com/rhunk/SnapEnhance/assets/11652113/e156363f-6eb2-45f4-b673-0b58e34b5dc6
https://github.com/rhunk/SnapEnhance/assets/11652113/f01de410-ceb5-4922-8b7c-81c62b4a02f4
```
### Snapchat Version

12.40.0.43

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by RevealedSoulEven** [comment]
That's snapchat side, not our concern. Even they've made disable spotlight as experimental, not an official release so forget they would work on it
