### ISSUE TITLE
Incompatible signature

### ISSUE THREAD

**Issue by SarvanshRaj** [rhunk/SnapEnhance#1117]
### Description

Diffrent signature even if snap is not installed

### Reproduction steps

Installed snap, patched it, ls patch installed the patched version, opened it, showed that module was not properly embedded, uninstalled, reinatalled snap, patched it again, shows diffrent signature, tried again with apk, didn't work

### Logs

```markdown
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.snapchat.android signatures do not match previously installed version; ignoring!
```

### Snapchat Version

12.90.0.46

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
This is not really a SnapEnhance issue

**Comment by QstTheDuck** [comment]
like mentioned before this is not a snap enhanced bug, but this happens when you uninstall an app and your phone keeps some data (like memories, saved accounts, settings etc) you need to fully delete all app data off your phone using a root file explorer
