### ISSUE TITLE
Context menu and remap bug

### ISSUE THREAD

**Issue by RSR1337** [rhunk/SnapEnhance#1134]
### Context menu
As you can see in the screenshot, I enabled 'preview' and 'stealth mode' , but the  text is not visible 

![Screenshot_2024-06-13-21-37-06-29_a63b0f8076346d26cbdc1b971a1da2a7](https://github.com/rhunk/SnapEnhance/assets/52901789/b9a53ce0-2ad9-4619-8cdf-632a275ff488)
![Screenshot_2024-06-13-21-36-34-91_a63b0f8076346d26cbdc1b971a1da2a7](https://github.com/rhunk/SnapEnhance/assets/52901789/6130f054-ba21-4201-9937-a5c324639b72)

### remap
When enabled remap It makes Snapchat crash

I'm using this build 552c1e4

### log
[snapenhance-logs-1718301692703.zip](https://github.com/user-attachments/files/15826843/snapenhance-logs-1718301692703.zip)
[LSPosed_2024-06-13T22_01_12.645762.zip](https://github.com/user-attachments/files/15826830/LSPosed_2024-06-13T22_01_12.645762.zip)

### Snapchat Version

12.90.0.46

### SnapEnhance Version

2.1.0

### Agreement

- [x] This is not a bug regarding Snapchat+.
- [x] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by TheVisual** [comment]
Remap is currently only working on AOSP confirmed maybe others. On OnePlus 12 it isn't working Yet

**Comment by bocajthomas** [comment]
> @RSR1337 Does the bug occur without custom colors?

been testing, from what i can see this has nothing to do with the `colors` feature

**Comment by RSR1337** [comment]
> @RSR1337 Does the bug occur without custom colors?

Occurs with and without custom colors

**Comment by RSR1337** [comment]
> > @RSR1337 Does the bug occur without custom colors?
> 
> been testing, from what i can see this has nothing to do with the `colors` feature

I just clear Snapchat data and it fixed

**Comment by RSR1337** [comment]
Fixed after cleaning Snapchat data
