### ISSUE TITLE
Detected...

### ISSUE THREAD

**Issue by v3noom** [rhunk/SnapEnhance#1138]
### Description

Snapchat notification 

### Reproduction steps

idk how

### Snapchat Version

latest

### SnapEnhance Version

latest

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by TheVisual** [comment]
Duplicate of https://github.com/rhunk/SnapEnhance/issues/1137
