### ISSUE TITLE
Random packagename...

### ISSUE THREAD

**Issue by JaKrIvMa** [rhunk/SnapEnhance#1142]
### Description

Like magisk to hide packagen name.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by RSR1337** [comment]
> ### Description
> Like magisk to hide packagen name.
> 
> ### Agreement
> * [x]  There is no issue already suggesting my feature.

It's already There, use manager

**Comment by JaKrIvMa** [comment]
> > ### Description
> > Like magisk to hide packagen name.
> > ### Agreement
> > 
> > * [x]   There is no issue already suggesting my feature.
> 
> It's already There, use manager

Where in manager is this?😃

**Comment by authorisation** [comment]
Duplicate of #21
