### ISSUE TITLE
New Bypas ban by jacob!

### ISSUE THREAD

**Issue by BrandonSchiller** [rhunk/SnapEnhance#1147]
### Description

https://github.com/rhunk/SnapEnhance/assets/173345977/c0487d56-7f4b-4f82-b582-c76a606f574b

https://github.com/bocajthomas/SE-Extended

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment]
@authorisation @rhunk take this down fast asap
