### ISSUE TITLE
++ Add

### ISSUE THREAD

**Issue by zNexwr** [rhunk/SnapEnhance#1154]
### Description

- Change name color (anyone can see names in color too)
- Add a button to add everyone at once in the quick addition.
Change the number of views on a story and change the number of screenshots.
![Screenshot_20240629_134500_RVX](https://github.com/rhunk/SnapEnhance/assets/101870034/0ff8a143-beb9-46c3-adcd-642fcb6fc7df)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
> Change name color (anyone can see names in color too)

Use feature `Snapchat
