### ISSUE TITLE
Gallery pic/vid album cannot be send in "snap" form.

### ISSUE THREAD

**Issue by Gissa01** [rhunk/SnapEnhance#1155]
### Description

Previous updates ago, if you wanted to send a picture or video from your gallery to someone on snapchat you had the option to either send it directly to the chat or send it as a snap. Now this function is gone and if I want to send something it goes directly to the chat. If it isn't gone please tell me how to activate it? 

### Reproduction steps

1. Go to gallery or photo/video album and select something you want to share and click on the snapchat friend you would like to share with.
2. It will lead you to the snapchat app. From there you should have options in what way you would like to get this send. You had 4 options (from which 2 I don't remember anymore because I never used it. The other 2 options were send it as a "snap" or "chat.

### Snapchat Version

12.93.0.43

### SnapEnhance Version

2.0.1 all release

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by QstTheDuck** [comment]
just used this 5 minutes ago, it still there. make sure you have "gallery media send override" to always ask and that native hooks is enabled and working
