### ISSUE TITLE
See if a snap is sent exclusively to you...

### ISSUE THREAD

**Issue by Jordan1233221** [rhunk/SnapEnhance#1163]
### Description

It says in 2.0.0 that i could see if a snap is sent exclusively to me. I am on 2.0.1, but i cant find the feature

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.95.0.41

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
Fidelius indicator

**Comment by Jordan1233221** [comment]
I cant find the fidelius indicator
