### ISSUE TITLE
bug: Not working on Android 14 Beta 3 non root

### ISSUE THREAD

**Issue by dnestico** [rhunk/SnapEnhance#117]
### Description

I have followed all steps from the telegram and downloaded LSPatch by following a video guide and I see SnapEnhance under the modules section. 

Problem is I click the 3 dots in the chat screen and see nothing, it could be user error as I'm not experienced with rooting stuff but please help.

### Reproduction steps

```bash
1. Install Snapchat latest version
2. Install SnapEnhanced
3. Install lsposed with shizuku
4. Restart device
5. Make sure shizuku is running and detected lsposed
6. Open snapchat
```

### Screenshots

![Screenshot_20230703-174847.png](https://github.com/rhunk/SnapEnhance/assets/3034555/7ec2511c-6c48-484f-b40a-252a49d56d68)

![Screenshot_20230703-174836.png](https://github.com/rhunk/SnapEnhance/assets/3034555/ac4a8e01-9a79-4767-a986-964b4f765e20)

![Screenshot_20230703-174857.png](https://github.com/rhunk/SnapEnhance/assets/3034555/a4b955f1-e7f6-41e9-bffb-c54de5055dea)

### Snapchat Version

12.42.0.45 beta

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by ReSo7200** [comment]
You have to go to the manage section in the LSPatch app, and make a new patch, the first one with snapchat having snapenhance module, and the second one is having snapenhance with snapenhance module.

**Comment by dnestico** [comment]
It worked! 🤯 

I knew it was error on my part, thanks.

**Comment by vvirtues** [comment]
I know this thread is closed but can you give clearer instructions from the top? I'm trying to get this to work but it isn't working
