### ISSUE TITLE
feat: Option to download at time of receiving snap

### ISSUE THREAD

**Issue by RichardGouda** [rhunk/SnapEnhance#119]
### Description

Is it possible to have the option to download at the time of receiving snaps?

If the show media option is enabled under better notifications, the media is already downloaded so would it be possible to save it at this point or any other other way of implementing it.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/pull/130/commits/6cbd6a22d3f53e9c58c4172dc2185e3ccef99980
