### ISSUE TITLE
i think i know why it's getting detected

### ISSUE THREAD

**Issue by vodkacsa** [rhunk/SnapEnhance#1190]
### Description

i always got timed out when i opened Snapchat so i removed the snapenhanced Snapchat and installed the normal one
i still got timed out → i think Snapchat checks ur storage to find snapenhance and will time you out if it finds it (i might be wrong, but this seems pretty logical)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by suryadip2008** [comment]
> ### Description
> i always got timed out when i opened Snapchat so i removed the snapenhanced Snapchat and installed the normal one i still got timed out → i think Snapchat checks ur storage to find snapenhance and will time you out if it finds it (i might be wrong, but this seems pretty logical)
> 
> ### Agreement
> * [x]  There is no issue already suggesting my feature.

Nice logic, but things aren't that simple as they seem to be.

**Comment by authorisation** [comment]
Keep detection related things to #1137
