### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by MCcoolman** [rhunk/SnapEnhance#1192]
### Description

Tried to patch the app with lspatch and when i start the app it just shows the yellow start screen with the logo

### Reproduction steps

Open the app

### Snapchat Version

13.1.0.43

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
Duplicate of #108
