### ISSUE TITLE
snap+ spoofer bug

### ISSUE THREAD

**Issue by Str8mudwater** [rhunk/SnapEnhance#1195]
### Description

you can't pin #1 bsf w snap+ spoofer 

### Reproduction steps

open snap+ menu
click pin as #1 bsf
click anyone
hit yes/confirm 
error

### Snapchat Version

12.81.44

### SnapEnhance Version

2.0.1

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
That's because its `server-sided`, Use feature `Best Friend Pinning` This can be found in `Experimental`

**Comment by Str8mudwater** [comment]
> That's because its `server-sided`, Use feature `Best Friend Pinning` This can be found in `Experimental`

I don't have said option?

**Comment by suryadip2008** [comment]
> > That's because its `server-sided`, Use feature `Best Friend Pinning` This can be found in `Experimental`
> 
> I don't have said option?

Please use the latest version of SE.

**Comment by Str8mudwater** [comment]
> > > That's because its `server-sided`, Use feature `Best Friend Pinning` This can be found in `Experimental`
> > 
> > I don't have said option?
> 
> Please use the latest version of SE.

2.0.1? I checked there isn't a new one
