### ISSUE TITLE
Debug CI #59 shows failed to initialize the bridge 

### ISSUE THREAD

**Issue by IamNickerson** [rhunk/SnapEnhance#1198]
### Description

Snapenhance-2.1.0-armv8-f97dda6 doesn't initialize the bridge.

### Reproduction steps

Just use the debug build f97dda6 in the actions tab.

### Snapchat Version

13.2.0.41

### SnapEnhance Version

13.2.0.41 (f97dda6)

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by RSR1337** [comment]
Same here

**Comment by suryadip2008** [comment]
@IamNickerson That's an issue with `Native`. Happens due to the recent refractor of the code to rust.

**Comment by IamNickerson** [comment]
> @IamNickerson That's an issue with `Native`. Happens due to the recent refractor of the code to rust.

But f97dda6 build needs to be remove asap or else ppl will start to find problems

**Comment by IamNickerson** [comment]
Its working now thanks
