### ISSUE TITLE
bug: - Cannot post unlimited timed videos to stories 

### ISSUE THREAD

**Issue by TheVisual** [rhunk/SnapEnhance#12]
### Description

while i can post non split / unlimited in snapchat /  chats I cannot on storys

### Reproduction steps

```bash
1. Go to camera roll on sc
2. Click on video
3. See error (no send button)
```

### Screenshots

```bash
https://cdn.discordapp.com/attachments/1071627543104467044/1113478156259696660/Screenshot_2023-05-31-09-44-23-11_a63b0f8076346d26cbdc1b971a1da2a7.jpg
```

### Snapchat Version

12.35.0.45

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by RSR1337** [comment]
I have same issue
- can't upload more than 1 minute from camera roll ( only work from chat ) 
- disable snap splitting not working when you upload video from memory or snaps

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/fe0b82c75b81c0048cf89a1b19b16113108415a1

**Comment by authorisation** [comment]
If the issue still persists let us know from our testing it should be fixed.
