### ISSUE TITLE
*FIXED* can't install Snapchat anymore

### ISSUE THREAD

**Issue by omexman** [rhunk/SnapEnhance#1224]
### Description

After a warning that my snap version is too old and snap noticed that I was using external stuff I wanted to upgrade and uninstalled old version and downloaded a new APK when I wanted to install it, it didnt work I thought it was because of the APK then I tried on Playstore it didn't work too so now for 1 month I don't know what to do and what I did wrong I can't install snapchat anymore whether APK or Playstore it doesn't work

### Reproduction steps

I have uninstalled snapchat and used SnapEnhance already and did nothing in SnapEnhance just uninstalled snapchat and when I had a new apk I installed the apk and there comes an error that it does not work just like in the Playstore there comes an error that the app cannot be installed

### Snapchat Version

12.88.0.43

### SnapEnhance Version

2.0.1

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by shaunbharat** [comment]
1. Download and install the adb (Android Device Bridge) command-line tool on a computer.

2. Connect your Android phone to the computer using a USB cable. Make sure USB debugging is enabled in the developer settings of your phone.

3. Run `adb devices` to make sure your phone is connected properly.

4. Unlock your phone to the home screen, then run `adb shell pm uninstall com.snapchat.android`.

5. Unplug your phone, and turn off USB debugging. Try re-installing Snapchat from Google Play Store. A restart might be needed before.

**Comment by omexman** [comment]
Wow... Thanks for the help it's wierd that you can't delete this file on your phone and that you have to do it through such a  complicated way i did it wrong at first but this tutorial helped a lot https://www.youtube.com/watch?v=GERlhgCcoBc and made this all easy 5min work...

**Comment by sathwik7668** [comment]
Thanks, worked for me

**Comment by sexyshikxy** [comment]
Wow. same like magic . Thanks for the help this is a miracle
