### ISSUE TITLE
...cant find the correct file

### ISSUE THREAD

**Issue by Itsfutile00** [rhunk/SnapEnhance#1225]
### Description

Hello I'm on a Redmi  and I canot find the right file for the app
![image](https://github.com/user-attachments/assets/e0c65624-6f32-45e5-aa26-edeee3b24699)
![Screenshot_2024-08-27-21-54-00-096_com google android documentsui](https://github.com/user-attachments/assets/912d73a9-0b1b-4d14-9cd8-6acc50a5a1d9)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

13.4.0.45.

### SnapEnhance Version

2.0.1

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by suryadip2008** [comment]
> ### Description
> Hello I'm on a Redmi and I canot find the right file for the app ![image](https://private-user-images.githubusercontent.com/179640365/361953878-e0c65624-6f32-45e5-aa26-edeee3b24699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3OTA2OTQsIm5iZiI6MTcyNDc5MDM5NCwicGF0aCI6Ii8xNzk2NDAzNjUvMzYxOTUzODc4LWUwYzY1NjI0LTZmMzItNDVlNS1hYTI2LWVkZWVlM2IyNDY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QyMDI2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjBjMjMwOTM4ZTk3YzVlZDExMzJmMTI1OWRjYThhNDgzZWZjMTU0OGFlYjM0YTI3NmUwMWI1N2MxNzJlOTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tj3XzvjDGdYGkF-xh2Tgnqz0E4l5abNphQqAaVs3aE0) ![Screenshot_2024-08-27-21-54-00-096_com google android documentsui](https://private-user-images.githubusercontent.com/179640365/361953928-912d73a9-0b1b-4d14-9cd8-6acc50a5a1d9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3OTA2OTQsIm5iZiI6MTcyNDc5MDM5NCwicGF0aCI6Ii8xNzk2NDAzNjUvMzYxOTUzOTI4LTkxMmQ3M2E5LTBiMWItNGQxNC05Y2Q4LTZhY2M1MGE1YTFkOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QyMDI2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTkzYjFkMjk5OGViZjVkNTRiM2QzOTg3YzJkZGFmM2ViMTAyNzdlNGU0MzMwYTgzNzY0YzAwZDA0ZWRiNWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ChDYgJZO2dFh_4lqb-IBbY0W_fjyh-KVa0X5KKqF6Is)
> 
> ### Reproduction steps
> 1. Go to `...`
> 2. Click on `....`
> 3. Scroll down to `....`
> 4. See error.
> 
> ### Logs
> _No response_
> 
> ### Snapchat Version
> 13.4.0.45.
> 
> ### SnapEnhance Version
> 2.0.1
> 
> ### Agreement
> * [ ]  This is not a bug regarding Snapchat+.
> * [ ]  I have provided a detailed description of the issue.
> * [ ]  I have attached a log if deemed necessary.
> * [ ]  This issue is not a duplicate.

You have to create a new folder first.
Create a new folder and then click on `Use this folder`.

**Comment by Itsfutile00** [comment]
Ok thank you
