### ISSUE TITLE
bug: without opening snap enhance the snapchat app not opening 

### ISSUE THREAD

**Issue by Ashhwnl12** [rhunk/SnapEnhance#125]
### Description

everytime when i need to open snapchat i just need to open the snap enhance app first then snapchat was working . when i directly open snapchat the start menu stucks at yellow page just loading nd loading.

### Reproduction steps

```bash
clear all apps from background and open snapchat without opening mod first
```

### Screenshots

```bash
https://photos.app.goo.gl/MVPU4n4bxc4HzVQr8
```

### Snapchat Version

12.41.0.54

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by No0099** [comment]
I have the same problem on galaxy s23

**Comment by Domiiniik** [comment]
I Have the same issue on S21 FE, to fix this you Gotta constantly reset mappings

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/c28a08f788861a5684691fc6237b4e12d79c1758
