### ISSUE TITLE
media upload

### ISSUE THREAD

**Issue by lovibhai** [rhunk/SnapEnhance#1289]
### Description

i tried turning on the media picker and gallery override still the media upload is showing on snap when i remix and send

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

13.13.0.36

### SnapEnhance Version

v2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by lovibhai** [comment]
> What a bad "bug report" lol. No infos about the specific versions used ("latest") nor anything else that could be helpful. Also, this isn't a bug. Sending gallery media as snap is working as intended in every version I've tried (12.70, 12.80, 12.81). No "media upload" whatsoever.

snapchat version 13.13.0.36 and snap enhance version v2.0.1 and bro instead of helping your pointing out at the report i thought people would understand if i write latest well my bad for writing latest only and pls can you help me respectfully? :)

**Comment by NMBlanco** [comment]
> > What a bad "bug report" lol. No infos about the specific versions used ("latest") nor anything else that could be helpful. Also, this isn't a bug. Sending gallery media as snap is working as intended in every version I've tried (12.70, 12.80, 12.81). No "media upload" whatsoever.
> 
> snapchat version 13.13.0.36 and snap enhance version v2.0.1 and bro instead of helping your pointing out at the report i thought people would understand if i write latest well my bad for writing latest only and pls can you help me respectfully? :)

Version 13.13 lol, your account will be locked tomorrow. If you would actually read through this repo (the readme for example) for once then it would answer all your questions.

**Comment by lovibhai** [comment]
> > > What a bad "bug report" lol. No infos about the specific versions used ("latest") nor anything else that could be helpful. Also, this isn't a bug. Sending gallery media as snap is working as intended in every version I've tried (12.70, 12.80, 12.81). No "media upload" whatsoever.
> > 
> > 
> > snapchat version 13.13.0.36 and snap enhance version v2.0.1 and bro instead of helping your pointing out at the report i thought people would understand if i write latest well my bad for writing latest only and pls can you help me respectfully? :)
> 
> Version 13.13 lol, your account will get locked tomorrow. If you would actually read through this repo (the readme for example) for once then it would answer all your questions.

bro how to view that readme or whatever im new to this site and having a hard time finding things

**Comment by NMBlanco** [comment]
Have you tried scrolling down and reading through EVERYTHING? Have you tried reading the red-colored "Caution" text block, where it says the recommended version is 12.81 or lower? 
Your account will get locked tomorrow, they usually do a ban wave on every friday.

**Comment by lovibhai** [comment]
> Have you tried scrolling down and reading through EVERYTHING? Have you tried reading the red-colored "Caution" text block, where it says the recommended version is 12.81 or lower? Your account will get locked tomorrow because you used a version above 12.81. They usually do a ban wave on every friday.

I've read it thanks and which version of the snap enhance should i use it that fine with the lastest or a lower version with ghst l
