### ISSUE TITLE
feat: <title>Instead of lsposed Am dedicated App for Root users

### ISSUE THREAD

**Issue by imvinod07** [rhunk/SnapEnhance#129]
### Description

suggestion #Request As for root users can't we have an app instead of lsposed 🥹 due to lsposed most of banking apps not working

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rathmerdominik** [comment]
That is not a very good argumentation

There is a bypass for that readily available

[MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

And

[SafetyNet Fix](https://github.com/kdrag0n/safetynet-fix)

This lets you pass ctsProfile and Basic integrity
