### ISSUE TITLE
Snapenhance failing to generating mappings

### ISSUE THREAD

**Issue by L-Ingwor** [rhunk/SnapEnhance#1292]
### Description

Running samsung note 9 rooted with magisk v28, LSPosed v1.10.1 (7119) debug.
Snapenhance can't generate mappings without failing, causing snapchat to constantly crash.

### Reproduction steps

1. Install snapchat version 12.59.0.62
2. Install snapenhance 2.1.0 armv8 or armv7
3. Run snapenhance, try generate mappings (security features on or off)
4. '3 warnings occurred while generating mappings'
5. snapchat will instantly crash if it is opened

![20241029_160258](https://github.com/user-attachments/assets/7a8f4646-ca68-413d-8115-16e330f1a633)

### Logs

```markdown
|W/2024-10-29 16:04:54/manager/3 warning(s) occurred while generating mappings:

Failed to serialize property runFriendDurableJob in FriendRelationshipChanger
Failed to serialize property class in MemoriesPresenter
Failed to serialize property onNavigationEventMethod in MemoriesPresenter
|V/2024-10-29 16:04:57/manager/Loading RemoteSideContext
|I/2024-10-29 16:04:58/manager/sif is up to date (compat_test-0.0.2)
|W/2024-10-29 16:05:40/manager/3 warning(s) occurred while generating mappings:

Failed to serialize property runFriendDurableJob in FriendRelationshipChanger
Failed to serialize property class in MemoriesPresenter
Failed to serialize property onNavigationEventMethod in MemoriesPresenter
|V/2024-10-29 16:05:42/manager/Loading RemoteSideContext
|I/2024-10-29 16:05:43/manager/sif is up to date (compat_test-0.0.2)
|D/2024-10-29 16:05:49/manager/Saving logs, this may take a while ...
```

### Snapchat Version

12.59.0.62

### SnapEnhance Version

2.1.0 - 721106a

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [x] This issue is not a duplicate.

**Comment by suryadip2008** [comment]
> ### Description
> Running samsung note 9 rooted with magisk v28, LSPosed v1.10.1 (7119) debug. Snapenhance can't generate mappings without failing, causing snapchat to constantly crash.
> 
> ### Reproduction steps
> 1. Install snapchat version 12.59.0.62
> 2. Install snapenhance 2.1.0 armv8 or armv7
> 3. Run snapenhance, try generate mappings (security features on or off)
> 4. '3 warnings occurred while generating mappings'
> 5. snapchat will instantly crash if it is opened
> 
> ![20241029_160258](https://private-user-images.githubusercontent.com/86875482/380966321-7a8f4646-ca68-413d-8115-16e330f1a633.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjg1NTQsIm5iZiI6MTczMDI2ODI1NCwicGF0aCI6Ii84Njg3NTQ4Mi8zODA5NjYzMjEtN2E4ZjQ2NDYtY2E2OC00MTNkLTgxMTUtMTZlMzMwZjFhNjMzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA2MDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYmI0MzI1NjFmOGQzOTU2MjViM2Q4NWMwMmJhZTliZWQ0Y2UzMzExZWJmMDQ0ZjJkMDNjNDUwZDAyOGY0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g1BmfT-MYJVoZmHKZ18L13wQHjmQFnbwNPPeYFrNAcQ)
> 
> ### Logs
> ```
> |W/2024-10-29 16:04:54/manager/3 warning(s) occurred while generating mappings:
> 
> Failed to serialize property runFriendDurableJob in FriendRelationshipChanger
> Failed to serialize property class in MemoriesPresenter
> Failed to serialize property onNavigationEventMethod in MemoriesPresenter
> |V/2024-10-29 16:04:57/manager/Loading RemoteSideContext
> |I/2024-10-29 16:04:58/manager/sif is up to date (compat_test-0.0.2)
> |W/2024-10-29 16:05:40/manager/3 warning(s) occurred while generating mappings:
> 
> Failed to serialize property runFriendDurableJob in FriendRelationshipChanger
> Failed to serialize property class in MemoriesPresenter
> Failed to serialize property onNavigationEventMethod in MemoriesPresenter
> |V/2024-10-29 16:05:42/manager/Loading RemoteSideContext
> |I/2024-10-29 16:05:43/manager/sif is up to date (compat_test-0.0.2)
> |D/2024-10-29 16:05:49/manager/Saving logs, this may take a while ...
> ```
> 
> ### Snapchat Version
> 12.59.0.62
> 
> ### SnapEnhance Version
> 2.1.0 - [721106a](https://github.com/rhunk/SnapEnhance/commit/721106ae2bdb77e5aaa082dd8b8ec7779ccdba2e)
> 
> ### Agreement
> * [x]  This is not a bug regarding Snapchat+.
> * [x]  I have provided a detailed description of the issue.
> * [x]  I have attached a log if deemed necessary.
> * [x]  This issue is not a duplicate.

Did you enable Snapchat in Snapenhance's scope in Lsposed first?? After enabling, you also need to restart your phone and then generate mappings and all...

**Comment by L-Ingwor** [comment]
I enabled it in LSPosed each time I reinstalled it, I have tried restarting between enabling the module and opening snapenhance with no change. I have also tried LSPosed_mod v1.19.3 (7244) debug. The latest version of snapchat + SE that works for me is snapchat 12.45.0.55 and SE 2.1.0-4b93ec7 but some modules don't work (e.g. bootstrap)

**Comment by suryadip2008** [comment]
> I enabled it in LSPosed each time I reinstalled it, I have tried restarting between enabling the module and opening snapenhance with no change. I have also tried LSPosed_mod v1.19.3 (7244) debug. The latest version of snapchat + SE that works for me is snapchat 12.45.0.55 and SE 2.1.0-4b93ec7 but some modules don't work (e.g. bootstrap overide)

Try this version of Lsposed: [Link](https://nightly.link/JingMatrix/LSPosed/actions/runs/11575244134)
Download the **Debug** one.

And also install this version of SE: [Link](https://nightly.link/rhunk/SnapEnhance/actions/runs/10585181221)

Lemme know if this works!

**Comment by L-Ingwor** [comment]
I downloaded both, tried them with snapchat 12.81 and 12.59 and neither threw errors, the logs don't say anything out of the ordinary but in both versions snapchat instantly crashes if i try to open it. I tried turning off security features and it didn't affect it.

**Comment by L-Ingwor** [comment]
Just tried LSPosed-Irena with snapchat 12.81 and SE version 2.1.0 721106a and 6fed85b. It didn't have any errors when generating mappings but snapchat still crashed as soon as I opened it

**Comment by L-Ingwor** [comment]
It opens without module, I can pass Basic and Device but not Strong, there are no apps in my denylist.

**Comment by L-Ingwor** [comment]
how do I use a keybox to pass strong?

**Comment by VendorAttestation** [comment]
https://github.com/JingMatrix/LSPosed/releases/tag/v1.10.1

Use this i tested and works


As for PI/Keybox its not needed don't listen to these people login doesn't check that idk why you people think this stuff

**Comment by L-Ingwor** [comment]
thanks for the advice, sadly even with LSPosed v1.10.1 snapchat still crashes on opening and the SE logs don't have any errors.

**Comment by VendorAttestation** [comment]
> 1. Install snapchat version 12.59.0.62

use https://www.apkmirror.com/apk/snap-inc/snapchat/snapchat-12-81-0-44-release/


it's working why use that old ass version

**Comment by L-Ingwor** [comment]
because as of creating this issue, the latest installation guide in the telegram channel said to install SE on 12.59 and then update to 12.81. this never worked for me, nor has installing SE into 12.81 but I thought I would try the suggested options. the only version I can get SE working on so far is 12.45

**Comment by VendorAttestation** [comment]
> because as of creating this issue, the latest installation guide in the telegram channel said to install SE on 12.59 and then update to 12.81. this never worked for me, nor has installing SE into 12.81 but I thought I would try the suggested options. the only version I can get SE working on so far is 12.45

Sounds like a fake guide tbh i never did that

**Comment by L-Ingwor** [comment]
ok I rolled back to the SE 2.1 release and everything works so Ill just not use debug builds. Thank you for your guy's help.
