### ISSUE TITLE
bug: - <Can't open app>

### ISSUE THREAD

**Issue by Dullma999** [rhunk/SnapEnhance#13]
### Description

Hi,i tried app today on s23ultra, i installed few different versions but phone does not even open the app.when i click on icon.nothing happens

### Reproduction steps

```bash
1. Go to main screen
2. Click on snapenchancer
3. See error (nothing happens)app doesnt open
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Snapchat Version

12.32.0.35

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by Zektra** [comment]
It is not an app you can open. You open Snapchat, go to your contacts screen, then press the three dots for the snapenhance menu. Make sure SnapEnhance is enabled in LSPosed, and that Snapchat is selected as app it affects.
