### ISSUE TITLE
Batterie drain

### ISSUE THREAD

**Issue by 13y87t** [rhunk/SnapEnhance#1306]
### Description

When I use snapehance I need to charge my device 3x a day instead of 1x in normal conditions. 
What can I do ? 

### Reproduction steps

1. Use snapehance

### Snapchat Version

11.84.0.16

### SnapEnhance Version

2.0.1

**Comment by 13y87t** [comment]
I allready know wich app cause this, hence my post ^^
-------- Message d'origine --------De : kamharry ***@***.***> Date : 03/12/2024  10:41  (GMT+01:00) À : rhunk/SnapEnhance ***@***.***> Cc : 13y87t ***@***.***>, Author ***@***.***> Objet : Re: [rhunk/SnapEnhance] Batterie drain (Issue #1306) 
Check in battery section of ur device which app is causing battery drain

**Comment by 13y87t** [comment]
I allready know wich app cause this, hence my post ^^

**Comment by wxnnvs** [comment]
I have no issues with this

**Comment by 13y87t** [comment]
> bro you gotta be joking
> 
> Snapchat Version 11.84.0.16
> 
> Released | 23 Jun 2022
> 
> Close this

Yes I don't update. And ?
