### ISSUE TITLE
Message translator(hopefully)

### ISSUE THREAD

**Issue by robinbood** [rhunk/SnapEnhance#1307]
### Description

caan you add messaage translator to it..like dev4mod did it with his whatsappenancer..(he added google-translator)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by suryadip2008** [comment]
> ### Description
> caan you add messaage translator to it..like dev4mod did it with his whatsappenancer..(he added google-translator)
> 
> ### Agreement
> * [x]  There is no issue already suggesting my feature.

Duplicate of https://github.com/rhunk/SnapEnhance/issues/1114
