### ISSUE TITLE
Android action menu v2 crashes

### ISSUE THREAD

**Issue by kamharry** [rhunk/SnapEnhance#1308]
### Description

After the new update snapchat is crashing when holding a chat in dm
Disabling action menu v2 fixes the problem

### Reproduction steps

1. Go to chat
2. Hold msg in chat
4. Snapchat crashes

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.1.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by RSR1337** [comment]
Same issue

**Comment by wsg788** [comment]
Same issue, also what is action menu v2 and how do I disable it?

**Comment by ar5to** [comment]
> Same issue, also what is action menu v2 and how do I disable it?

Downgrade

**Comment by rhunk** [comment]
someone can try this ci build : https://github.com/rhunk/SnapEnhance/actions/runs/12421795181

**Comment by NMBlanco** [comment]
> someone can try this ci build : https://github.com/rhunk/SnapEnhance/actions/runs/12421795181

Thank you for trying, it still crashes though.
I attached the log.
[LSPosed_2024-12-19T23_42_35.819948.zip](https://github.com/user-attachments/files/18203874/LSPosed_2024-12-19T23_42_35.819948.zip)

**Comment by rhunk** [comment]
@NMBlanco try this ci build it should be fixed : https://github.com/rhunk/SnapEnhance/actions/runs/12422289278/job/34683694178

**Comment by NMBlanco** [comment]
Can confirm it is fixed now! Thank you @rhunk
