### ISSUE TITLE
bug: message content on notifications

### ISSUE THREAD

**Issue by CanerKaraca23** [rhunk/SnapEnhance#136]
### Description

i can see the text message content on my notifications. But when message sender manually replies my message, i can't see the message on notifications. It says "x user repliled your message".

### Reproduction steps

```bash
reply a message and see
```

### Snapchat Version

12.41.0.54

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/pull/130/commits/d88954c8054ce7384eef1ebd553d08d94c32eaf1
