### ISSUE TITLE
feat: Streaks notification

### ISSUE THREAD

**Issue by TeamBattino** [rhunk/SnapEnhance#139]
### Description

Send the user a notification if theyre getting close to losing a snap streak. (maybe let the user decide what they consider "close to losing")

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by aayushrautela** [comment]
That would definitely be great.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/3eb8c8f015380da1b9f5319ba869f082f7925970
