### ISSUE TITLE
feat: Partial chat export

### ISSUE THREAD

**Issue by RevealedSoulEven** [rhunk/SnapEnhance#141]
### Description

I've a 1 year long chat and it always takes 40-45 minutes to load the conversation completely even I'm using 5G high speed data so internet is not an issue.

Everytime I want to export the chat, I can't keep scrolling to the top of the saved media.

Please add a toggle in export section to export only the partial data which is loaded in local database (this was issue in snapmod, but required) and if the toggle is off, it would load all previous conversation and export the chat in the next decades.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/33131728cadbb3e203d17ddec4bf2814b714137c
