### ISSUE TITLE
bug: Hide Story Section

### ISSUE THREAD

**Issue by BrilliantlyEducated** [rhunk/SnapEnhance#142]
### Description

Hide friends section, does not work

### Reproduction steps

```bash
go to SnapEnhance and then tap on the bug after that tap on SnapEnhance settings and then scroll down till you find Hide Story Section, tap on it and enable Hide friends section
```

### Snapchat Version

v12.43.0.56

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by homesquares** [comment]
deleted.
