### ISSUE TITLE
feat: open each snaps given by a user

### ISSUE THREAD

**Issue by Fl0werHakeS** [rhunk/SnapEnhance#148]
### Description

Give the user option to automatically open all snaps instantly w/o viewing them example you have streak with someone but cba to open there snaps and they sent like 45+ shit then just have it done automatically

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by CanerKaraca23** [comment]
Thanks, just as I was about to open it, I saw that it was already open. Simply add button to mark all snaps as seen. And it will be great also adding send automatic black photo to prevent streak loss. But it's hard to make this feature i guess.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/4b49d669b7ec8ee0599f621b64b3e8ad674a5dfe
