### ISSUE TITLE
bug: Startup Override left camera activity open in background 

### ISSUE THREAD

**Issue by RevealedSoulEven** [rhunk/SnapEnhance#160]
### Description

Like if you change startup page to say "Chat" then also snapchat is using your camera (as I can see the indicator in Android 13) also if you accidentally press the volume keys, it will capture the snap and show you your depressed face 😐
Please make the camera activity completely stopped for that moment when snapchat is initially loaded IF startup page override is active.

### Reproduction steps

```bash
.
```

### Snapchat Version

12.44.0.59

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/87c5f7dc55839a38929463e7fd8d1dac65fcb368
