### ISSUE TITLE
App crash on select save folder popup

### ISSUE THREAD

**Issue by Nicolai-Holmgaard** [rhunk/SnapEnhance#170]
### Description

When I go into the settings of snap enhance, I get a popup for selecting a save folder. There is 2 buttons: cancel or select. When I press either of them, the app just crashes. 

### Reproduction steps

1. Go to snap enhance 
2. Click on settings
3. Click in the pop up
4. Crash

### Snapchat Version

12.44.0.59

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by TheVisual** [comment]
To help the dev's please provider logs and device specs

Example:
Android Version:
Phone Model:
Custom Rom:

The amount of data given no one can solve 🤔

**Comment by Nicolai-Holmgaard** [comment]
Android Version: 13
Phone Model: OnePlus 8T
Custom Rom: yes, evolution x 13

I have had this working before, but after updating, the bug came. 
I can click outside of the popup to use it.

**Comment by Nicolai-Holmgaard** [comment]
App also crashes when clicking on save folder option in the settings
