### ISSUE TITLE
bug (?): anonymous story view seems bugged

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#177]
### Description

So idk if its supposed to be like that or if its actually a little bugged.
Today I set my other phone up with stock snapchat and tested all the snapenhance features on my main phone.
At first it seems that the "anonymous story view" feature works as it should when you enable it.
But if you want to mark the story later as seen, and disable it again, it will still hide that you viewed the story.
Clearing snapchat from the recents also doesn't work, and the story won't get marked as viewed on the other phone.

I then found out, that you have to clear snapchat from the recents from the phone with which you've UPLOADED the story. Only after doing this, it will magically show that I've viewed the story from my main phone.
Is this intended to be like this? It seems really strange.

I've already submitted a feature suggestion which might handle this better (https://github.com/rhunk/SnapEnhance/issues/172#issue-1837685905)

### Reproduction steps

See above

### Snapchat Version

12.45.0.55 with SnapEnhance 1.2.1 stable

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/9dc61b62158b84a50149632c7ea95a12d4b3be73
could you try the latest ci to make sure it works for you?

**Comment by NMBlanco** [comment]
> fixed in [9dc61b6](https://github.com/rhunk/SnapEnhance/commit/9dc61b62158b84a50149632c7ea95a12d4b3be73) could you try the latest ci to make sure it works for you?

Yes works perfectly fine now with 9dc61b6 Ci build!
Thanks a lot!
