### ISSUE TITLE
chat exporting bug

### ISSUE THREAD

**Issue by dovisp** [rhunk/SnapEnhance#179]
### Description

Newest snapenhance throws a funi error when i try to export chats. and it looks like this when opened.
![IMG_20230807_184522_896](https://github.com/rhunk/SnapEnhance/assets/64722645/11f72840-84a9-4af5-b1f1-776fb9f1a0ed)
![IMG_20230807_184519_497](https://github.com/rhunk/SnapEnhance/assets/64722645/b1473840-543e-4e54-8b3d-e3d0edcebcdb)
**And the "newest" 1.1.0 ci build doesn't have this issue(commit 968718c)**

### Reproduction steps

1. Go to ...
2. Click on "Export chat messages"
3. Use HTML as the export type(i think it occurs in other export types too)
4. See error.

### Snapchat Version

12.45.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by dovisp** [comment]
**newest stable 1.2.1**
![image](https://github.com/rhunk/SnapEnhance/assets/64722645/9c8d919b-61f6-48d5-b31a-da04a0afb0cc)
![image](https://github.com/rhunk/SnapEnhance/assets/64722645/e14035b7-a20a-46c1-b116-48ee4812d9a6)
![image](https://github.com/rhunk/SnapEnhance/assets/64722645/86da22bb-62f1-4f8b-a153-4c4ffb89c5aa)
**meanwhile with 968718c version**
![image](https://github.com/rhunk/SnapEnhance/assets/64722645/df72a1af-0ba5-4437-86be-dce95563e921)
![image](https://github.com/rhunk/SnapEnhance/assets/64722645/7c16241e-1bb5-4324-84a4-5946fba40253)
![image](https://github.com/rhunk/SnapEnhance/assets/64722645/766a658f-3dc2-4d81-a74f-ab696fc91e09)

**Comment by dovisp** [comment]
> Could you check if there are any errors in the dev console when opening the HTML File?

^

**Comment by dovisp** [comment]
interesting, newest ci does work

**Comment by dovisp** [comment]
There is a new "bug", if you have the .html big enough, it will show a blank page. Both chats are taken in CI 44eccb66.


First exported chat(the smaller one):
![1st](https://github.com/rhunk/SnapEnhance/assets/64722645/dffe9665-76d5-4f69-b363-e9dd697c146d)

Second exported chat(the bigger one):
![2nd](https://github.com/rhunk/SnapEnhance/assets/64722645/0406a48e-968f-4e52-968c-9172e22eebb4)

Both names and sizes:

![3d](https://github.com/rhunk/SnapEnhance/assets/64722645/6fac99ac-70a7-4477-b45d-e74203113041)

**Comment by authorisation** [comment]
Are you sure that it's not just rendering very long?

**Comment by dovisp** [comment]
i don't think so. firefox shows a white page without any indication that it is loading, while chrome screams with aw, snap! error code: status_breakpoint.

**Comment by authorisation** [comment]
Show me the console output

**Comment by dovisp** [comment]
![image](https://github.com/rhunk/SnapEnhance/assets/64722645/ecc89e5f-06f9-4f78-a413-ba08cc6042a6)

**Comment by bocajthomas** [comment]
I can confirm it's blank

**Comment by authorisation** [comment]
![image](https://github.com/rhunk/SnapEnhance/assets/64337177/05ea30b4-97bf-47fb-b6f6-e8017de68488)
https://stackoverflow.com/questions/31241582/rendering-very-large-html-file-in-browser

**Comment by dovisp** [comment]
Hello, there's another one :). I'll upload the logs, when I'll be back from school.

 ![Screenshot_20240517-124553_Snapchat.png](https://github.com/rhunk/SnapEnhance/assets/64722645/b1990ddd-9231-478e-a9ce-a400034fe984)

![Screenshot_20240517-124550_Snapchat.png](https://github.com/rhunk/SnapEnhance/assets/64722645/32a85258-a3ec-446a-9e39-b29554e3ef45)
