### ISSUE TITLE
bug: "Download Media" button inconsistent background with AMOLED dark mode

### ISSUE THREAD

**Issue by sn-o-w** [rhunk/SnapEnhance#183]
### Description

"Download Media" button looks weird if Snapchat's dark mode + SnapEnhance's AMOLED dark mode are enabled.

It should be either "Download Media" with the same background color as the rest of the options, or the rest of the options should have a black background as the current "Download Media" has.

### Reproduction steps

1. Enable dark mode within Snapchat
2. Enabled AMOLED dark mode within SnapEnhance
3. Try to download any story and notice the button

See the image: 
![photo_2023-08-07_04-18-36](https://github.com/rhunk/SnapEnhance/assets/2406819/23eb0dee-4ffc-4778-b4eb-56ecd300ae4f)

### Snapchat Version

12.45.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/58a13fe5be925e7d92526bc68683f0ded58c4126
