### ISSUE TITLE
bug: Downloading stories from Following section will not include username in the filenames

### ISSUE THREAD

**Issue by sn-o-w** [rhunk/SnapEnhance#184]
### Description

When I download media from the "Following" section, those media will not contain usernames, despite I selected to save the username in the filenames. Perhaps I will see the "display name" of those Snapchat users in filenames but not their usernames.

### Reproduction steps

1. Go to SnapEnhance, then select "Download Options"
2. Make sure to enable "Add the username to the file name"
3. Go to Snapchat, then go to your Following section
4. Select any Snapchat user you have in Following, then download any media you want
5. Notice the saved media will not include username in the filename (perhaps it would include the "display name", but no the username)

### Snapchat Version

12.45.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by JaKrIvMa** [comment]
Not only that but every image or video saves in each separate folder within username.

**Comment by melbarouzi** [comment]
> I just noticed that these stories are actually saved inside another folder called "Public Stories" which I don't like. 😞
> 
> I would rather have all stories inside the same folder, without another folder called "Public Stories".
> 
> Please give us an option to not save these media inside another folder like "Public Stories".

Go to snapenhance Settings > downloader > path Fomat then untick options you didnt like/want
