### ISSUE TITLE
feat: Force WEBP images to be saved as JPG

### ISSUE THREAD

**Issue by sn-o-w** [rhunk/SnapEnhance#185]
### Description

Add a feature to force images/pictures to be saved as JPG because sometimes they are saved as WEBP.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by alwakir** [comment]
Thank you all

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/b004f92b9cd9751fa0f22403b8b07ae426cd58cd

**Comment by alwakir** [comment]
Thank you
