### ISSUE TITLE
feat: More useful information about your Snapchat friends

### ISSUE THREAD

**Issue by sn-o-w** [rhunk/SnapEnhance#186]
### Description

It would be nice to let us see friend information on user profiles.

Info like:
```
Friends since <DATE> (this info exists by default)
User's birthday
Friendship status: MUTUAL/OUTGOING/FOLLOWING
Added by: ADDED_BY_QR_CODE/ADDED_BY_SUGGESTED/ADDED_FROM_PUBLIC_PROFILE, etc.
```

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/a341801be37427ff60e663b2d20ed10c91a50b32
