### ISSUE TITLE
bug: Amoled dark mode glitch

### ISSUE THREAD

**Issue by NotApex** [rhunk/SnapEnhance#187]
### Description

When switching accounts with amoled dark mode the chat menu is glitched

### Reproduction steps

1. Sype right to go to the  `chat menu`
2. Click on `cog in the top right`
4. Scroll down to `the amoled dark mode setting`
5. `enable it`
6. enable dark mode
7. log out
8. log back in
9. Sype right
10. See error.

### Snapchat Version

12.44.0.59

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [x] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by Ridayjrz800** [comment]
Dark theme
