### ISSUE TITLE
feat: save audio notes as mp3/opus

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#190]
### Description

Right now saved audio notes from the chat get saved as mp4 file.
I think it would be better when the saved file had an actual audio format 

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/89a155227794b987bb91abd003c33db9d9a50161
