### ISSUE TITLE
feat: manually set a value for "force highest framrate"

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#195]
### Description

Some options to choose from would be nice (like force 60,90,120 fps)
Right now the option force highest framerate causes some autofocus and lighting issues for me.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/a5ed05e41501dc1c1bb3f8c3d04cf80d95b8341c
