### ISSUE TITLE
bug: multi snap 

### ISSUE THREAD

**Issue by SFSN0** [rhunk/SnapEnhance#198]
### Description

Hello I have a problem when I take ( multi snap ) and send them to a friend They appear as just one photo not multiple photos

### Reproduction steps

1. Go to ...
2. Click on ...
3. Scroll down to ...

### Snapchat Version

12.46.0.51 

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by B1GPOLARB3AR** [comment]
I'm stuck too

**Comment by rhunk** [comment]
with "Disable Snap Splitting" turned off, it works as expected
