### ISSUE TITLE
Cant send multiple photos in gallery at once with send external gallery as snap

### ISSUE THREAD

**Issue by Siendra** [rhunk/SnapEnhance#20]
### Description

when i opened the gallery in snapchat and want to send multiple gallery photos at least 2+ at once (send external media as snap function checked) it gives me an error that sending failed.

### Reproduction steps

```bash
1. Make sure external media as snap feature is enabled
2. Go to camera
3. Click on gallery
4. sellect 2+ photos or videos 
5. press send and send it to people
6. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Snapchat Version

12.35.0.45

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [ ] There is no issue already describing my problem.

**Comment by Siendra** [comment]
can you solve this bug

**Comment by authorisation** [comment]
😒

**Comment by authorisation** [comment]
Currently, the functionality only allows for sending a single gallery item. While there is a possibility of adding a feature to support multiple gallery uploads, I cannot guarantee its implementation.
