### ISSUE TITLE
bug: voice notes download error

### ISSUE THREAD

**Issue by MAZZEOUS** [rhunk/SnapEnhance#200]
### Description

For the first time ever I needed to download a voice note and when held on it to download I got this error (unknown media type) screenshot attached.. 
![Screenshot_20230813-133234_Snapchat](https://github.com/rhunk/SnapEnhance/assets/135961492/6704db5b-e697-4201-9f97-b4f09a9390f4)

### Reproduction steps

1. Go to snap chat app
2. Open conversation
3. Click and hold voice note to get download media option
4. Click on download
5. Error msg

### Snapchat Version

12.46.0.51 

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by MAZZEOUS** [comment]
[Logcat file](https://files.fm/u/92q7qvpy9)

**Comment by rhunk** [comment]
@MAZZEOUS I can't figure out where you sent the message from
Can you send a video of how you sent it to reproduce the bug?

**Comment by MAZZEOUS** [comment]
@rhunk what do you mean by where I sent the message from? I originally posted a pic on my Snapchat story and got a very funny comment about it as a voice message/note . All I'm trying to do is download it. The above attached picture is this person's reply. It is saved in the chat between me and him but I want to download it. Hope this is clear and/or makes sense.

**Comment by MAZZEOUS** [comment]
https://streamable.com/yzzdd0

Hope this screen recording helps

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/5776d4411103691e0f09a2e902cb6e0591a8ccb5
