### ISSUE TITLE
bug: Applock dosen't allow recording voice messages.

### ISSUE THREAD

**Issue by TheVisual** [rhunk/SnapEnhance#201]
### Description

Applock dosen't allow recording voice messages it just loops you to keep inputting password.

### Reproduction steps

1. Enable Applock
2. Set password Example 0000
3. Restart app to enable
4. Type Password
5. Go to someone chat try to voice message

### Logs

```markdown
None as it doesn't really throw any.
```

### Snapchat Version

12.46.0.51

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by RSR1337** [comment]
You're so annoying, stop spamming, scammer

**Comment by rhunk** [comment]
AppLock is experimental and will likely be removed in future versions
