### ISSUE TITLE
a question:

### ISSUE THREAD

**Issue by SFSN0** [rhunk/SnapEnhance#202]
### Description

![Screenshot_20230814_123639](https://github.com/rhunk/SnapEnhance/assets/142000950/652fbc59-7d3e-4b2b-ac4a-0a0fc2e41716)
 Why on Android devices when posting a snap to the public story the quality decreases is not the same as posting to the private story of friends

### Agreement

- [ ] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
It seems that Snapchat compresses public media, on their servers and not from the application itself, because of their lifespan
