### ISSUE TITLE
bug: dark mode is glitching 

### ISSUE THREAD

**Issue by Venom1XD** [rhunk/SnapEnhance#203]
### Description

When i turn the dark mode on it doesn't change it to dark and the app keeps on crashing everytime i go to appearance settings 

### Reproduction steps

1. Go to ...
2. Click on ...
3. Scroll down to ...

### Snapchat Version

12.46.0.51 and 12.45.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Since v12.46.0.51, dark mode has been officially released. 
If it happens again, try clearing the cache from the 3 dots menu
