### ISSUE TITLE
bug: Messages disappears when sent

### ISSUE THREAD

**Issue by N1sh4ntK** [rhunk/SnapEnhance#206]
### Description

The messages are not getting sent. They disappear when tapped 'send' and which reach after 20-30 mins. My internet is perfectly fine. The messages don't even show 'sending' or 'network problem'.
Video showing the issue: https://photos.app.goo.gl/S8JQ1fjqSkJNwX7G7

### Reproduction steps

1. Open any dm
2. Type and send any message
3. The message disappears
4. Video showing the issue: https://photos.app.goo.gl/S8JQ1fjqSkJNwX7G7

### Snapchat Version

12.47.1.0

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by RSR1337** [comment]
+

**Comment by rhunk** [comment]
I can't really solve this problem without logs, but you can clean the cache from the three-dot menu, which solves almost all Snapchat problems caused by SE

**Comment by rhunk** [comment]
It seems to be a bug in beta versions of sc

**Comment by N1sh4ntK** [comment]
I'm on the regular version.
