### ISSUE TITLE
bug: Failed to init feature InfiniteStoryBoost

### ISSUE THREAD

**Issue by blikje7up** [rhunk/SnapEnhance#211]
### Description

When launching app message shows at the bottom of the screen: Failed to init feature InfiniteStoryBoost

Feature is disabled in settings, happened after installing for the first time

### Reproduction steps

1. Installed armv8 version Android 13
2. Launched Snapchat
3. Error pops up in bottom of the screen

### Snapchat Version

12.48.0.66

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by TheVisual** [comment]
Story boost is fixed in bleeding edge builds aka debug -> https://github.com/rhunk/SnapEnhance/actions/runs/5888264959
