### ISSUE TITLE
bug: the thumbnails for the stories doesn't load

### ISSUE THREAD

**Issue by BrilliantlyEducated** [rhunk/SnapEnhance#216]
### Description

if i disallow the permission for the Camera the thumbnails of the stories won't load up

### Reproduction steps

.

### Snapchat Version

any version

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Can't reproduce
