### ISSUE TITLE
bug: crashing when exiting the app and opening 

### ISSUE THREAD

**Issue by Y0SH1zzzz** [rhunk/SnapEnhance#217]
### Description

So I have followed the steps, using the tested version but when I first start it works but exiting the app and then trying to open it again will just crash it even with no settings enabled

I have an xiaomi running android 11 with miui 12.5.9

### Reproduction steps

1. Open snapchat, let it map
2. Exit the app completely 
3. Try opening again and it will crash

### Logs

```markdown
Where are they located?
```

### Snapchat Version

12.48.0.66

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by TheVisual** [comment]
Logs are in the lsposed verbose / module logs area in the lssposed app 🤗

**Comment by RSR1337** [comment]
> ### Description
> So I have followed the steps, using the tested version but when I first start it works but exiting the app and then trying to open it again will just crash it even with no settings enabled
> 
> I have an xiaomi running android 11 with miui 12.5.9
> 
> ### Reproduction steps
> 1. Open snapchat, let it map
> 2. Exit the app completely
> 3. Try opening again and it will crash
> 
> ### Logs
> ```
> Where are they located?
> ```
> 
> ### Snapchat Version
> 12.48.0.66
> 
> ### Agreement
> * [x]  I am using the latest stable SnapEnhance version.
> * [x]  This is not a bug regarding Snapchat+.
> * [x]  I have provided a detailed description of the issue.
> * [x]  I have attached a log if deemed neccessary.
> * [x]  This issue is not a duplicate.

The latest one in action is completely broken, Use the stable version

**Comment by Y0SH1zzzz** [comment]
I have no idea what I did different but apparently seems to work for now totally randomly after over 20 tries. Changed nothing tho so I'm lost

**Comment by TheVisual** [comment]
> > ### Description
> > So I have followed the steps, using the tested version but when I first start it works but exiting the app and then trying to open it again will just crash it even with no settings enabled
> > I have an xiaomi running android 11 with miui 12.5.9
> > ### Reproduction steps
> > 
> > 1. Open snapchat, let it map
> > 2. Exit the app completely
> > 3. Try opening again and it will crash
> > 
> > ### Logs
> > ```
> > Where are they located?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Snapchat Version
> > 12.48.0.66
> > ### Agreement
> > 
> > * [x]   I am using the latest stable SnapEnhance version.
> > * [x]   This is not a bug regarding Snapchat+.
> > * [x]   I have provided a detailed description of the issue.
> > * [x]   I have attached a log if deemed neccessary.
> > * [x]   This issue is not a duplicate.
> 
> The latest one in action #349 is completely broken, Use the stable version

1 no it isn't 2
![image](https://github.com/rhunk/SnapEnhance/assets/132447890/445ff5d0-5310-4c3e-8fef-14a19cbbc025)

He already checked hes using latest lol.

**Comment by RSR1337** [comment]
> > > ### Description
> > > So I have followed the steps, using the tested version but when I first start it works but exiting the app and then trying to open it again will just crash it even with no settings enabled
> > > I have an xiaomi running android 11 with miui 12.5.9
> > > ### Reproduction steps
> > > 
> > > 1. Open snapchat, let it map
> > > 2. Exit the app completely
> > > 3. Try opening again and it will crash
> > > 
> > > ### Logs
> > > ```
> > > Where are they located?
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### Snapchat Version
> > > 12.48.0.66
> > > ### Agreement
> > > 
> > > * [x]    I am using the latest stable SnapEnhance version.
> > > * [x]    This is not a bug regarding Snapchat+.
> > > * [x]    I have provided a detailed description of the issue.
> > > * [x]    I have attached a log if deemed neccessary.
> > > * [x]    This issue is not a duplicate.
> > 
> > 
> > The latest one in action #349 is completely broken, Use the stable version
> 
> For one no it isn't i'm using it and two he already said hes using the LATEST stop spamming offtopic.
> 
> ![image](https://user-images.githubusercontent.com/132447890/262808098-445ff5d0-5310-4c3e-8fef-14a19cbbc025.png)
> 
> He already checked hes using latest lol.

Spamming!!? , fix ur shit or delete it , no one will use  broken things

**Comment by Y0SH1zzzz** [comment]
It's working for now so I'll close it, if it stops working I'll just get rid of it. Thanks for trying to help tho
