### ISSUE TITLE
feat: Stop auto-save messages when chat not open

### ISSUE THREAD

**Issue by Kayetic** [rhunk/SnapEnhance#224]
### Description

It's weird for a message to be saved in chat (by the SnapEnhance user) when the chat hasn't even been opened by them (or has been half-swiped)

The auto-save messages feature should only be active when the SnapEnhance user is present on the chat to make it 'realistic'.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/3656024c986c76b7ab26c19e4f515ff1c70ea167
