### ISSUE TITLE
bug: Crash when starting snapchat

### ISSUE THREAD

**Issue by MaloFauchet** [rhunk/SnapEnhance#227]
### Description

Hello,
I use SnapEnhance on a non-rooted device, so I use LSPatch.
I've had this bug since the installation of SnapEnhance. When it is the first time I start snapchat (or when I opened another app before), Snapchat crashes either right before the main menu appears, or right after. It does it one or two times, then I can use the app normaly.
However, if I open another app after, the crashes occure again.

(+ The app became a bit slow but it might be because of my "old" phone, an Honor 8X running on android 10.0)

### Reproduction steps

1. Open the app
2. See it crashes
3. Do it again
4. See it doesn't crashes

### Logs

```markdown
When going on the logs section in LSPatch, it is written : "This page is not yet implemented". What should I do ?
```

### Snapchat Version

12.48.1.0

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by Domiiniik** [comment]
Can confirm this issue, it randomly starts happening to me as well until I clear mappings and then its fixed for some time (Android 13 Samsung Galaxy s21fe)
Installed the same as you, using LSPatch as well as i don't have root either.

**Comment by MaloFauchet** [comment]
> I clear mappings

Hey, thanks for the reply
How are you doing this ?

**Comment by Domiiniik** [comment]
Open SnapEnhance settings and you Will find "clear mappings" there

**Comment by MaloFauchet** [comment]
Tried to clear the mappings, snapchat launched, a textbox appeared saying "generating mappings", and then crashed. Did it again, and it did not crash. Not sure about what's happening

**Comment by Domiiniik** [comment]
Yeah, it seems random.

**Comment by MaloFauchet** [comment]
When going on the logs section in LSPatch, it is written : "This page is not yet implemented". What should I do ? Is there another way to get the logs ?

**Comment by MaloFauchet** [comment]
So I made a logcat using developpers options in android where should I send it, I don't want to send it here where everyone can see it

**Comment by Roki100** [comment]
hello, my snap seems to crash when i use the web version, when i close the web version the mobile app stops crashing

**Comment by MaloFauchet** [comment]
Sorry for the late reply. I can't send pm to an admin since we need to be mutual friends

**Comment by TheSirTigerr** [comment]
Hey what is the Fix?

I have the same Problem.

**Comment by TechLionDev** [comment]
Any Solutions?

**Comment by TechLionDev** [comment]
so far i have to clear config file so that it launches

**Comment by MaloFauchet** [comment]
I wasn't able to find any sort of logs. I just gave up and i'm using normal snapchat now.
If you can provide a log of the crash, it'll maybe help them.

**Comment by TechLionDev** [comment]
where would i find the log?

**Comment by MaloFauchet** [comment]
Maybe in the logs section in LSPatch ? I can't help you much sorry

**Comment by TechLionDev** [comment]
ok, i think its one specific mod that causes th eissue
so il ltest one by one and report back when i figure it out
also looking through code inconsistencies

**Comment by TechLionDev** [comment]
tysm tho

**Comment by MaloFauchet** [comment]
No problem !

**Comment by TechLionDev** [comment]
ok its the startup page, and app appearance so far

**Comment by TechLionDev** [comment]
those are broken on non-rooted

**Comment by TechLionDev** [comment]
you can do startup page with th eplus spoof

**Comment by TechLionDev** [comment]
And GOOGLE PLAY SERVICES is SUPER imporant do not disable

**Comment by MaloFauchet** [comment]
Thank you, that'll help people !

### So for now, here are the problems :
- Startup page
- App Appearance
- Google Play Services MUST be enabled

Thank you a lot TechLionDev
