### ISSUE TITLE
bug: Filters do not apply to face

### ISSUE THREAD

**Issue by ibigrock-ashish** [rhunk/SnapEnhance#231]
### Description

When ever i change filter on snapchat, the filter is applied on the whole image but it is not detecting face and applying effect on face. 

### Reproduction steps

1. Go to Snapchat
2. Click on any filter with face effects
3. See that effect is not applied on the face.

### Snapchat Version

12.48.1.0

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by EasyKey5** [comment]
I found that turning off the “disable metrics” toggle and restarting fixes this issue for now

**Comment by Theonethom** [comment]
> I found that turning off the “disable metrics” toggle and restarting fixes this issue for now

Mine does it but never had that option toggled on

**Comment by ibigrock-ashish** [comment]
I tried disabling all the toggles and restarted, I even tried multiple combinations of toggles. I am still facing the same issue. I got so frustrated that for now I have switched to Original app from playstore.

**Comment by Domiiniik** [comment]
Happens for me as well

**Comment by Murtezah** [comment]
Im using LSpatch method as my device not rooted, i just did reinstalled snapchat enhance and patched the apk file again and it was fixed for me.

**Comment by TheVisual** [comment]
this is happening for me to recently

**Comment by RSR1337** [comment]
same here

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/8fd72d60dfb4b188e0ac12bcf2d0cb0cba11ecda
