### ISSUE TITLE
feat: Bundled Notifications

### ISSUE THREAD

**Issue by lalettan-fan** [rhunk/SnapEnhance#235]
### Description

Notifications from Snapchat is filling up the notification panel. It will be nice if you could combine all the notifications into a single Bundled notification like WhatsApp or telegram.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/7c5195e83cc981197fe5f0c59cd74c4a636d8022
