### ISSUE TITLE
feat: 2D bitmoji back

### ISSUE THREAD

**Issue by Radical4ever** [rhunk/SnapEnhance#237]
### Description

Hi, so the feature is pretty self explanatory, an option to get back the 2d bitmojis for the whole snapchat, because 3d ones are kinda ugly

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/3ba4e573adf9e775816b9b115fd966f5a1ff6377
