### ISSUE TITLE
feat: Option to don't Autosave snaps from a group thread

### ISSUE THREAD

**Issue by MnkyMth** [rhunk/SnapEnhance#248]
### Description

The choice to auto download group snaps or opt out. 
With download option: "add group name into file name" and group name folder. 

Hopefully this doesn't affect personal one on one chats from individuals who might be in the same group.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by ReSo7200** [comment]
Hi, in version 2 you would be able to enable "auto download, stealth mode, auto save" for specific chats and/or groups.

**Comment by MnkyMth** [comment]
Already beating me to it lol.
