### ISSUE TITLE
feat: "now-listening" filter, similiar as in SnapTools

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#251]
### Description

Back when SnapTools had its peak, there was a "now-listening" filter, which took the song you're listening to right now, and put it into a swipeable filter. 
See my screenshot for reference. 
![Snapchat-1815388012](https://github.com/rhunk/SnapEnhance/assets/12681440/7a5ece01-3104-4a68-acfd-4d3fe0719e8b)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Unfortunately, snaptools is made for a very old version of snapchat and so I can't reproduce based on the public source code
