### ISSUE TITLE
bug: unable to turn off snap map location mock

### ISSUE THREAD

**Issue by SirenGlitch** [rhunk/SnapEnhance#257]
### Description

I turn on the Snap Map location mock, and cannot find a way to stop mocking. Turning off "Snapmap Location Spoofer" in SnapEnhance settings doesn't work, and there is no obvious setting to do so.

### Reproduction steps

1. Go to SnapEnhance settings
2. Turn on "Snapmap Location Spoofing"
3. Set a location
4. Try and stop spoofing.

### Snapchat Version

12.52.0.47

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
You need to force close snapchat for this to work
