### ISSUE TITLE
bug: - Preview option can't display emojis

### ISSUE THREAD

**Issue by RevealedSoulEven** [rhunk/SnapEnhance#26]
### Description

The preview option can't display emojis instead it shows question marks and invalid symbols. Maybe it's due to the encoding issue in the code. Please try to fix it. I'm sure you need to add UTF-8 related something.

### Reproduction steps

```bash
.....
```

### Screenshots

```bash
Why shall I give me gf's chat screenshot 😭
```

### Logs

```bash
Bla bla bla
```

### Snapchat Version

12.36.0.53

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by authorisation** [comment]
Cannot reproduce, provide more info
