### ISSUE TITLE
bug: override startup page breaks "draft snaps"

### ISSUE THREAD

**Issue by D3SOX** [rhunk/SnapEnhance#262]
### Description

When I set override startup page to chat it breaks the functionality of the app to take a snap reopen the app and then send it later

### Reproduction steps

1. Set override startup page to Chats
2. Take a snap
3. Go to home screen
4. Open Snapchat again
5. Chat page is opened instead of the "draft snap"
6. Compare it to the behavior when it's turned off

### Logs

Not relevant

### Snapchat Version

12.51.0.62

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Startup tab is now a sc + feature (at least beta), so it will be removed in v2.0.0
