### ISSUE TITLE
bug: Unable to download multiple snaps within a chat. 

### ISSUE THREAD

**Issue by Lucky-069** [rhunk/SnapEnhance#263]
### Description

When attempting to download multiple snaps within a chat received by a user, a problem arises. The issue is that only the first snap successfully downloads, and subsequent attempts to download any additional snaps within the same chat fail. This means that users are currently unable to download any snap other than the first one in the chat, which is causing a limitation in snap retrieval functionality.

### Reproduction steps

1. Open the Snap Enhance app on your device.

2. Navigate to the chat or conversation where you have received multiple snaps or where multiple snaps are saved.

3. Tap on the first image or video you want to enhance within the chat.

4. Once the first image or video is downloaded, proceed to tap on the second or third snap for enhancement, or you can manually download the snaps within the chat.

5. You may encounter a popup message indicating "Media already downloaded" for snaps that have already been saved.

### Snapchat Version

12.51.0.62

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/904d9175b69b20156d6f083a4d389149655ab908

**Comment by Lucky-069** [comment]
Thank you for the fix. Waiting for CI build. Will try!
