### ISSUE TITLE
feat: Add marker next to deleted logged messages

### ISSUE THREAD

**Issue by TFManship** [rhunk/SnapEnhance#264]
### Description

As the title says, adding a marker (e.g. a small yellow circle to the right of the message) to deleted messages would make it more clear as to which messages a friend has deleted.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by Blake-m05** [comment]
I absolutely love this idea. I accidentally deleted a message because I thought they deleted it. Having an icon, Or even some message loggers I use turn the text another colour, would be a great addition to this already amazing app.

**Comment by aikooo7** [comment]
That is actually a perfect idea, that I would use a lot, if the current contributors let me I would do it.

@rhunk

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/fc838fed7ab0b889d92e5d9b43863319df973fec
