### ISSUE TITLE
bug: anon story viewing not working 

### ISSUE THREAD

**Issue by neos909** [rhunk/SnapEnhance#271]
### Description

when I finish watching someone's story, their bubble is greyed out with a replay icon on it. indicating that I did watch their story.

### Reproduction steps

settings I have enabled:
•prevent read receipts
•unlimited snap view time
•anonymous story view
•gallery media send override 
•show streak expiration info
•snapmap location spoofer
using LSposed

### Snapchat Version

12.51.0.62

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
The story has been viewed on your phone but your friends won't see it

**Comment by neos909** [comment]
have been using many snapchat modules like Casper, snaptools, snapmod throughout the years. this the first one to include that but I trust you. will make a burner account to see if true. will report back with results
