### ISSUE TITLE
bug: Snapchat Plus not working after 1.2.3 update

### ISSUE THREAD

**Issue by sheeepdev** [rhunk/SnapEnhance#273]
### Description

Updating from 1.2.2 to 1.2.3 caused the "Enable snapchat plus" feature to stop working. I tried enabling and disabling it but nothing worked

### Reproduction steps

1. Update to 1.2.3
2. Check if snapchat plus is enabled in SnapEnhance settings (it is)
3. Check snapchat plus status
4. See that you dont have snapchat plus
 

### Snapchat Version

12.51.0.62

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by sheeepdev** [comment]
Note: This is not an issue about Snapchat+, but rather the setting not working (not giving you the status of Snapchat+ subscriber)

**Comment by sheeepdev** [comment]
Refreshing mappings did it, thanks

**Comment by cookedfnm** [comment]
how do we refresh mappings?

**Comment by sheeepdev** [comment]
> how do we refresh mappings?

Open SnapEnhance app ➞ Click on the bug icon ➞ Click on "Clear Mappings file"
