### ISSUE TITLE
App fully closes once I go off it

### ISSUE THREAD

**Issue by Dom513** [rhunk/SnapEnhance#276]
### Description

The app will reload from scratch when I reopen it so it must have completely closed. When I'm on calls and leave the app, it ends immediately and the app shuts down. Wastes a few seconds of loading time when opening the app every time.

I recently removed the mod and this was not an issue on standard Snapchat 

### Reproduction steps

Will either be an issue or not, if the yellow background and large Snapchat icon show on startup every time then that's the same issue

### Snapchat Version

12.51.0.62

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://dontkillmyapp.com/
