### ISSUE TITLE
feat: - Media download options should have Snap/Story display

### ISSUE THREAD

**Issue by RevealedSoulEven** [rhunk/SnapEnhance#28]
### Description

There should be an option to display in the file name whether it was a story or a snap.

![Screenshot_2023-06-05-07-09-16-692_com snapchat android](https://github.com/rhunk/SnapEnhance/assets/49313374/0e06d200-ed74-476c-8d5c-72497149a592)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
Thanks for this suggestion, this will (most likely) be worked on soon.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/c8bfd14c3f9581b2098f620592b2498d3a5c21d0
