### ISSUE TITLE
bug: pinning does not work

### ISSUE THREAD

**Issue by BulletZ4Break2A** [rhunk/SnapEnhance#280]
### Description

i beg you fix this soon. whenever i try to pin somebody, it doesnt work. i click on it and nothing happens

**Comment by rhunk** [comment]
@BulletZ4Break2A Can you try to pin and then refresh the friends feed?

**Comment by melbarouzi** [comment]
> ### Description
> i beg you fix this soon. whenever i try to pin somebody, it doesnt work. i click on it and nothing happens

Do use pin friend from
Snapchat plus menu or u long press the name because in snapchat plus menu it will show you a fail message

**Comment by BulletZ4Break2A** [comment]
my mistake. it works. what i was doing is justvlong pressing on the name and choosing "pin as #1 bff" (thats the option that didn't work).
today i realized that if i long press the name, go to chat settings, i could now pin the conversation and thats what worked.
