### ISSUE TITLE
Bug: Sign up error

### ISSUE THREAD

**Issue by EmanuelQeryo** [rhunk/SnapEnhance#281]
### Description

Whenever I try to login to my account it says my account Is disabled for failed sign in attempts but account works on the normal version

![Screenshot_20230925_071333_Snapchat](https://github.com/rhunk/SnapEnhance/assets/112962571/ce1403bf-44cf-4cb1-850e-39dee0de3dc6)

### Reproduction steps

1. Go to the sign in menu
2. Enter login details
3. Click on login

### Snapchat Version

12.52-12.54beta

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by Zeek2003** [comment]
Having this same issue trying to login on version 12.51.0.62
