### ISSUE TITLE
bug: Snap Turning Black after Clicking 

### ISSUE THREAD

**Issue by Arshad-sys-max** [rhunk/SnapEnhance#285]
### Description

i was clicking a selfie and all of a sudden, after clicking it, the snap went black, i discarded the snap, tried many more times but it keeps happening the same, after clicking, the snap turns black and if i send it to someone, it appears a black snap to them, please fix this, it is happening 99% of the times from todayy 

### Reproduction steps

1. Go to camera
2. Click a picture of anything
3. see the error, the snap turning black

### Snapchat Version

12.48.1.0

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
This might be fixed in v2.0.0 but you can still clean the Snapchat cache from the three-dot menu.
