### ISSUE TITLE
bug: Snapchat chats not loading when opening notification 

### ISSUE THREAD

**Issue by xahem** [rhunk/SnapEnhance#287]
### Description

When I get a chat notification, I press on it to open Snapchat. Most of the times the chat wouldn't be loaded, it would just be the black screen without the texts. I have to close Snapchat a few times and open it for them to load

### Reproduction steps

1. Get a chat notification
2. Open the notification and check

### Snapchat Version

12.51.0.62

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by Rainerr123** [comment]
I also have this issue

**Comment by rhunk** [comment]
Hey, could you all test the v2.0.0 build [here](https://github.com/rhunk/SnapEnhance/actions/runs/6475180354) and tell me whether the bug is still there?

**Comment by xahem** [comment]
I just tested the new version. The issue is the same, but in this version rather than chat just not loading when the issue happens, the app crashes a few seconds later.
