### ISSUE TITLE
bug: - My Eyes bypass sucks

### ISSUE THREAD

**Issue by RevealedSoulEven** [rhunk/SnapEnhance#29]
### Description

Actually if you try that hack again, with a fresh account or by clearing snapchat data, it won't work.

It needs you to enter the My Eyes code once and after that it will bypass. Until and unless you don't put the correct code ONCE, it won't work.

### Reproduction steps

```bash
Bla bla bla
```

### Logs

```bash
.....
```

### Snapchat Version

12.36.0.53

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by authorisation** [comment]
This is intended and cannot be changed
