### ISSUE TITLE
feat: No Notification Re-play snap

### ISSUE THREAD

**Issue by yesitskiko** [rhunk/SnapEnhance#299]
### Description

I know there are features to disable sending the notification for screenshot and saved-to-camera, but would it be possible to implement this for replaying snaps?

Love your work m8!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/1a40856ae74db91023f27cb23bc064413e74fa39

**Comment by khush-img** [comment]
> Added in [1a40856](https://github.com/rhunk/SnapEnhance/commit/1a40856ae74db91023f27cb23bc064413e74fa39)

I can't see it in settings? I want to hide replay chat message from friend I'm chatting to

**Comment by rhunk** [comment]
@khush-img go in settings > Messaging > Prevent message sending > turn on Snap Replay

**Comment by yesitskiko** [comment]
There is no option for snap replay in 1.2.5

sön 26 nov. 2023 kl. 12:05 skrev rhunk ***@***.***>:

**Comment by rhunk** [comment]
@yesitskiko use v2.0.0

**Comment by yesitskiko** [comment]
There is no V2. The latest is 1.2.5

mån 27 nov. 2023 kl. 00:05 skrev rhunk ***@***.***>:
