### ISSUE TITLE
Mapping is not working

### ISSUE THREAD

**Issue by JeetParab** [rhunk/SnapEnhance#3]
I'm on Latest snapchat version - 12.34.0.36
Device Details - Sweet on Android 13
Here are the logs - https://katb.in/uqetotipoto

**Comment by Tenclea** [comment]
Well the [last release](https://github.com/rhunk/SnapEnhance/releases)  specifically states to use v12.33.1.19, so it makes sense that you run into problems with 12.34.0.36
@rhunk also stated not to use the Google Play version nor a bundled file, so also make sure to comply with these requirements before submitting an issue
