### ISSUE TITLE
feat: - Export Chat .txt or .json

### ISSUE THREAD

**Issue by RevealedSoulEven** [rhunk/SnapEnhance#30]
### Description

Why not an option to export chat?
Also in my repository you can see Snapmod-new which has export feature.

Adding to this, if you're going to work for it please consider that it first loads a chat to the top completely and then exports it to .txt because it only exports the data available in the local database and not the complete chat. Also please add option to export as a zip file where it would contain all the saved images, videos and snaps in chat too. 

Additionally, please add an option whether [stickers/voicenotes/images/videos/snaps] to be added in export or not?

One good way to do this is. (if the user choses txt go with only exporting the chat messages) 
But if the user choses complete export, it should create a zip file and should ask whether to consider sticker/snaps and all and it should create separate folders for stickers/images/videos and when these photos/videos occur in chat, it shows filename. For example:

`SoulEven : hi see this pic.
Me : wait send me
SoulEven : [image | jdjskcjrhr.jpg]
SoulEven: [sticker | djjdishfhd.png]
Me : Wow`

This is what I'm talking about.

Further on when  I'll be free I'll write an html code for this where it will parse the exported zip and show it in a UI and more precise format so that we can see thise exported chats on any browser app. (Why not using that shitty chatgpt for this?)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
This is actively being worked on as seen here. https://github.com/rhunk/SnapEnhance/pull/17

**Comment by RevealedSoulEven** [comment]
Are you adding exporting snaps/images/videos support too?

**Comment by authorisation** [comment]
It's in a very early stage so I can't give any info on that yet
