### ISSUE TITLE
bug: Snapchat Crashing

### ISSUE THREAD

**Issue by TheSirTigerr** [rhunk/SnapEnhance#301]
### Description

Hello,

My Snapchat crashes on Startup, then I try restarting it and it works.

I use the Hotfix of SnapEnhance.

Can someone please help me??

### Reproduction steps

1. Start Snapchat
2. Crashes
3. Restart Snapchat
4. Works

### Snapchat Version

12.52.0.60

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by rhunk** [comment]
Restart your device or clear Snapchat app data
