### ISSUE TITLE
can't save stories or snaps

### ISSUE THREAD

**Issue by missmiaaa** [rhunk/SnapEnhance#302]
### Description

I'm facing this issue i tried to clear cache and deleted the app but still not working 

### Reproduction steps

saving any pics or videos 
![Screenshot_20231004_053703_Snapchat](https://github.com/rhunk/SnapEnhance/assets/146905165/8a7aa45a-7584-4295-b52d-8ad93d73c485)

### Logs

```markdown
Failed to save to gallery
java.lang.NullPointerException
```

### Snapchat Version

12.53.0.46

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Change the save folder and force stop the app
