### ISSUE TITLE
feat: Option to disable the annoying snapstreak has ended in chats

### ISSUE THREAD

**Issue by cjcj233** [rhunk/SnapEnhance#309]
### Description

In chats when streaks end it now has a nice big annoying bit of text that takes over my chat so I cannot read if someone has opened a snap. Terrible design from Snapchat and would think many would like that feature to be able to be toggled off completely from all parts of the UI. 

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/1d41aef8e058ca4dcc50e145efacd0edca5d2edb
