### ISSUE TITLE
feat: Download public profile pictures

### ISSUE THREAD

**Issue by sn-o-w** [rhunk/SnapEnhance#310]
### Description

Because why not?! 🤔 People you follow or your friends can set a profile picture that is currently not downloadable via SnapEnhance.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Already implemented https://github.com/rhunk/SnapEnhance/commit/d0668b67d4c64b2b70d5e9ae9c88af8161abe8e9
