### ISSUE TITLE
bug: Night sight on pixel doesn't work

### ISSUE THREAD

**Issue by nikhilpanchal1** [rhunk/SnapEnhance#311]
### Description

Night sight/low light mode doesn't work. When you click the icon it switches to ultra wide but photos aren't processed for the longer time so it gives no additional clarity 

### Reproduction steps

1. Go to main camera (snapchat) using a pixel 6 or above 
2. Click on moon icon (night sight)
3. Notice how it switches to ultra wide mode and doesn't really process any photos for extra time like it did 2 versions ago on 1.2.2

### Snapchat Version

Snapchat 12.54.0.67, snapenhance - latest release

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
@nikhilpanchal1 does the bug occur when SE is disabled?
Try resetting the config or use a beta version of Snapchat as they may apply patches early

**Comment by rhunk** [comment]
@nikhilpanchal1 does the bug occur when SE is disabled?
Try resetting the config or use a beta version of Snapchat as they may apply patches early

**Comment by nikhilpanchal1** [comment]
> @nikhilpanchal1 does the bug occur when SE is disabled? Try resetting the config or use a beta version of Snapchat as they may apply patches early

If SE is disabled, the bug does not occur. I tried resetting the config and using beta build of snapchat, didn't work.

**Comment by rhunk** [comment]
@nikhilpanchal1 you may try the latest beta ci build and see if it got fixed
