### ISSUE TITLE
Screenshot notification bypasser not working

### ISSUE THREAD

**Issue by Jlinkify** [rhunk/SnapEnhance#315]
### Description

The notification for screenshots bypasser feature is not showing up on my phone, i am using armv7 version and am fully updated, is there any fix?

### Reproduction steps

1. Go to chat
2. Click on snapenhance settings
3. Scroll down to where feature normally is
4. See nothing

### Snapchat Version

Latest

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Search for "Prevent Sending messages" and toggle "Screenshots"
