### ISSUE TITLE
bug: Some buttons missing depending on Snapchats version

### ISSUE THREAD

**Issue by TheJordanDev** [rhunk/SnapEnhance#316]
### Description

SnapEnhance Version: v1.2.4-hotfix
Snapchat Version with issues: >12.48.1.0 *I am not going higher than the tested version for each SnapEnhance versions*
I use LSPatch to install SnapEnhance

I have most of the features (Settings Gear, Image downloading, etc...) but when updating to a new version of Snapchat the "Friend Feed Buttons" do not appear. The SnapEnhance version does not seem to matter, the version that I have to use as of now to still have the buttons is Snapchat 12.48.1.0.

### Reproduction steps

1. Install the latest SnapEnhance with Snapchat 12.48.1.0
2. Go into SnapEnhance settings
3. Scroll down to "UI & Tweaks"
4. Enable buttons in "Friend Feed Menu Buttons"
5. Go to a friends profile, click on the three dots on the top right and you'll see the buttons you've enabled (see picture)
![image](https://github.com/rhunk/SnapEnhance/assets/55529456/28b3229b-c667-4263-98ce-6c3f1babb6c3)
*depending on if you've enabled the "Friend feed menu bar" you'll see the same options but differently

6. Uninstall Snapchat and make a new patch with a higher version (e.g: 12.54.0.67)
7. Check if the setting is still enabled *it is supposed to still be enabled*
8. Go to your friends profile and look for the options shown above.
9. Nothing appears.

### Snapchat Version

12.54.0.67

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
FF menu buttons have been removed in v2.0.0 because they were not explicit enough but you can always use the classic mode if you are having issues
