### ISSUE TITLE
bug: when receiving video snaps Text is not saved on video

### ISSUE THREAD

**Issue by bignonce69420** [rhunk/SnapEnhance#319]
### Description

When receiving a video the text on the snap is not saved to the video, and all that is saved is the video it's self

### Reproduction steps

1. Recive video with text
2. Download video
3. Playback video

### Snapchat Version

12.54.0.67

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Toggle merge overlay feature

**Comment by bignonce69420** [comment]
If you are talking about the setting under media manager/download option/ merge snap image overlays does not fix the issue.

**Comment by rhunk** [comment]
@bignonce69420 you might have chosen the wrong device architecture. If you're on a old device, try the armv7 build.

**Comment by bignonce69420** [comment]
Thank you for the response. Was using the v7 build on my Xiaomi mix fold 2 and changed to the v8 version and it fixed the issue
