### ISSUE TITLE
feat: split media sent from gallery

### ISSUE THREAD

**Issue by RevealedSoulEven** [rhunk/SnapEnhance#32]
### Description

As the title says. All videos from camera roll directly goes straight forward as a single video. 
(as you see in my repo, there they would split up in multiple files)

The problem is, when you send long videos in one go, people will understand you're doing some magic 😂

So please try making it such that it Splits those snaps

### Snapchat Version

12.36.0.53

### Agreement

- [X] There is no issue already suggesting this feature.

**Comment by TheVisual** [comment]
Disable snap splitting toggle it's there for a reason

**Comment by RevealedSoulEven** [comment]
But I don't need it to split. It's off still videos from gallery are sent in one go

**Comment by authorisation** [comment]
This is more of a feature request instead of an actual bug as the feature used here does exactly what it's supposed to but we will take your suggestion into consideration. Thanks!

**Comment by RevealedSoulEven** [comment]
Yaaa... Actually voice notes are being split. So make the voice notes not to be split because it doesn't happens in original snapchat too. Just the snaps from gallery should be split😅

**Comment by authorisation** [comment]
fixing #31 would fix this issue
