### ISSUE TITLE
feat: Disable "reacted to" notification

### ISSUE THREAD

**Issue by jollran2005** [rhunk/SnapEnhance#322]
### Description

Would be awesome to be able to disable notifications from when people react to a message. Especially in group chats, if 10 people react to a message I'll get 10 notifications. I still want to be able to see when someone reacts in a private dm. Would it be possible?

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/8f699e39020422f18a77dc6f0b0c9f373572a9a2
