### ISSUE TITLE
bug: latest notifications dont disappear

### ISSUE THREAD

**Issue by DenischoIBobo** [rhunk/SnapEnhance#324]
### Description

When i go to check my chats i notice that the latest notification on a group chat doesnt disappear, even if i enter and exit out of it, so it ends up constantly showing that i have unread texts

### Reproduction steps

1. Go to "chats" tab
2. Click on any chat
3. Exit out of said chat
4. See the "new snap from x / x replied to a chat / etc" alert next to the group chat name not disappear

### Snapchat Version

12.55.0.56

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Disable prevent read receipts
