### ISSUE TITLE
feat: Timed Chat Purge

### ISSUE THREAD

**Issue by DestinyWelthe** [rhunk/SnapEnhance#325]
### Description

Idk if this has been said but I was wondering if its possible to add chat purge to 1.2.4. I noticed there was one by thevisual but I don't think its been added into the features here.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/4b49d669b7ec8ee0599f621b64b3e8ad674a5dfe
