### ISSUE TITLE
bug: Language setting not working

### ISSUE THREAD

**Issue by XanderTheDev** [rhunk/SnapEnhance#327]
### Description

1.2.4 has a bug that you can't change your language. When you try to change the language in the settings of Snapchat, you get the error: "Something went wrong. Please try again later"

### Reproduction steps

1. Go to settings in Snapchat
2. Click on Language
3. Scroll down to the language you want
4. Select the language
5. Chance tot the language
6. See error: "Something went wrong. Please try again later"

### Logs

```markdown
Something went wrong. Please try again later
```

### Snapchat Version

12.54.0.67

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
This is not a bug. It's because you downloaded Snapchat from the Play Store. Try to use a version from apkmirror it should fix the issue.

**Comment by XanderTheDev** [comment]
> This is not a bug. It's because you downloaded Snapchat from the Play Store. Try to use a version from apkmirror it should fix the issue.

Nope. Installed it via aptoide.
