### ISSUE TITLE
feat: Hide Friends From Friends List

### ISSUE THREAD

**Issue by CKHSS375** [rhunk/SnapEnhance#328]
### Description

A feature that would allow us to manage friends from the in-app SnapEnhance settings. Where we can select a friend(s), and then toggle Hidden/Visible.
This would: 
- Remove them from the Conversation List, New Chat Selection, and the Friends List, without needing to block them, or remove them as a friend, ending any streaks or removing any messages.
- Still allow them to send messages/snaps, but they would not push notifications or show up on the conversation list until we toggle them back to "Visible".
- Then when we toggle them back to "Visible", the effect reverses.

Is this possible?

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/4a7c7d71bc6a7b66396899625661ac86c0543ee0
