### ISSUE TITLE
bug: Bug with unique hash

### ISSUE THREAD

**Issue by sn-o-w** [rhunk/SnapEnhance#329]
### Description

The saved media could have a name like "**_77cf2f4f_77cf2f4f_2023-10-12..._**" and the folder will be called "**_77cf2f4f_**".

So, the folder is somehow named as the unique hash, and the unique hash is twice in the saved media's file name.

Maybe it's related to some degree to the previous issue I reported: https://github.com/rhunk/SnapEnhance/issues/184 ?!

P.S.: This bug was discovered in SnapEnhance 2.0.

### Reproduction steps

1. Go to SnapEnhance, then select "Downloader"
2. Select "Path Format", then enable "Create folder for each author" + "Add a unique hash to the file name" + "Add the username to the file name" + "Add the date and time to the file name" (not sure if the last one I listed here is absolutely necessary, tbh)
3. Go to Snapchat, then go to your Following section
4. Select any Snapchat user you have in Following, then download any media you want

### Snapchat Version

12.54.0.67

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/0d3bffb05bc14af3dab21a05ad2795876e34dfc5
