### ISSUE TITLE
bug: "add reply button" feature neither working in 1.2.4 nor 2.0 

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#330]
### Description

When you reply to a chat within the notification and send the message, it acts like it sent the message to the recipient.
But the recipient never gets the message and when you open snapchat, the chat is still marked as unread.
This happens with 1.2.4 stable + latest 1.2.4 Ci build, and also with the lates 2.0 ci build.

### Reproduction steps

1. Enable "add reply button" feature
2. Send a message to the recipient with the reply button within the chat notification
3. Open snapchat
4. The recipients chat is still unread and no message has been sent

### Snapchat Version

12.55.0.56

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Got fixed already
v1 : https://github.com/rhunk/SnapEnhance/commit/f5cb0671d7e6944ebc4c3577d082e70bbc52975b
v2 : https://github.com/rhunk/SnapEnhance/commit/a38e96906dfdedaa334f2e0e0a0278a454797e64
