### ISSUE TITLE
bug: Snapchat still asks to update to 1.2.4 when Snapenhance is already updated to 1.2.4

### ISSUE THREAD

**Issue by WarFiN123** [rhunk/SnapEnhance#332]
### Description

As u must have read the title, I am not quite sure why this is there but the download and install feature too just downloads the apk and does not install it. 

### Reproduction steps

1. Open Snapchat
2. You will get the update message / go to the chats menu
3. Click on the hamburger icon top right
4. Click on check for updates 

### Snapchat Version

1.2.4

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
You need to repatch for each update if you use lspatch
