### ISSUE TITLE
bug: message crash

### ISSUE THREAD

**Issue by NotApex** [rhunk/SnapEnhance#333]
### Description

I'm using a Samsung galaxy A51 with non root

### Reproduction steps

1. Open Snapchat
2. swipe right
3. crash
Or
1. Go to SnapEnhance settings 
2. Enable Override Startup Page
3. Select chat
4. Restart snap
5. Crash

### Snapchat Version

12.54.0.67

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
This feature is deprecated and has been removed since v2.0.0, use the Snapchat + one instead
