### ISSUE TITLE
bug: Snapchat crashing & can't change chat wallpaper

### ISSUE THREAD

**Issue by Vollan06** [rhunk/SnapEnhance#334]
### Description

when i open Snapchat it crashes in few seconds & when i try to change the chat wallpaper it goes back to default (blank) when i leave the app and come back

### Reproduction steps

1. Go to ...
2. Click on ...
3. Scroll down to ...

### Snapchat Version

12.56.0.57

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Clean Snapchat cache if you're having repeated crashes

**Comment by Vollan06** [comment]
I did clear cache and it still kept crashing
