### ISSUE TITLE
bug: Hide From Friend Feed is only clearing the conversation

### ISSUE THREAD

**Issue by CKHSS375** [rhunk/SnapEnhance#335]
### Description

The new feature added in SnapEnhance 2.0.0 [4a7c7d7](https://github.com/rhunk/SnapEnhance/commit/4a7c7d71bc6a7b66396899625661ac86c0543ee0) is only clearing the conversation from the Chat Log. It is not removing the friend from the list of "My Friends" or disabling Message Notifications for that friend.

### Reproduction steps

1. Go to Social Tab of SnapEnhance 2.0.0
2. Click on desired friend to Hide
3. Toggle Hide from Friend Feed to ON
4. Go to Snapchat chat log
5. Pull down to refresh (Hidden friend disappears from chat log)
6. Go to My Friends in Snapchat
7. Still see the Friend that was selected to Hide
8. Long Press Friend Name
9. Press Chat Settings
10. See Message Notifications still toggled ON.

### Snapchat Version

12.54.0.67

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
I can't hide the friend from your friends list, only remove from the feed. Therefore notifications don't seem to appear for hidden friends.
