### ISSUE TITLE
bug: Infinite snap glitch/bug

### ISSUE THREAD

**Issue by pralinkhaira** [rhunk/SnapEnhance#346]
### Description

# Infinite Snaps

- Today I sent a snap (without audio, I mean the red one) to over 150 of my friends and then suddenly they started receiving tons of notifications, like 100 to 200 notifications and even tho the snap was still having notification of sending.
- The notification on my phone of `sending` was stuck on 0%
- All those friends who received tons of notifications have received only one snap but notifications were like flood
- Restarting/Rebooting the phone corrected the notification glitch on their side.
- In a hurry to avoid all this I cleared all the data of snapchat 😢 

### Reproduction steps

1. Go to ...
2. Click on ...
3. Scroll down to ...

I have no idea what happened, the steps include normal clicking the snap then sending it to other snapies!

### Logs

```markdown
There was nothing fishy in the logs.
```

### Snapchat Version

12.54.0.67

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by TheVisual** [comment]
@pralinkhaira send logcat please.

**Comment by pralinkhaira** [comment]
> @pralinkhaira send logcat please.

- I am sorry but after all this happened, i received a lot of chat saying stop sending soo many snaps :)
- So I just cleared data/cache and ultimately uninstalled the app!

**Comment by authorisation** [comment]
I doubt this is a thing but as this would be a severe issue I'll leave it open for now, perhaps it happens to someone else

**Comment by Vntonios** [comment]
> ### Description
> # Infinite Snaps
> * Today I sent a snap (without audio, I mean the red one) to over 150 of my friends and then suddenly they started receiving tons of notifications, like 100 to 200 notifications and even tho the snap was still having notification of sending.
> * The notification on my phone of `sending` was stuck on 0%
> * All those friends who received tons of notifications have received only one snap but notifications were like flood
> * Restarting/Rebooting the phone corrected the notification glitch on their side.
> * In a hurry to avoid all this I cleared all the data of snapchat 😢
> 
> ### Reproduction steps
> 1. Go to ...
> 2. Click on ...
> 3. Scroll down to ...
> 4. See error
> 
> I have no idea what happened, the steps include normal clicking the snap then sending it to other snapies!
> 
> ### Logs
> ```
> There was nothing fishy in the logs.
> ```
> 
> ### Snapchat Version
> 12.54.0.67
> 
> ### Agreement
> * [x]  I am using the latest stable SnapEnhance version.
> * [x]  This is not a bug regarding Snapchat+.
> * [x]  I have provided a detailed description of the issue.
> * [x]  I have attached a log if deemed neccessary.
> * [x]  This issue is not a duplicate.
It happens with me too

**Comment by Vntonios** [comment]
I have this issue i think it happens when i send snaps without having internet so when i come back home it gets stuck at 0% and my friend gets tons of notifications i hope it gets fixed it is so annoying

**Comment by V1li** [comment]
This is also happening for me.

**Comment by V1li** [comment]
Fully restarting the phone seems to fix it, but it keeps happening pretty frequently. At least for me.

**Comment by TheVisual** [comment]
@rhunk @authorisation this is solved for me i had this issue but never happens anymore we should close 👍
