### ISSUE TITLE
Snapchat Map in Custom Map Location

### ISSUE THREAD

**Issue by hamzaharoon1314** [rhunk/SnapEnhance#352]
### Description

The map currently provided for the custom location to fix isn't as good and user friendly. Maybe we can look into it to update it.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
Suggestions on what to use instead?

**Comment by hamzaharoon1314** [comment]
1. Open Street Map
2. Bings Map

**Comment by authorisation** [comment]
1. OSM is what we use
2. No, proprietary(?)
