### ISSUE TITLE
feat: Export all snap and pictures  

### ISSUE THREAD

**Issue by suleymanlaarabi** [rhunk/SnapEnhance#353]
### Description

Export all snap and pictures from memories to gallery

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by Not-Smelly-Garbage** [comment]
This but for saved media from chats

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/dd755af5be3be51fab88f09042cfca5d0f76a830
