### ISSUE TITLE
bug: Doesn't auto download every snap

### ISSUE THREAD

**Issue by bignonce69420** [rhunk/SnapEnhance#373]
### Description

Sometimes when receiving a snap it will not auto download.
Will notice that the snap hasn't been saved but then will go to manually download the image and it says " allready in que" and will not download till I clear the downloads in the snapenhanse app

### Reproduction steps

1. Recive snap 
2. Never get confirm download notification 
3. See image is not saved
4. Go to manually save snap from the chat menu and says "allready in que"
5. Will not download till downloads are cleared in snapenhance app

### Snapchat Version

12.57.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bignonce69420** [comment]
1.2.5

**Comment by rhunk** [comment]
V1.0 will no longer be updated (except for critical bugs), so please use v2.0.0 from now on.

**Comment by bignonce69420** [comment]
> V1.0 will no longer be updated (except for critical bugs), so please use v2.0.0 from now on.

Where do I find the download for v2.0?
