### ISSUE TITLE
feat: Exact date and time for all stories and all saved media in a friend's gallery

### ISSUE THREAD

**Issue by xnvmx** [rhunk/SnapEnhance#386]
### Description

Please add an option to display the exact time when the story was added like "08/11/2023 14:15", instead of e.g. "15 hours ago"
We really need this.

Edit: I noticed that the same problem occurs in the shared gallery on a friend's profile. There is also a timestamp there as an indication of how long ago a snap or some media was sent instead of the exact date and time.

If you added this, I would be very grateful and I think it's not just me, because being able to see or save snaps and stories with the exact date and time of sending would be useful to many people. I could even pay for it or support you in some way.

### Agreement

- [x] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/752f87179fb71a5aa0440bca4159c5246a75a152

**Comment by xnvmx** [comment]
Thank you so much! ❤ This is the most important functionality for me.

Maybe a stupid question, but how to install app with this update?
Because when I install the latest stable or beta version, it is not there.

**Comment by rhunk** [comment]
@xnvmx join CI build channel [here](https://t.me/snapenhance_ci). Btw these builds expire within 2 weeks so you need to update often.

**Comment by xnvmx** [comment]
@rhunk So I see on that channel that the last update was on November 19, so I have to wait for new CI builds with this new functionality added?

**Comment by rhunk** [comment]
@xnvmx yeah It will be published soon
