### ISSUE TITLE
bug: - Stories / Uploading Your Own Sounds on snapchat are broken now

### ISSUE THREAD

**Issue by TheVisual** [rhunk/SnapEnhance#39]
### Description

Stories / Uploading Your Own Sounds on snapchat are broken now they become blank for stories and for custom audios for snaps that you can create they get suck at 1 second

### Reproduction steps

```bash
1. Go to Camera Roll
2. Click on Video
3. Upload to Story / Create custom audio sound
4. See error
```

### Screenshots

```bash
https://cdn.discordapp.com/attachments/1071627543104467044/1115192013768376360/Screenshot_2023-06-05-03-14-38-64_a63b0f8076346d26cbdc1b971a1da2a7.jpg
https://cdn.discordapp.com/attachments/1071627543104467044/1115192014225547264/Screenshot_2023-06-05-03-14-13-06_a63b0f8076346d26cbdc1b971a1da2a7.jpg
```

### Snapchat Version

12.36.0.53

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by RevealedSoulEven** [comment]
That's what I said. @authorisation you should improve the "bypass video restrictions" such that it expands the maximum video limit from 60s to INT.MAX or LONG.MAX as required. 
Even though you need to do the same with few other classes because there are multiple classes responsible for video length restrictions at different places according to their use.

But making the video length to be treated as 1 second doesn't makes sense.

**Comment by TheVisual** [comment]
@rhunk @authorisation can this be fixed next released this is  critical bug and renders the current app unusable for snaps / stories / audios on current versions

**Comment by RevealedSoulEven** [comment]
Bro do one thing. Turn off video length restriction and use

**Comment by TheVisual** [comment]
@RevealedSoulEven doesn't fix it for me lol don't you think i've done that

**Comment by RevealedSoulEven** [comment]
Yaaa I know, there is a bug where the video length bypass is working even after turning it off. Go to Actions and download the latest build, it's working fine

**Comment by RevealedSoulEven** [comment]
#57 

And please close this issue

**Comment by TheVisual** [comment]
@RevealedSoulEven ARE YOU FUCKING STUPID THIS BUG ISNT FIXED STORIES ARE STIL BLACK

**Comment by RevealedSoulEven** [comment]
Ufff. Read what I said, download the latest build from Actions page and it's fixed there.

**Comment by authorisation** [comment]
related to #31
