### ISSUE TITLE
feat: TITLE

### ISSUE THREAD

**Issue by Madshuman** [rhunk/SnapEnhance#391]
### Description

Dear,,
I installed snapchat 12.57.0.55
With snapchat enhance 1.2.5
I did all step including force stop 
But I didn't show the Gear icon
Any advice?
Thanks in advance
![Screenshot_20231111-155344_EdXposed Manager](https://github.com/rhunk/SnapEnhance/assets/103794038/cd3bb356-69f9-428d-a29e-b4d2bb1117eb)
![Screenshot_20231111-155317_Snapchat](https://github.com/rhunk/SnapEnhance/assets/103794038/649b91f2-2ea0-4350-b51f-0dd5aa2449e8)
![Screenshot_20231111-154419_Snapchat](https://github.com/rhunk/SnapEnhance/assets/103794038/65642d02-7eea-4b53-a03b-e7de73855e57)

### Agreement

- [x] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
Wrong place to ask, get help from someone in the discussion group

**Comment by authorisation** [comment]
Also use LSPosed instead of EdXposed
