### ISSUE TITLE
bug: SnapEnhance options show as strings

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#40]
### Description

When I open the SnapEnhance options within Snapchat, some of the (context) menus there are shown as weird strings.
![Screenshot_20230605-103928](https://github.com/rhunk/SnapEnhance/assets/12681440/aa4b37ab-c45f-43ed-9491-cb00c24e012c)
![Screenshot_20230605-101242](https://github.com/rhunk/SnapEnhance/assets/12681440/10c78bbe-0e97-4925-a175-ddb8d8f100d0)

I have an armv8 device (motorola edge 30 ultra) and installed the proper version. Latest lsposed and enabled the module + rebooted. Granted SnapEnhance storage permissions even. A reinstall didn't help, also trying out my luck with the armv7 version didn't help as well.
Really not a clue why this is happening. 
Features seem to work fine though.
The log says something about "missing translation for [...]"
Maybe it helps to know that my device language is german.

### Reproduction steps

```bash
See description
```

### Snapchat Version

12.36.0.53

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by authorisation** [comment]
Hello thanks for reporting this issue, unfortunately due to heavy changes in the code, the German language is now outdated and needs updating. If you want you can make a pull request and update the language file located here: https://github.com/rhunk/SnapEnhance/tree/main/app/src/main/assets/lang
You can use the en_US.json as reference

**Comment by NMBlanco** [comment]
> Hello thanks for reporting this issue, unfortunately due to heavy changes in the code, the German language is now outdated and needs updating. If you want you can make a pull request and update the language file located here: https://github.com/rhunk/SnapEnhance/tree/main/app/src/main/assets/lang You can use the en_US.json as reference

I understand, but is it possible to just force english language within the app?
I'd rather have the mod in english tbh 😁

**Comment by authorisation** [comment]
> > Hello thanks for reporting this issue, unfortunately due to heavy changes in the code, the German language is now outdated and needs updating. If you want you can make a pull request and update the language file located here: https://github.com/rhunk/SnapEnhance/tree/main/app/src/main/assets/lang You can use the en_US.json as reference
> 
> I understand, but is it possible to just force english language within the app? I'd rather have the mod in english tbh 😁

That depends on what Snapchats language is set to but yeah this could be added in the future
