### ISSUE TITLE
Ability to hide Quick Add section in Chat Tab

### ISSUE THREAD

**Issue by adrienschndr** [rhunk/SnapEnhance#401]
### Description

Hi! I don't think I need to explain more, it's so annoying having recommandations of people, sometimes you can even miss a touch and add someone. It seems that this section only appears when you have less than 10 friends.

Thanks for considerating this feature request!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
Already implemented in a4b7432

**Comment by adrienschndr** [comment]
Sorry, only checked Releases and not Commits

**Comment by Leclowndu93150** [comment]
Hey sorry to bother but i am using 2.0.0 and the option doesn't take effect ![Screenshot_2024-01-24-11-35-07-246_com.snapchat.android.jpg](https://github.com/rhunk/SnapEnhance/assets/73310949/944a1c6c-2dcb-4ebb-a326-4a1c93308954)

**Comment by rhunk** [comment]
@Leclowndu93150 Here are the things you can do:
- check that you're using the latest build from GitHub Actions
- force stop Snapchat and SnapEnhance
- refresh mappings in snapenhance (using the settings menu)
- use a stable version of Snapchat or downgrade

**Comment by Leclowndu93150** [comment]
> @Leclowndu93150 Here are the things you can do:
> - check that you're using the latest build from GitHub Actions
> - force stop Snapchat and SnapEnhance
> - refresh mappings in snapenhance (using the settings menu)
> - use a stable version of Snapchat or downgrade


The build comes from the automatic Telegram builds
I restarted my phone as i couldn't force stop the apps
I did refresh mappings
Snapchat comes from the Google Play Store.

Nothing worked sadly. Do you know any build of snapchat that works so i downgrade ?
