### ISSUE TITLE
bug: Snap not getting saved

### ISSUE THREAD

**Issue by mjain234** [rhunk/SnapEnhance#402]
### Description

Whenever I am taking snaps and saving it, it isn't saving on my device folder as I have already given the storage permission and also save the directory folder. You can see the video 

### Reproduction steps

NIL

### Snapchat Version

12.57.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
Works fine for me

**Comment by sinhy0** [comment]
> Works fine for me, which build are you using? What have you tried to fix it already? 1`
**1-sometimes when I click download, appears "Download dash media" and if click "download" or "download all" download does not work.**
**2-if download video from Spotlight, it create folder for each video in gallery.**

**Thanks**

**Comment by sinhy0** [comment]
> Works fine for me, which build are you using? What have you tried to fix it already?

g

**Comment by sinhy0** [comment]
> Works fine for me, which build are you using? What have you tried to fix it already?

**1-sometimes when I click download, appears "Download dash media" and if click "download" or "download all" download does not work.**
**2-if download video from Spotlight, it create folder for each video in gallery.**

**Thanks**
