### ISSUE TITLE
feat: "Panic" mode

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#407]
### Description

Have there be an option accessible via either the snapenhance gui (settings icon) or the 3 dots at the top right, which quickly removes/clears/hides chats when enabled.

There could even be a security feature which only allows you to re-display/re-whatever those chats when inputting a password/pin.

It could be integrated with the friend menu via a whitelist/blacklist system like stealth mode, or could utilize the "social" tab of snapenhance's app

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by Not-Smelly-Garbage** [comment]
It could also prevent the notifications of messages/snaps sent by any selected friends when panic mode is enabled

**Comment by authorisation** [comment]
Sorry not really seeing the point for this

**Comment by Not-Smelly-Garbage** [comment]
> Sorry not really seeing the point of this

Not that helpfu everyday users, helps people who are hiding things.
Might help some users
