### ISSUE TITLE
feat: Automatic Conversation Hider

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#408]
### Description

Would work by hiding/clearing (actual Snapchat behavior) any conversations that dont have any activity for a customizable amount of time.
For example, removing conversations that haven't been used for over 6 months or a year.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
This could be implemented using the script engine but will not be officially supported.
