### ISSUE TITLE
feat: Stylized Preview

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#409]
### Description

If possible it would be nice to have the preview message screen be stylized in the look of snapchat and possibly even scrollable, with snaps showing as either the unopened snap icon, or actually displaying the snap 

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
I don't see the point here, you can just enable stealth mode and snaps preview
