### ISSUE TITLE
bug: Snaps being saved with file name ChatMedia

### ISSUE THREAD

**Issue by pcxnet** [rhunk/SnapEnhance#410]
### Description

Snaps being saved with file name ChatMedia when 'add media type to file name" is selected

### Reproduction steps

save a snap automatically from a friend and it's labelled as chat media rather than a snap.

### Snapchat Version

12.57.0.55

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Works as intended

**Comment by pcxnet** [comment]
Just wondering what is it called of they send a picture via the chat rather than as a snap? since a snap is generally live but thru chat can be from gallery.
