### ISSUE TITLE
feat: Bypass Emulator detection

### ISSUE THREAD

**Issue by snapboss** [rhunk/SnapEnhance#412]
### Description

Snapchat detects when the app is run on Emulators and because of this doesn't allow to sign up or login to accounts.

Can a detection bypass for this be put into SnapEnhance??

This article shows some of the detection methods snapchat used in the past, maybe can be used for reference.
https://aeonlucid.com/Snapchat-detection-on-Android/

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
I couldn't implement a bypass for emulators and if I ever added one it would be patched pretty quickly because it's opensource.
