### ISSUE TITLE
feat: hide settings gear icon

### ISSUE THREAD

**Issue by sinhy0** [rhunk/SnapEnhance#413]
### Description

1. ~~When share video from gallery to snap and click story,it upload as snap. I suggest when click story show blacklist options because it can upload as "snap"or"original". Searching for video within snapchat wastes time.~~

2. ~~Upload video to story without it split, send whole video.~~

3. ~~Move the download button to the bottom next to the reply box, for easy download.~~

4. ~~When click the download button once,it download current snap. But long click show "Download dash media",for download any snap want or all snap.~~

5. Add option in snapenhance for hide settings gear icon.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/f16eb3a009a30c6347927a6bfdfe04baa6edfae6
