### ISSUE TITLE
Features NOT work

### ISSUE THREAD

**Issue by sinhy0** [rhunk/SnapEnhance#414]
### Description

1- ~~when click "Following" in Stories page show white page, Snapchat 12.60.0.58.( show picture ).~~
2- ~~the Logging"Progress" in Downloader page in snapenhance, NOT work.~~
3- ~~sometime when click download show "download dash media''but NOT work if click "download" or "all download".~~
4- the home in "memories" page after choose video and click Story, it upload as snap direct.NOT show options "snap" or "original". This happens if the video duration is correct!.
5- after click "Recents" in "home" option in "memories " page, Download button above text button.This happens if the language in the app is English.( show picture).
6- ~~This Features NOT work, I chose 4032*3024.like my orginal camera but not work and also the front camera does not work if enabled.AND Custome Frame Rate NOT work, my orginal camera support to 60fps( show picture ).~~

![Screenshot_20231116-110912_Snapchat](https://github.com/rhunk/SnapEnhance/assets/149545509/9bf74189-95f8-42b9-b802-9487febce14d)
![Screenshot_20231116_103748](https://github.com/rhunk/SnapEnhance/assets/149545509/92fc2e76-99ad-471c-a8ab-b80da86962ee)
![Screenshot_20231116-102859_Snapchat](https://github.com/rhunk/SnapEnhance/assets/149545509/b3e0b2b5-7363-4d8c-b400-80e9d1031b9b)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.60.0.58

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
1 turn off "Hide Story Section > Hide for you section"
4 https://github.com/rhunk/SnapEnhance/commit/e956400ffebe740dc61ecc5ffa0c47c0c5c90706
5 https://github.com/rhunk/SnapEnhance/commit/ad048082898d4fd49d1cb4d3c087d891bb397538
