### ISSUE TITLE
Some functions are failing

### ISSUE THREAD

**Issue by donete7** [rhunk/SnapEnhance#416]
### Description

[using Google translator]
Hello, first of all thank the developers for the excellent work! But I came here to let you know that I installed this module yesterday and noticed some flaws such as: many media that I received, whether as snaps or through the chat that I click on the save option in the gallery, do not appear at all, even after restarting and I ended up losing some of them.
Another point is that I didn't find the stealth screenshot option, even if I took the screenshot, the SC still notified my friend that I took it! If you have this option active, could you tell me what it is?
And I also saw that even closing the conversation and then returning, a lot of things still remain there as if they had been saved in the conversation, both for me and my friend.
I am using version 12.57.0.55 / Android 12 / Samsung A11
Sorry for the English, I'm Brazilian. :)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.57.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
Go to settings, click on Prevent message sending and turn on whatever you want. 
Also if you want to download media into the chat, turn on Chat Download Context Menu in settings

**Comment by donete7** [comment]
[using Google translator]
Wow, now everything actually works!!! I believe it's just because I don't understand English very much. It would be interesting in the future to have a video tutorial explaining it or even just a more explanatory post about the options.
Thank you very much! :)
