### ISSUE TITLE
bug: Filter Applied to Snap but dosent show on the chat/snap that it has a filter

### ISSUE THREAD

**Issue by TheVisual** [rhunk/SnapEnhance#418]
### Description

Filter Applied to Snap but dosent show on the snap that it has a filter

### Reproduction steps

1. Go to Camera
2. Click on Photo from Camera Roll
3.  Apply Filter
4. Spoof Image
5. Check chat it's just a red/purple snap but dosen't show that i has a filter in chat like normal snap

### Logs

```markdown
None
```

### Snapchat Version

12.60.0.58

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Unfortunately I can't add the filters as they are not generated before the message is sent.
