### ISSUE TITLE
bug: Merge Overlays not working

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#419]
### Description

Usually having the merge overlays option disabled would remove any and all "extras" from a snap/story/video (drawings, text, overlays, etc.)

Now it seems it doesn't remove anything from images. it does remove text from videos, along with things such as private story invites, but not things like the music descriptions and drawings.

This is a huge difference than previous behavior which stripped anything you downloaded to just the bare image/video, with maybe a mosaic/blur effect underneath where there was drawings.

I am using SnapEnhance CI Build 2.0.0-ff79f20 which is why I didnt select that I am using the latest stable version of snapenhance.

### Reproduction steps

1. Disable "Merge Overlays" from Downloader settings
2. Download any media with overlays
3. See that overlays are there still

### Snapchat Version

12.60.0.58

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by rhunk** [comment]
This is normal behavior as you can't delete some overlays because they've been assembled into a single file (video). This is technically impossible.
