### ISSUE TITLE
feat: - Adding dark mode using Xposed

### ISSUE THREAD

**Issue by RevealedSoulEven** [rhunk/SnapEnhance#42]
### Description

Why not using xposed to add dark mode? Instead of creating another app.

https://github.com/mhashim6/Music-Colors/blob/master/app/src/main/java/mhashim6/android/musiccolors/MusicColorsModule.java

Take this as a reference.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by RevealedSoulEven** [comment]
Adding to this... Few months back I changed something using xposed and it gave me dark mode in snapchat which was being made by the developers itself. It was incomplete as they maybe working on it, it only worked for 2 or 3 layouts.

You can use these texts and change the boolean to True

is_dark_mode
isDarkMode=
forceDarkMode=
is_dark_mode

**Comment by RevealedSoulEven** [comment]
Yaaa that's working good. I edited the snapchat apk in my phone and replaced those boolean to true and yaa they are working fine.

Although you need to use additional colours from "Snapchat Dark" module, but yaaa snapchat is applying some of the intents itself.


![Screenshot_2023-06-05-19-05-04-921_com snapchat android](https://github.com/rhunk/SnapEnhance/assets/49313374/790d133d-c7d5-4b62-8877-65b7e4b8833f)
![Screenshot_2023-06-05-19-05-32-703_com snapchat android~2](https://github.com/rhunk/SnapEnhance/assets/49313374/3516556e-71fd-486c-b880-9c550bd2df8d)
![Screenshot_2023-06-05-19-05-36-202_com snapchat android~2](https://github.com/rhunk/SnapEnhance/assets/49313374/6a0e3e05-7a70-447f-b8e2-479b2fa8972b)

Not only those but some others too. Snapchat literally did half of the job just by changing those boolean to True. Rest of them please do using xposed🥲

**Comment by RevealedSoulEven** [comment]
![Uploading Screenshot_2023-06-05-19-09-41-133_com.snapchat.android-edit.jpg…]()

**Comment by authorisation** [comment]
It'll release soon anyways (hopefully) there's no point of adding something that is halfway finished

**Comment by RevealedSoulEven** [comment]
Naah naaahhhhh.....
In snapchat it's half but if you add using snapchat dark module, it's working fine.

Ya but you're right, leave it for now. Snapchat will give it soon
