### ISSUE TITLE
feat: Invisible but enabled settings icon

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#420]
### Description

I saw a closed issue of someone requesting there be an option to disable the gear icon in the friend feed, but what about having it be there and pressable, just not visible?

It would do what it was meant to do (hide it) while not sacrificing any usability

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
I don't see the point of doing this if you want to use it just disable the option that hides it.
