### ISSUE TITLE
feat: Combined Story Downloader

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#421]
### Description

Similarily to how a menu pops up asking which segments to save when trying to download a story from the discover page, one should pop up when trying to download videos/snaps that are in multiple parts, so you dont have to download several 10 second clips and put them together after the fact.

I feel like this would be be simpler to implement for stories than multi-part snaps

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Unfortunately I can't implement this because only public stories contain a predefined video playlist (mpeg dash) that can be merged. However, it's possible to do this in theory, but impossible to make it compatible for a wide range of Snapchat versions.
