### ISSUE TITLE
feat: Name of saved media

### ISSUE THREAD

**Issue by donete7** [rhunk/SnapEnhance#422]
### Description

[using Google translator]
I have a suggestion that I think would be much better even to recognize where the media was recorded from. It would be interesting if when you save media, it would be saved with the name of the user (friend) and the date it was saved. I believe it would be more organized and better. If there was that possibility, I think it would be an excellent idea!! Thanks again to the developers!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Use the "Download Options" property in settings to customize the file path

**Comment by donete7** [comment]
It's great! tkx :)
