### ISSUE TITLE
bug: Endless snaps

### ISSUE THREAD

**Issue by StasMega** [rhunk/SnapEnhance#423]
### Description

I received snaps yesterday, and today I also see them, and to view new snaps I need to watch them again. I turned off unlimited snap views and message logger. I used non-rooted version.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.60.0.58

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [x] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by schlaf3r** [comment]
Turn off do not send read receipts

**Comment by StasMega** [comment]
Thank you🙂
