### ISSUE TITLE
bug: "friend not found in database" toast

### ISSUE THREAD

**Issue by TheTrueDonDotta** [rhunk/SnapEnhance#424]
### Description

Anytime I scroll through stories specifically through the story tab (doesnt happen when i open stories through the chat tab) it gives me a random "friend not found in database" toast. Not sure if this is actually snapenhance related.

### Reproduction steps

1. Open stories tab
2. Scroll through stories
3. You will see the toast

### Snapchat Version

12.60.0.58

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by Not-Smelly-Garbage** [comment]
Force close Snapchat and clear message logger and Snapchat cache, force stop snapenhance and re open everything, fixed it for me

**Comment by rhunk** [comment]
It's a database corruption I'm still working on a better fix. I close this issue and if it ever happens again let me know.
