### ISSUE TITLE
feat: media / videos

### ISSUE THREAD

**Issue by Nightflyer1975** [rhunk/SnapEnhance#425]
### Description

Can you pls add video option when in chat and want to send a video? Only option to send from gallery while in chat is photos or memory's .

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by Not-Smelly-Garbage** [comment]
What??

**Comment by Nightflyer1975** [comment]
See screenshot. At the bottom you see fotos (photo) and herinneringen (memory's ).  Would like to have the option video as well. Its handy when i want to share videos fast. I can do it now from gallery and then share but takes time when i want to send several .

Hope it can be done . Thanks in advance !😊

_
![Screenshot_20231120_114650_Snapchat](https://github.com/rhunk/SnapEnhance/assets/151477374/07ca5ca1-e43d-44cc-89ca-c8fda667c106)
_

**Comment by rhunk** [comment]
Unfortunately we couldnt add this feature because it's a part of composer modules of Snapchat
