### ISSUE TITLE
bug: How to remove pinned conv with new version ?

### ISSUE THREAD

**Issue by MatisAgr** [rhunk/SnapEnhance#428]
### Description

I would like to delete a pinned conversation but without removing them all. Before I saw the option to do it but since 1.2.4 I no longer find it. Should I do a deletion via deleting the file? Or where is the file to do it manually?

Thanks to those who take the time to answer me :)

### Reproduction steps

To delete the file

1. Go to `SnapEnhance`
2. Click on `the bug button`
3. Scroll down to `Delete Pinned Conversations`

### Snapchat Version

1.2.4

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
You can use the native menu in the friends feed to unpin conversations and there have been no changes since 1.2.4 on this feature.

**Comment by MatisAgr** [comment]
> You can use the native menu in the friends feed to unpin conversations and there have been no changes since 1.2.4 on this feature.

Oh i'm bad, I didn't look well apparently. Thanks for your help !
