### ISSUE TITLE
Sign in error

### ISSUE THREAD

**Issue by EmanuelQeryo** [rhunk/SnapEnhance#429]
### Description

So this has been happening for 2 months and I reported this issue but someone closed the issue for no reason 

So whenever I open the patched snapchat I type all my info then it says my account has been temporarily locked and some other stuff and this doesn't happen on the original snapchat and I tried multiple versions of snapchat but still nothing.

### Reproduction steps

1. Open patched snapchat
2. Click on Login
3. Type username and password
4. Click sign in
5. See error.

### Snapchat Version

Every 12.50-latest

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by EmanuelQeryo** [comment]
And I dunno how to add a log

**Comment by Tobian42** [comment]
![Screenshot_20231120_210141_Snapchat](https://github.com/rhunk/SnapEnhance/assets/115111119/164231c6-4788-4437-a700-83a72e542511)
Here is a screenshot of the error, I updated snapchat and snapenchance to the latest version (12.57.0.55) its tested on and now I can't log in.

**Comment by rhunk** [comment]
Snapchat checks whether the apk has been modified and we do not support that officially.
Btw you could try with LSPatch obfuscation enabled in the Snapenhance manager.

**Comment by EmanuelQeryo** [comment]
What is blud yapping about

**Comment by authorisation** [comment]
Root your device, it's not that hard.
