### ISSUE TITLE
feat: Enhanced friend remover 

### ISSUE THREAD

**Issue by alexxmali** [rhunk/SnapEnhance#432]
### Description

May we please have an easy way to remove friends on Snapchat.Anyone that has tried removing a friend on Snapchat knows it's the worst. It gets 100x worse when it's multiple people that you are trying to unadd. Would appreciate something like a select button where I select multiple people then click remove and it's done(or something close to that)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by Brokoli5191** [comment]
To remove a friend you have to go to their profile -> 3 dots -> manage friendship -> remove friend -> confirmation. This is wayyyy to much clicks if you want to unadd several people, i agree with you. I removed much of my old friends and it took ages. Please add this. Maybe when long tapping on a chat is selecting them?

**Comment by alexxmali** [comment]
> To remove a friend you have to go to their profile -> 3 dots -> manage friendship -> remove friend -> confirmation. This is wayyyy to much clicks if you want to unadd several people, i agree with you. I removed much of my old friends and it took ages. Please add this. Maybe when long tapping on a chat is selecting them?

Exactly. I've been trying to remove people for years and just leave my actual friends but I'm making zero progress. It's so annoying

**Comment by Brokoli5191** [comment]
Try to do it with an auto clicker

**Comment by Brokoli5191** [comment]
But it also takes time and you cant use ur phone when the autoclicker runs

**Comment by rhunk** [comment]
Implemented in https://github.com/rhunk/SnapEnhance/commit/f66859b1fd4cf59c471837fc25afd9c47f238f59
