### ISSUE TITLE
feat: don't repeat name in DM notification preview

### ISSUE THREAD

**Issue by Mattwmaster58** [rhunk/SnapEnhance#436]
### Description

When I receive a DM from someone, the chat notification is extremely useful, and I just have one suggestion: remove the repetition of the name before the chat content.

Example: 
![image](https://github.com/rhunk/SnapEnhance/assets/26337069/b750b472-a3d0-464e-a846-4bb89eb341e7)

I am not sure how hard this is to do well, maybe a heuristic would just be testing if the sender name == conversation name, although this could have false positives (Group name same as someone in the group).

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/ea8723d99067dad86202895dbeb15c8888f7c1b9
