### ISSUE TITLE
bug: cant open the exported HTML file of snaps and media

### ISSUE THREAD

**Issue by MdSaqlainSaeed** [rhunk/SnapEnhance#437]
### Description

Upon exporting snaps and chat media, an HTML file is generated alongside a cache folder. Unfortunately, access to the cache folder was lost, and it has been inadvertently deleted. However, the HTML file remains intact with a substantial size of approximately 1.7GB. Every attempt to open this file in various browsers results in crashes, rendering the content inaccessible.

Seeking guidance, I'm interested in learning how to successfully open this unwieldy HTML file. Additionally, I am inquiring whether there is a viable method to extract the embedded images and videos contained within the file. Any assistance or advice on resolving this issue would be greatly appreciated. Thank you.

### Reproduction steps

1. Go to `...1`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.60.0.58

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Can you specify your SE version please?

**Comment by MdSaqlainSaeed** [comment]
> Can you specify your SE version please?

1.2.5

**Comment by rhunk** [comment]
SE v1 is no longer updated and this bug has surely been fixed in v2.0.0

**Comment by MdSaqlainSaeed** [comment]
> SE v1 is no longer updated and this bug has surely been fixed in v2.0.0

Can you please tell me how to download v2. I am umable to figure it out. Thanks
