### ISSUE TITLE
bug: profile info preview birthday bug

### ISSUE THREAD

**Issue by TheTrueDonDotta** [rhunk/SnapEnhance#438]
### Description

in the profile preview info, for people who aren't sharing their birthday it says "December 0" despite their birthday not actually being in December.

### Reproduction steps

1. Go to the friend tab
2. Long press on a friend that isnt sharing their birthday.
3. Press 'preview'
4. Press 'profile info'
5. See the error with birthdays.

### Snapchat Version

12.60.0.58

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/fb16a220b72227cc8d4759c2d4aa6623f1586abd
