### ISSUE TITLE
bug: snap reply not hide 

### ISSUE THREAD

**Issue by 9875vishal** [rhunk/SnapEnhance#440]
### Description

Snap hide ki notification hide nhi ho rhi check kro why no working snap reply (prevent message)

### Reproduction steps

![Screenshot_2023-11-24-06-58-09-06_a63b0f8076346d26cbdc1b971a1da2a7](https://github.com/rhunk/SnapEnhance/assets/151546708/c0a328c8-17b1-460a-a5df-4e276ed2db8f)

### Snapchat Version

12.62. ..... Beta 

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
Turn on native hooks in experiments
