### ISSUE TITLE
bug: Doesn't export all messages.

### ISSUE THREAD

**Issue by xnvmx** [rhunk/SnapEnhance#442]
### Description

I've been looking for a long time where I could archive my entire chat history, and you've created something brilliant. 

The only problem is that it only exports part of all messages. I have a 3 year old chat with almost 500k messages where it only exports 3/4/5k messages. 
I did an experiment and this number increases as messages are loaded into the cache, but scrolling through 500k messages would take forever. 
When I needed to find a message from a month ago, I had to scroll for hours, let alone when I had to scroll to the beginning to be able to export the entire chat... 

Please add something that allows to export an entire large chat completely in the background. 
You can introduce it as a paid feature, I have been dreaming about something like this for a very long time. 
And during this time - I met many people who just like me, wanted and were looking such a app to archive Snapchat conversations that had taken place over many years with loving couples, friends and family.

### Reproduction steps

1. Go to SnapEnhance app.
2. Click the settings button in the upper right corner.
3. Click on the "Export Chat Messages" action.
4. Select any export format.
5. Select any media types format or don't select at all.
6. Enter a number above 10000 messages or leave empty for all.
7. Select conversations with a person with whom you have exchanged more than 10,000 messages.
8. See that SnapEnhance will only export a portion of all messages.

### Snapchat Version

12.59.0.62

### Agreement

- [x] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
If you want to archive your account I suggest you request the account data from Snapchat website.
However, I've implemented a fix [here](https://github.com/rhunk/SnapEnhance/commit/04fcc33264a9652b2580077b079eef68fc80005e) that should work
