### ISSUE TITLE
The location filter isn't working

### ISSUE THREAD

**Issue by Sha23di** [rhunk/SnapEnhance#444]
### Description

After taking a picture or a video and if you want add a location to it which is appear in the bottom of the screen, it's not working. 

### Reproduction steps

Location filter 

### Snapchat Version

12.60.0.58

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Fixed in 2.0.0
