### ISSUE TITLE
feat: Bulk Clear Chats in addition to Bulk Remove Friends

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#446]
### Description

I see that people have suggested (and that you've started implementing) Bulk Removing Friends (#432) and I'd like to suggest Bulk Clearing Chats, because on new accounts, all people added appear as empty chats even if they didn't add you back (not sure if it's a bug or intentional) and it's really annoying to have to manually clear all the chats.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by khush-img** [comment]
it's already been suggested before. moved to not planned unfortunately :(

**Comment by CompuGenius** [comment]
> it's already been suggested before. moved to not planned unfortunately :(

Oh, that sucks. You sure it can't even be on the back burner?

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/3b0b44fcd44fa67e7a7eacc5c61a003975230191

**Comment by khush-img** [comment]
> Added in https://github.com/rhunk/SnapEnhance/commit/3b0b44fcd44fa67e7a7eacc5c61a003975230191

bulk remove is added? how do we get the update? I'm not familiar with GitHub unless it's an update on releases sectio. sorry :')
