### ISSUE TITLE
feat: Bypass Media Send Limit + Gallery Tweaks

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#447]
### Description

When sending media in a chat you can only select 10 items at a time, this is bypassable by swiping up from the camera, then you can send more than 10 at a time.

Would be cool to see that sort of thing implemented from inside chats, allowing you to select an unlimited/increased number of images to send.

Gallery Tweaks:
It would also be nice to have the option to disable the ability to swipe from camera roll to memories and vice versa from the in-chat media picker, cant count how many times ive selected stuff then accidentally swiped it all away.

Another thing that kinda adds onto that is saving the distance you scrolled in the media picker, so once you send stuff/click off of the media picker, you dont have to scroll alllll the way back to wherever you were, it gets cached and you can open it right back up to there

ONE MORE THING, increase the grid size on the in-chat media picker, so instead of it being 3x2, it could be 3x3 or 4x3

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
After some research, I can't unfortunately modify the chat media drawer because it's a composer module.
