### ISSUE TITLE
bug: Auto Save Messages saves messages specifically unsaved

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#448]
### Description

Auto Save Messages is amazing except when it comes to messages I specifically UNSAVE. It would be great if there was a way that it keeps track of messages unsaved and therefore doesn't save the ones I'm specifically avoiding saving.

### Reproduction steps

1. Enable Auto Save Messages
2. Go to any chat
3. Unsave a message 
4. Leave the chat
5. Reenter chat
6. See message has been resaved

### Snapchat Version

12.61.0.45 Beta

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
I don't see the point of doing this, but feel free to create a pull request if you'd like to contribute.
