### ISSUE TITLE
feat: send snaps without showing you used a filter

### ISSUE THREAD

**Issue by NotApex** [rhunk/SnapEnhance#449]
### Description

The ability to disable showing that you used a filter on a photo eg the try lens under the photo and the filter on the bottom left when you click the snap

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/9c5a590a6088aab4d9a623c732b47757c638a684
