### ISSUE TITLE
bug: Make Chat Download Context Menu Scrollable

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#450]
### Description

When selecting really long messages, the Chat Download Context Menu prevents access to the default Snapchat context menu. Please make it scrollable (like the Snapchat one is) so we can access all options even on long messages.

### Reproduction steps

1. Hold down on a really long message with Chat Download Context Menu enabled.
2. Try accessing any of the default Snapchat context menu items (copy, delete, etc)
3. You can't because you can't scroll past the Chat Download Context Menu.

### Snapchat Version

12.61.0.45 Beta

### Agreement

- [x] I am using the latest stable SnapEnhance version.
- [x] This is not a bug regarding Snapchat+.
- [x] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/78c28a8c9ed86269b81bd818e84e130d7927fe13

**Comment by rhunk** [comment]
@CompuGenius I'm too lazy to fix the scroll so I resized the message preview btw

**Comment by CompuGenius** [comment]
> @CompuGenius I'm too lazy to fix the scroll so I resized the message preview btw

Yeah, I see that in the code haha. That's totally fine, as long as the end result is the same 😄
Can't wait for the new CI or official release with this and the multi-select friends.
Out of curiosity, you closed my Android Auto notifications request as unplanned - does this mean you don't have any interest in it? Or did research and found it's not worth your while? I have lots of Android app experience but no experience with Xposed modules or anything like that. I'd be happy to make a PR, but I don't know where to start.

**Comment by rhunk** [comment]
> Out of curiosity, you closed my Android Auto notifications request as unplanned - does this mean you don't have any interest in it? Or did research and found it's not worth your while? I have lots of Android app experience but no experience with Xposed modules or anything like that. I'd be happy to make a PR, but I don't know where to start.

I closed the issue because I couldn't develop or maintain the functionality atm. 
It's true that for the moment I haven't made a schema explaining how the mod works, but the system that hooks the notifications can be found [here](https://github.com/rhunk/SnapEnhance/blob/dev/core/src/main/kotlin/me/rhunk/snapenhance/core/features/impl/messaging/Notifications.kt) if you'd like to take a look
