### ISSUE TITLE
bug: Snaps do not get downloaded unless there is more than one

### ISSUE THREAD

**Issue by Dennis1507** [rhunk/SnapEnhance#454]
### Description

Whenever I open a snap received from a contact, it does not automatically download, even though the setting for it is turned on.
When I receive multiple snaps from a single contact however, every snap except the first one gets saved.

### Reproduction steps

1. Open a snap
2. See that it doesn't save

### Snapchat Version

12.60.0.58

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
@Dennis1507 which version are you using

**Comment by Dennis1507** [comment]
> @Dennis1507 which version are you using of SE

1.2.5

**Comment by rhunk** [comment]
Clear mappings file in debug settings and if it still doesnt work use a beta version of Snapchat
