### ISSUE TITLE
feat: change icon like material you

### ISSUE THREAD

**Issue by 9875vishal** [rhunk/SnapEnhance#457]
### Description

change icon like material you
![InShot_20231129_152010333](https://github.com/rhunk/SnapEnhance/assets/151546708/b029decf-ac64-43a3-bd57-ce04f104886f)
Like this when dark mode enable change dark icon Monet theme when light mode change Monet theme like md garm icon 

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Already implemented
