### ISSUE TITLE
feat: Quick Access "Merge Overlays" Setting

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#459]
### Description

Could add a toggle to turn on and off merge overlays easily. It could be next to the download button in the press and hold ui and could be hidden in the snapenhance app settings.

It would make the download function easier so you dont have to go back and forth through settings if you want to enable and disable it.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
The settings gear is already a quick way to toggle features, I guess it's enough
