### ISSUE TITLE
bug: Crashing

### ISSUE THREAD

**Issue by lancXD** [rhunk/SnapEnhance#462]
### Description

Sometimes when I open friends chats my snapchat just flat out crashes.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.60.0.58

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Bug fixed in 2.0.0

**Comment by arfanvlk** [comment]
I am having the same issue and i am using the latest beta on my pixel 7 Pro
