### ISSUE TITLE
bug: SnapEnhance Bridge service not install

### ISSUE THREAD

**Issue by THON1203** [rhunk/SnapEnhance#463]
### Description

I have this problem where always when I start Snapchat with SnapEnhance it doesn't work it always give me the a popup with the title of the screen and even after reinstall and getting the latest version it doesn't help. And even though this issue already exists it doesn't help.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.63.0.39

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by THON1203** [comment]
My phone is the Moto G84 from Motorola and (I think!!!) I can unlock it tomorrow or after tomorrow

**Comment by rhunk** [comment]
@THON1203 If you just updated I recommend you to patch Snapchat again using LSPatch

**Comment by THON1203** [comment]
I never updated this is the first time I installed SnapEnhance

**Comment by authorisation** [comment]
Provide logcat

**Comment by rhunk** [comment]
@THON1203 do you have both snapchat app and snapenhance app installed?

**Comment by THON1203** [comment]
No I used LSPatch and install SnapEnhance as a Module

**Comment by THON1203** [comment]
I fixed my problem by install the snapenhance APK and Snapchat with the snapenhance module
