### ISSUE TITLE
Extra buttons not showing in the "..." menu

### ISSUE THREAD

**Issue by lancXD** [rhunk/SnapEnhance#464]
### Description

![Screenshot_20231129_193126_Snapchat](https://github.com/rhunk/SnapEnhance/assets/144092626/5126e9bb-d6ad-45aa-9287-bdcdae4c7c6a)
The extra buttons like Clear Cache, Choose Location, etc. aren't there for some reason. I am using the latest debug version.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.62.1.63

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Moved to Snapenhance settings (home section > settings gear on top right corner)
