### ISSUE TITLE
feat: option to force english language within the mod

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#47]
### Description

An option to force english would be cool, because I just like to have the mod descriptions in the original language.
Right now, SnapEnhance forces the system language of my device (german).

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
It actually depends on which language Snapchat is set to not the system language
Also it would look really weird if there are certain things in English while the rest of the app is still in German
