### ISSUE TITLE
Forced highest frame rate not working 

### ISSUE THREAD

**Issue by Efg13** [rhunk/SnapEnhance#473]
### Description

Using s22 Ultra, forced high frame rate doesn't seem to work. Used several different versions

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.52.0.60

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
This has been fixed in v2.0.0

**Comment by Efg13** [comment]
Oh, I wasn't aware there was a v 2.0.0 everytime I click the downloads the newest it shows is 1.25
