### ISSUE TITLE
Visual bug at discovery page

### ISSUE THREAD

**Issue by brog-io** [rhunk/SnapEnhance#474]
### Description

When disabling the spotlight,  you get the discovery page. But it has a visual bug that it's very pleasant to look at.
![Screenshot_20231203_104217_Snapchat](https://github.com/rhunk/SnapEnhance/assets/141176104/35e33216-2bc7-477d-aa09-25601752742c)

### Reproduction steps

1. Disable the spotlight
2. Go to Discovery page
3. Look

### Snapchat Version

12.62.1.53

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/111
