### ISSUE TITLE
feat: Hitting streaks faster on Snapchat

### ISSUE THREAD

**Issue by xnvmx** [rhunk/SnapEnhance#476]
### Description

A notification, some note in the "Preview" or "Friend Feed" at what time friend or me must send a snap to hit next number in the streak as soon as possible.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
What do you mean with this?

**Comment by Not-Smelly-Garbage** [comment]
I think they meant an indication of when sending a snap would increase your streaks with someone.

**Comment by authorisation** [comment]
Needs investigating, got any idea how this should work? At which point does Snapchat increase the counter? We have no clue.
The algois sadly server-sided.

**Comment by TheVisual** [comment]
@authorisation @rhunk this isn't even possible
