### ISSUE TITLE
feat: Hide UI Elements when editing video

### ISSUE THREAD

**Issue by snapboss** [rhunk/SnapEnhance#477]
### Description

Long Story Short : I have automation scripts on Snapchat, which break because some of these UI elements appear sometimes and sometimes they don't. 
Is it possible to implement a feature to show only some of these and hide all others I don't need?
[Screenshot_20231206_104003_Snapchat](https://github.com/rhunk/SnapEnhance/assets/113789609/3e606cb2-e96b-45ae-b143-4373596ad0a2)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by Not-Smelly-Garbage** [comment]
Where do you get scripts?

**Comment by rhunk** [comment]
@snapboss We don't support automation tools and most people won't use it. However, you can always create your own script to hide these elements
