### ISSUE TITLE
bug: Downloaded stories (posted on public profiles) will not include correct info in filenames

### ISSUE THREAD

**Issue by sn-o-w** [rhunk/SnapEnhance#478]
### Description

Exactly like the title says.

By public stories, I mean this: 
![Screenshot_4](https://github.com/rhunk/SnapEnhance/assets/2406819/201d848e-64aa-42f8-8bf3-aad066250c58)

Downloading any of those public stories will result to this:
![Screenshot_3](https://github.com/rhunk/SnapEnhance/assets/2406819/44a70d0a-c81f-4ce2-8f3f-8919f11f66e8)

I can reproduce this on both real device and WSA. It was easier for me at this moment to make some screenshots from my computer.

This issue was discovered on latest CI build of SnapEnhance 2.0.

### Reproduction steps

1. Go to SnapEnhance, then select "Downloader"
2. Select "Path Format", then enable "Create folder for each author" + "Add the username to the file name" + "Add the date and time to the file name"
3. Go to Snapchat, then go to your Following section
4. Find a Snapchat user that has public stories, then download any public story you want.

### Snapchat Version

12.64.0.40 Beta

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
This has already been fixed [here](https://github.com/rhunk/SnapEnhance/commit/0984644adcaddcc0a4efc18e7949d9b8f4dbe4d9)

**Comment by authorisation** [comment]
> @rhunk Please email me: **sn_ow@tutanota.com**
> 
> 
> 
> I can send you a recording to show you this is still a problem. I don't want to publicly reveal my friends' personal information, so please email me so I can send the video to you.

Censor it then.

**Comment by authorisation** [comment]
You're running an old build, your recording shows a hash that is longer than 8 chars which is not possible.
https://github.com/rhunk/SnapEnhance/blob/dev/core/src/main/kotlin/me/rhunk/snapenhance/core/features/impl/downloader/MediaDownloader.kt#L169

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/abfbe86a917a51e2fcbf74ac2dfe500ce6892f30
However, in rare cases for some stories you must follow to display the original username in file path, otherwise the display name will be used.
