### ISSUE TITLE
bug: Snapchat hangs and force close

### ISSUE THREAD

**Issue by loca-lhost** [rhunk/SnapEnhance#480]
### Description

Whenever the snapenchance is enabled and snapchat is pushed to the background, I have to force close the app before it becomes usable again. It happens on the CI and stable builds

### Reproduction steps

Activate snapenchance 
Open snapchat 
Push it into the background 
Open snapchat again and you are met with a black screen. 
The force close dialog will appear 
Hitting ok to close the app and dialog is the way to use the app again. 

### Snapchat Version

12.63.055

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by rhunk** [comment]
I can't reproduce your issue how do you want me to fix it if you don't give any logcat or lsposed logs?

**Comment by loca-lhost** [comment]
[LSPosed_2023-12-09T00_28_26.369054.zip](https://github.com/rhunk/SnapEnhance/files/13622081/LSPosed_2023-12-09T00_28_26.369054.zip)
[snapenhance-logs-1702081658018.zip](https://github.com/rhunk/SnapEnhance/files/13622087/snapenhance-logs-1702081658018.zip)

**Comment by rhunk** [comment]
I still can't reproduce it. Can you try to clean install both SE and Snapchat, it may solve the problem. Please let me know

**Comment by loca-lhost** [comment]
I have and same thing happens. This is a video recording of what happens. https://github.com/rhunk/SnapEnhance/assets/35551569/0a2eaa52-2938-4cb4-acac-4de02f14f226

**Comment by authorisation** [comment]
Do you have Battery Optimization off for Snapchat and SnapEnhance? This has been resolved on MIUI before by turning that off.

**Comment by loca-lhost** [comment]
Issue has been resolved thanks...
