### ISSUE TITLE
feat: Download media multiple times 

### ISSUE THREAD

**Issue by Rainerr123** [rhunk/SnapEnhance#481]
### Description

If you download an image, delete it, then try download it again you will get "media already downloaded", maybe this is an issue unique to me but I've had this happen twice.
Is the media already downloaded required? Could it just overwrite it, or can it check if the file actually exists and not just that it's been downloaded?
Thankyou :)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/368d70226d3cd1da327107970a45fc1dc3d1843d
