### ISSUE TITLE
Notification tone issue

### ISSUE THREAD

**Issue by gladwin890** [rhunk/SnapEnhance#483]
### Description

Snapchat is using phone default notification instead of Snapchat native notification tone and no way to change it

### Reproduction steps

While receiving any snap

### Snapchat Version

12.63.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
A clean install of Snapchat should fix this issue
