### ISSUE TITLE
feat: Disable friend suggestions in story

### ISSUE THREAD

**Issue by brog-io** [rhunk/SnapEnhance#484]
### Description

I randomly got this on my stories page, it'd be nice I could toggle it off.
![3pPXyvhb](https://github.com/rhunk/SnapEnhance/assets/141176104/036b5a3a-0505-4430-b87d-9aa3c008148b)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/af138225f13159b86430fc92a489889b83c27427
