### ISSUE TITLE
Can't save spotlight videos

### ISSUE THREAD

**Issue by lancXD** [rhunk/SnapEnhance#486]
### Description

![Screenshot_20231209_153833_Snapchat](https://github.com/rhunk/SnapEnhance/assets/144092626/4e922f0b-3650-45b7-9c2f-10052b1c83b9)
This happens everytime i try to save Spotlight Videos using SnapEnhance

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.65.0.28

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/62396885e23e976213cf4418c51671622431d6dd

**Comment by rhunk** [comment]
@lancXD https://t.me/snapenhance_ci
