### ISSUE TITLE
bug: Hide suggested friend stories creates blank spaces

### ISSUE THREAD

**Issue by brog-io** [rhunk/SnapEnhance#488]
### Description

![Screenshot_20231210_084102_Snapchat](https://github.com/rhunk/SnapEnhance/assets/141176104/d2d5e71e-8da5-44bd-ab65-49e4d8a60f90)

### Reproduction steps

1. Enable hide suggested friend stories
2. Go to the story section
3. You should see blank spaces where there used to be suggested friends

### Snapchat Version

12.63.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Already fixed in https://github.com/rhunk/SnapEnhance/commit/9583d67bf1da3c9abb1f35a1000d1186ab07a154
