### ISSUE TITLE
Regarding Snap Enhance

### ISSUE THREAD

**Issue by PratikGaikwad2003** [rhunk/SnapEnhance#490]
### Description

I'm not able to send snaps using snap enhance
![Screenshot_20231211_134505_Snapchat](https://github.com/rhunk/SnapEnhance/assets/125955372/16bba6c0-987f-4c64-903f-ea497b87da5c)
It's just showing sending snaps but I waited for so long still the snaps haven't being sent please help me how can I fix this

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.39.0.48

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Unfortunately I can't reproduce the issue. This does not seem to be related to snapenhance, check your internet connection or upgrade to the latest version of Snap and SE.
