### ISSUE TITLE
feat: fake add from quick add list

### ISSUE THREAD

**Issue by finniday** [rhunk/SnapEnhance#494]
### Description

A way for you to add someone specific by search but it shows up as you added them from the quick add list

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
Already implemented

**Comment by lemans-milan** [comment]
> Already implemented

I'm sorry I didn't see that, how do I do this?

**Comment by khush-img** [comment]
> Already implemented

I'd also like to know how to do this?

**Comment by rhunk** [comment]
@khush-img download ci build here : https://t.me/snapenhance_ci
