### ISSUE TITLE
Issues logging in 

### ISSUE THREAD

**Issue by ArchieAngelo** [rhunk/SnapEnhance#495]
### Description

Hi ever since the latest snapenhance update I haven't been able to login into my account through snapenhance at all but I can login through the app store version is there any solution to this ?

### Reproduction steps

1.start up Snapchat with snapenhance 
2. Click on login
3. Put in your info 
4. See error.

### Snapchat Version

Latest 

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
You should patch using LSPatch manager instead of SE manager for now

**Comment by ArchieAngelo** [comment]
> You should patch using LSPatch manager instead of SE manager for now

I am using LSpatch and I'm getting that issue

**Comment by khaledmoayad** [comment]
I am also getting this issue right now

**Comment by rhunk** [comment]
@khaledmoayad [t.me/snapenhance_chat](t.me/snapenhance_chat)

**Comment by thepapisogram** [comment]
I just found out about SnapEnhance. I've followed the steps with LSPatch and after installing the new APK, I cannot login. Snapchat says suspicious activity
