### ISSUE TITLE
feat: Option to download all media in a chat.

### ISSUE THREAD

**Issue by Czernobo** [rhunk/SnapEnhance#496]
### Description

Was wondering if it's possible to add that feature? Could be only possible if all media is loaded before downloading to make it easier, maybe?

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Export a conversation to HTML using the chat export feature and downloaded files will be located in /sdcard/Download/SnapEnhance/cache
