### ISSUE TITLE
bug: snapchat crash

### ISSUE THREAD

**Issue by Adity1243** [rhunk/SnapEnhance#500]
### Description

![Screenshot_2023-12-15-17-58-42-888_me rhunk snapenhance-edit](https://github.com/rhunk/SnapEnhance/assets/131557644/f3ddabb3-6b14-4748-8fb3-e8ccf9c1c55e)

When enabling  hide ui elements option in snapenhance v1.2.5, the snapchat crashes when opened chat screen.

Snaphenhance v1.2.5
Snapchat v12.64.0.42

### Reproduction steps

Patch snapchat v12.64.0.42
Enable hide ui elements in snapenhance
Open chat in snapchchat app then it crashes everytime

### Logs

```markdown
.
```

### Snapchat Version

12.64.0.42

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/492
