### ISSUE TITLE
bug: manually marking stories as "read" not working

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#501]
### Description

So when I have "Anonymous Story Viewing" enabled and view a story, the seen state is hidden properly.
But when I try to manually mark the story as read afterwards (through the friend feed menu buttons), it doesn't work as intended. It still doesn't show that I've viewed it, even after restarting Snapchat on both my phone and the story-sending phone.

**Edit:** Also I just tried to disable "Anonymous Story viewing" and viewed the same story again. Even then it won't mark the story as read anymore. I tried restarting and clearing cache of both phones, but no matter how often I try to view the story now (with anonymous story viewing DISABLED) it just doesn't work anymore. It remains as unseen.

**2nd edit:** Seems like the feature "Prevent Story rewatch indicator" causes this issue. I had it enabled and now I disabled it and tried to view both stories again, which marked them both as seen immediately. So there seems to be a bug with that feature I believe.

The initial issue with the "mark stories as seen" friend feed menu button remains though. Clicking on it while having Anonymous Story viewing enabled, does nothing

### Reproduction steps

1. Enable Anonymous Story viewing
2. View a story (it won't show your seen state)
3. Click on "mark stories as seen" within friend feed menu
4. It still doesn't mark the story as seen

### Snapchat Version

12.64.0.42 and latest CI build (abfbe86) 

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Unfortunately the feature to mark stories as seen is client-side only and will probably never be implemented as it requires a signed request to SC.
I've changed the titles to clarify things [here](https://github.com/rhunk/SnapEnhance/commit/0fdd7b576f3279a7147e458342bd1ea9c047f740)
"Prevent Story Rewatch Indicator" only prevents your friends from knowing if you've watched twice. It only works when "anonymous story viewing" is disabled AND if the story has not been seen locally.
