### ISSUE TITLE
feat: Friend Add Timestamp + UI Improvements

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#502]
### Description

Could use the opera quick info setting to have a toggle to see when someone added you.

UI Improvements:
Add an icon or some indication to settings that have more menus behind them.
![IMG_20231215_160613](https://github.com/rhunk/SnapEnhance/assets/62516050/b19232d4-8e2c-4335-ab11-ea5356d440d0)
Would probably look better, i just made that quickly on my phone

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
1. Preview > Profile Info > Added Date
2. There is already a separator on the left of the switch.
