### ISSUE TITLE
Stay logged in

### ISSUE THREAD

**Issue by theycallmemonkey** [rhunk/SnapEnhance#503]
### Description

I have a friend who's shy, and I sometimes get in his account to help him, but when he signs into the account to see it signs me out. Idk if there's a way to keep us both signed into the account.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/d70fb0f193888b146a31faa4802990a188afd5cd
