### ISSUE TITLE
Issues with login 

### ISSUE THREAD

**Issue by ArchieAngelo** [rhunk/SnapEnhance#504]
### Description

It tells me that due to suspicious activity or too many failed attempts even though I haven't made failed attempts I'm using ls patch to do it and I'm using just 1.2.5 version of snapenhance which Snapchat version should I use and from where ? Also do I need to install a debug and if so place it where ?

### Reproduction steps

1. Go to login
2. Put my data in 
3. Too many failed attempts or suspicious activity 
4. See error.

### Snapchat Version

Every single one of them 

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by ArchieAngelo** [comment]
This is the issue I'm running into

**Comment by rhunk** [comment]
Join [t.me/snapenhance_chat](https://t.me/snapenhance_chat) for support
