### ISSUE TITLE
feat: merge split media

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#506]
### Description

When downloading a story or multi part snap, have the segment selector pop up like when downloading public stories. If multiple sections are selected, use ffmpeg to combine them into one video instead of multiple 10 second clips.

~~An option to delete logged items older than a customizable time period would be a useful implementation alongside the story and message logger, could help keep storage use down.~~ https://github.com/rhunk/SnapEnhance/commit/b925e8f54664d9aa7f92d43693a886051e1960af

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/04b70431c7b384bae81a79ebbdc9675046a9a643

**Comment by AntiHate** [comment]
Is this feature available? Can you provide any information on how to enable it? Thanks!
