### ISSUE TITLE
bug: Cameo not appearing in settings or chat

### ISSUE THREAD

**Issue by nahhurr** [rhunk/SnapEnhance#510]
### Description

Cameo doesn't appear in chat and also in the settings where you can enable it.
![Screenshot_2023-12-17-20-48-23-91_a63b0f8076346d26cbdc1b971a1da2a7](https://github.com/rhunk/SnapEnhance/assets/74925355/e02ca948-eef2-4d6b-9ea1-8e857fb45d47)
![Screenshot_2023-12-17-21-49-33-60_a63b0f8076346d26cbdc1b971a1da2a7](https://github.com/rhunk/SnapEnhance/assets/74925355/b430e908-a33a-4208-9f8c-9cbed7e112a9)

### Reproduction steps

In chat:
1. Go to `Chat`
2. Click on `emoji icon above the Keyboard`
3. You won't find the cameo Icon

In settings:
1. Profile
2. Gear icon (settings)
3. Then under 'Manage Photoshoot Snaps' there was supposed to be cameo but it's missing.

### Snapchat Version

12.64.0.42

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
This bug is not related to SnapEnhance, try on another device / Snapchat version

**Comment by nahhurr** [comment]
I've tried other versions of Snap but it still doesn't work.
