### ISSUE TITLE
Sending stuff from camera roll

### ISSUE THREAD

**Issue by agarfa433** [rhunk/SnapEnhance#512]
### Description

whenever I try to send someone things from my camera roll, if I select multiple things, when I send only the first shows up and the others just buffer and don't load. Also when I try to send a picture to someone it will send as like a 3 second video and it's annoying. 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

 12.57.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Turn off "disable snap splitting"
