### ISSUE TITLE
bug: Uninstalling the mod and then reinstalling from playstore doesn't work

### ISSUE THREAD

**Issue by EricKuper** [rhunk/SnapEnhance#514]
### Description

I tried SnapEnhance for the first time. But I don't see myself using this feature a lot. So I decided to uninstall the mod but when I reinstall the original app from playstore, I can't install the app.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

Latest version 

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
You should uninstall Snapchat first and then install it from playstore
