### ISSUE TITLE
cannot login. says too many tries

### ISSUE THREAD

**Issue by T3lluz** [rhunk/SnapEnhance#516]
### Description

when trying to login it says to many requets after new installation to newest version

### Reproduction steps

1. Go to login page android
2. Click on login after filling in info
3. Scroll down to ....
4. See error: too many reqests

### Snapchat Version

12.64.0.42

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://t.me/snapenhance_chat
