### ISSUE TITLE
feat: toggle to prevent bitmoji appearing as active while having snapmaps enabled

### ISSUE THREAD

**Issue by Rooklz** [rhunk/SnapEnhance#517]
### Description

Would be cool to see a toggle to stop appearing as active on snapmap when opening snapchat. Better than ghost mode/disabling location since both make your bitmoji dissapear from the map instead of displaying when you were last active.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/cc94ea93b27398a0ef17b1d6e259f525a2d796ae
