### ISSUE TITLE
bug: Snapchat+ Features 

### ISSUE THREAD

**Issue by shadowking1443** [rhunk/SnapEnhance#518]
### Description

Hi all!

After enabling the Snapchat+ features option, it doesn't appear the features are working. Such as the planet bff orbit, the snapscore changes, etc...

### Reproduction steps

1. Go to `SnapEnhance Settings'
2. Click on `Enable Snapchat+'
3. Try any SnapChat+ feature.
4. See error.

### Snapchat Version

12.57.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by sheeepdev** [comment]
https://github.com/rhunk/SnapEnhance/issues/273#issuecomment-1722547772
