### ISSUE TITLE
Remove the restore streaks button

### ISSUE THREAD

**Issue by Y0SH1zzzz** [rhunk/SnapEnhance#519]
### Description

I'm so tired of seeing this also makes it impossible to see if they've opened my chat. 

Kind of lame suggestion but I hate to see that button

![Screenshot_2023-12-21-08-46-40-948_com snapchat android-edit](https://github.com/rhunk/SnapEnhance/assets/70285938/53ff18a5-ce61-401b-8e4e-cf208c1c3d0b)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Already implemented https://github.com/rhunk/SnapEnhance/blob/dev/core/src/main/kotlin/me/rhunk/snapenhance/core/features/impl/ui/HideStreakRestore.kt

**Comment by Y0SH1zzzz** [comment]
Am I just stupid or how do I use that?

**Comment by rhunk** [comment]
@Y0SH1zzzz download the latest v2.0.0 build [here](https://t.me/snapenhance_ci)

**Comment by Y0SH1zzzz** [comment]
Well that was a ton better but now where do I find which version it is tested on? Crashes all the time now
