### ISSUE TITLE
Sent Snaps Missing Text

### ISSUE THREAD

**Issue by 6R1M4C3** [rhunk/SnapEnhance#520]
### Description

When you send a snap to someone with this module installed and active the text you put on the snap is removed and not sent with it, this wasn't happening before but has now started to do this? 

### Reproduction steps

1. Go to `send snap`
2. Click on ` create a snap and write text`
3. Scroll down to `send snap and open you will see no text`
4. See error.

If you disable the module and try it will send normally 

### Snapchat Version

12.64.0.42

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Turn off "disable snap splitting" or "bypass video length restrictions"

**Comment by 6R1M4C3** [comment]
> Turn off "disable snap splitting" or "bypass video length restrictions"

Thank you that worked 😁
