### ISSUE TITLE
feat: Message Logger Update

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#522]
### Description

I noticed someone in a groupchat i was in got into and argument then left, but the message logger didnt save anything. Would be nice to have it save messages from people who leave.

It would be nice if the person who left the groupchat doesn't immediately disappear, and you could see when their profile they left by opening the group profile, they could be highlighted in red or something with a timestamp of leaving and maybe even joining.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Unfortunately, I can't restore graphically the messages of people who have left a group. However, the messages are saved in the database, which you can export if needed.
