### ISSUE TITLE
feat: Settings page instead of discovery

### ISSUE THREAD

**Issue by brog-io** [rhunk/SnapEnhance#523]
### Description

It'd be cool if you could change the discovery page to be Snapenhance settings instead. Discovery looks pretty buggy and this can't be fixed sadly. 
![Screenshot_20231222_165529_Snapchat](https://github.com/rhunk/SnapEnhance/assets/141176104/eef730f9-ffcf-47d8-b3fc-0716e88b7c71)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
SnapEnhance settings can only be accessed via the settings gear or from the app launcher for compatibility reasons.
