### ISSUE TITLE
Access to snapchat temporary disabled

### ISSUE THREAD

**Issue by sneazy-ibo** [rhunk/SnapEnhance#524]
### Description

Snapchat was working perfectly fine before updating Snapenhanxe to v2. However after updating I am not able to login anymore and it gives me this pop-up message whenever I try to login.
![Screenshot_20231222_232711_Snapchat](https://github.com/rhunk/SnapEnhance/assets/41344259/271cec93-d8c8-4a72-95c7-5d815f1f86f7)
I took into consideration that my snapchat account might be banned but this is not the case since I can still login through the browser so this issue must be related to SnapEnhance.

### Reproduction steps

happened after updating snapenhance v.2

### Snapchat Version

12.65.0.38

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by Not-Smelly-Garbage** [comment]
Try to disable spoof options, clear cache. Maybe repatch with core.apk on latest stable snapchat release.

Or you got banned :/

**Comment by sneazy-ibo** [comment]
@Not-Smelly-Garbage 
I uninstalled everything and the snapchat data too and could login through the official snapchat version. I also checked my emails in case I got banned but I got none. It was probably too many login attempts.

I am trying to "update" the modded snapchat through the core apk but installing the core apk itself doesn't work.
I firstly installed the SE manager, then installed snapenhance univ through telegram and then updated snapchatenhance with the core apk and after that it just keeps crashing. Even if I install the core apk alone it gives me this error.

![Uploading Screenshot_20231223_164247_Device care.png …]()

**Comment by bocajthomas** [comment]
> @Not-Smelly-Garbage I uninstalled everything and the snapchat data too and could login through the official snapchat version. I also checked my emails in case I got banned but I got none. It was probably too many login attempts.
> 
> I am trying to "update" the modded snapchat through the core apk but installing the core apk itself doesn't work. I firstly installed the SE manager, then installed snapenhance univ through telegram and then updated snapchatenhance with the core apk and after that it just keeps crashing. Even if I install the core apk alone it gives me this error. ![Screenshot_20231223_164247_Device care.png](https://private-user-images.githubusercontent.com/41344259/292633972-da6a7e0b-3ccf-4d23-a18b-39770f965a4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNzExMjUsIm5iZiI6MTcwMzM3MDgyNSwicGF0aCI6Ii80MTM0NDI1OS8yOTI2MzM5NzItZGE2YTdlMGItM2NjZi00ZDIzLWExOGItMzk3NzBmOTY1YTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDIyMzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTA3NDUyMzQ2MjczMDJlYmVkNzgzNjdkYTQ5Yjk2Y2ZlZTE1ZTM4N2IxYTA2MmI0ZDAwMTA0YTMyMmE4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b49Iv85cVci_Py7cfmoT3IpoAkHe6FkcaykearRlvQ8)

Your NOT Ment to install core.apk . Core.apk is used for only Patching

**Comment by bocajthomas** [comment]
> @Not-Smelly-Garbage I uninstalled everything and the snapchat data too and could login through the official snapchat version. I also checked my emails in case I got banned but I got none. It was probably too many login attempts.
> 
> I am trying to "update" the modded snapchat through the core apk but installing the core apk itself doesn't work. I firstly installed the SE manager, then installed snapenhance univ through telegram and then updated snapchatenhance with the core apk and after that it just keeps crashing. Even if I install the core apk alone it gives me this error. ![Screenshot_20231223_164247_Device care.png](https://private-user-images.githubusercontent.com/41344259/292633972-da6a7e0b-3ccf-4d23-a18b-39770f965a4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNzExMjUsIm5iZiI6MTcwMzM3MDgyNSwicGF0aCI6Ii80MTM0NDI1OS8yOTI2MzM5NzItZGE2YTdlMGItM2NjZi00ZDIzLWExOGItMzk3NzBmOTY1YTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDIyMzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTA3NDUyMzQ2MjczMDJlYmVkNzgzNjdkYTQ5Yjk2Y2ZlZTE1ZTM4N2IxYTA2MmI0ZDAwMTA0YTMyMmE4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b49Iv85cVci_Py7cfmoT3IpoAkHe6FkcaykearRlvQ8)

1.install SnapChat From Google Play
2.open LSPatch
3.tap the manage tab
4.then tap +
5.tap installed apps
6.Find Snapchat 
7. Tap integrated 
8. Tap embed 
9. Tap from apks 
10. Find core.apk
11. Tap start Patch 
12. Then once finished tap install ( Shizuku needs to be running) 
13. Press Ok if it says uninstalling cuz of Signatures....
14. Now install SnapEnhance v2 latest ci 
15. Set up 
16. Then open snapchat 
17. Set up 
18. Done

**Comment by rhunk** [comment]
https://t.me/snapenhance_chat

**Comment by sneazy-ibo** [comment]
@bocajthomas Tysm for the clarification however there still seems to be a problem

The first thing I did was using SE manager which had by itself some issues so I switched back to LSpatch.

I've done everything as you listed it but instead of patching with the core apk I patched snapchat directly with snapchat enhanced which atleast successfully reinstalled snapchat atleast.

Now I've done everything exactly as you said with snapchat patched by the core apk first and then installing snapchat enhanced. Everything installed the right way I even got the successful updated snapenhanced popup notification for the first time but now I am back to where I was.

Snapchat lets me login easily through the official version but everytime I patched it it gives me this error. Weirdly enough this has nothing to do with my account since my account is neither locked nor disabled. This has to be related to snapchat enhance since it only happens whenever I patch snapchat.
![Screenshot_20231224_000109_Snapchat.png](https://github.com/rhunk/SnapEnhance/assets/41344259/b02517d7-f7f0-49dc-9c35-e35858bbc218)

**Comment by squashiemallow** [comment]
So i installed also the same way u did and got the same message everytime so i figured it out i installed the lastest beta version from apk site https://www.apkmirror.com/apk/snap-inc/snapchat/snapchat-12-76-0-34-beta-release/snapchat-12-76-0-34-beta-android-apk-download/download/?key=eab17fa970141ae59758e8347a544157382c0466&forcebaseapk=true and patched that with the core and installed the other snap enhance module and it now works

**Comment by mark1942** [comment]
Can't seem to get back in control of your account? There's only one person to contact: AngelinaChristopher1738@gmail.com this lady works for META i suggest you contact her. Alternatively, you can reach her on Instagram at Angelina_Christopher1738. Her dependability and level of skill are unparalleled. Contact her right now with any questions you may have about your social media accounts!
