### ISSUE TITLE
bug: Hide from friend feed Not Complete

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#525]
### Description

Hiding a person or group doesnt hide them from search, you can not open the chat or view info on it, but you can double tap and send a snap.

Not sure if this is a bug or just overlooked but it exists

### Reproduction steps

1. Enable and hide a group or friend
2. Search for them
3. They show up

### Snapchat Version

12.64.0.42 (v2.0.0 699da49)

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
It works as expected, only conversations in in the friend feed can be hidden
