### ISSUE TITLE
feat: More Themes To SnapEnhance 

### ISSUE THREAD

**Issue by bocajthomas** [rhunk/SnapEnhance#526]
### Description

I would like to see more themes added 
E.g. Amoled Dark Mode on SnapEnhance 
Ik it will be low priority but love to see it 
Also merry Christmas and Happy New year 
SnapEnhance 2024 👀👀 

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/159
