### ISSUE TITLE
 feat: option to add/change emoji

### ISSUE THREAD

**Issue by Itsmehzoya** [rhunk/SnapEnhance#528]
### Description

It would be great if we could add or change emojis.🥹💗
Like honistagram 👉🏻👈🏻
  
I want iOS emojis.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment]
https://github.com/Keinta15/Magisk-iOS-Emoji

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/159
