### ISSUE TITLE
Safetynet check

### ISSUE THREAD

**Issue by EmanuelQeryo** [rhunk/SnapEnhance#530]
### Description

Hi I just wanted to know If I use snapenhance, does snapchat still use a safetynet check?

### Agreement

- [x] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment]
@EmanuelQeryo 

They use:
https://developer.android.com/google/play/integrity
https://developer.android.com/privacy-and-security/security-key-attestation

Safetynet is obsolete

![image](https://github.com/rhunk/SnapEnhance/assets/132447890/e31a3432-398b-416d-933b-b976e60db154)
