### ISSUE TITLE
feat: Blocking People in Single Click

### ISSUE THREAD

**Issue by Kittyxox** [rhunk/SnapEnhance#531]
### Description

Hi, First of all, this module is amazing, I've been using it since a month. Really awesome.
Just few features in my mind.
Currently to block people / Remove people in snapchat, i have to go to their profile and manage friendship, then block. It's not user friendly if i want to block 20 people quickly.
Can you add this feature?

Another feature in my mind is that, Send Fake Snaps as live snap.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Already implemented in https://github.com/rhunk/SnapEnhance/commit/3b0b44fcd44fa67e7a7eacc5c61a003975230191

**Comment by Kittyxox** [comment]
@rhunk , i dont see the option in snap enhance settings.

**Comment by rhunk** [comment]
It's implemented in v2.0.0 not in v1.x.x, go into SnapEnhance > click the settings gear > Bulk Messaging Action

**Comment by Kittyxox** [comment]
@rhunk Great, didn't know that it was in beta apk, just found it.
Btw bro, I am a female python developer and want to make sure amazing apps like this, what should i learn first?
any tips from u?
I am inspired by ur work.
