### ISSUE TITLE
Inspired by your work, Need to start my career as an android dev

### ISSUE THREAD

**Issue by Kittyxox** [rhunk/SnapEnhance#532]
### Description

Hey, Idk where to contact you. 
Actually I am 19 years old, want to make such amazing android app like yours.
Where do i start first?
Java or kotlin?

I am coming from Python Background, python doesn't have much library support for android apps.
Can i have your telegram? or mail to contact and discuss more?

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
No, sorry. There are tons of learning resources online.
