### ISSUE TITLE
feat: Replace snapchat camera with custom image/video

### ISSUE THREAD

**Issue by Kittyxox** [rhunk/SnapEnhance#533]
### Description

Hey , this is very important feature and most people will def like this.
Let me explain :
Whenever the user opens his snapchat, there should be an option to change snapchat internal camera to custom pic or video (and the custom pic or video - should have the option to resize according to snapchat camera size )
While video calling, it should show the custom video.

Is it possible to implement?

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
I don't see the point of doing this, but you can always try to implement it via the script engine
