### ISSUE TITLE
bug: App Crash

### ISSUE THREAD

**Issue by f4mlit** [rhunk/SnapEnhance#534]
### Description

A few times a day, the app crashes with the message "manager died" on the bottom of the screen. It only fixes when I go back into LSPatch and optimize the app. I believe this started when I installed Android 14 on my phone, but I'm not sure
This crash only happens when I try to open the app, not while I use it. 

### Reproduction steps

1. Open snapchat
4. See error.

### Snapchat Version

12.60.0.58

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
Logs?
