### ISSUE TITLE
bug: Banned from logging in temporarily

### ISSUE THREAD

**Issue by devgaharwar** [rhunk/SnapEnhance#535]
### Description

I've been using the latest version of SnapEnhance for quite a while, with suggested and tested version of Snapchat. But today I started getting this error message saying "Due to repeated failed attempts or other unusual activity, your access to Snapchat is temporarily disabled." I tried installing the Snapchat from play store and that works fine on the same device. But the moment I switch to SnapEnhance version, I keep getting this error. 
![Screenshot_20231228_124700_Snapchat](https://github.com/rhunk/SnapEnhance/assets/69291392/c9ff2687-c7ad-4c4a-9391-ba45c1bc4ac5)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.57.0.55

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/516
