### ISSUE TITLE
bug: Suspend Location Updates doesn't seem to work

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#536]
### Description

I enabled suspend location updates, yet my friends still see my proper last seen. Am I understanding the function incorrectly?
Also, how can I use unsaveable chats?

### Reproduction steps

1. Go to map
2. Enable suspend location updates 
3. Wait 10 mins
4. Friend sees proper last seen instead of "10 mins ago"

### Snapchat Version

12.65.0.38

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
You must quit the map tab for changes to take effect.

**Comment by CompuGenius** [comment]
> You must quit the map tab for changes to take effect.

What do you mean quit the map tab? I'm not STAYING in the map, if that's what you mean.
