### ISSUE TITLE
feat: automated snap sender

### ISSUE THREAD

**Issue by dxdvostfr** [rhunk/SnapEnhance#537]
### Description

It would be great to have a feature that would automatically send snaps of the same picture/video indefinitely to a chosen contact/group. Doing these with our alt accounts would make snapscore farming much easier since doing this with autoclickers is unreliable.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/194
