### ISSUE TITLE
feat: Unsave Messages that were already saved by the other person 

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#538]
### Description

The addition of unsaveable messages is amazing, but is there theoretically a way to force unsave a message that the other person already saved, whether before this feature had been implemented or if I forgot to turn it on?
Just thinking out loud, definitely no rush or anything.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
no don't think so
