### ISSUE TITLE
feat: Disable Auto flipping

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#539]
### Description

Stop stories from automatically going to the next snap when it ends and have it loop until you tap to advance.

Sort of like unlimited snap view time but for stories

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/f1b0bc41f2410c2c72dd9c9a14f4d3b90fcf3e1b
