### ISSUE TITLE
feat: search in message logger history

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#540]
### Description

Add a search button next to the top right call buttons on groupchats and normal chats that lets you search through the chat message history, could be incorporated with the message logger db for even older search results

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by Tale316** [comment]
How do I use the message logger. My friends are still able to delete texts

**Comment by mo0ov** [comment]
Good idea

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/fe777ff1d8a1e0fcb9662c14d988ed321627382e
