### ISSUE TITLE
Feat: Ability to remove navigation bar buttons.

### ISSUE THREAD

**Issue by TheMoonld** [rhunk/SnapEnhance#541]
### Description

It would be nice to be able to remove the snap maps or spotlight page on the navigation bar. So instead of five buttons there could only be three. On the snap enhance setting you could enable or disable each button with a switch.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
The ui layout changes too often from one version to another, so it's impossible for me to create mappings that will remain functional in the future
