### ISSUE TITLE
bug: chat export doesn't show nickname

### ISSUE THREAD

**Issue by dovisp** [rhunk/SnapEnhance#545]
### Description

a simple, small problem - no username is shown.
latest ci build(ffd42de)

![Screenshot_20240101-123334_Browser](https://github.com/rhunk/SnapEnhance/assets/64722645/177de2a6-bd42-4021-a3f0-65756e26aabe)

### Reproduction steps

1. Export chats.
2. Scroll down to first message.
3. See problem.

### Snapchat Version

12.65.0.38

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
@dovisp Can you check whether the author of the message is a member of the conversation?

**Comment by dovisp** [comment]
it's a dm, so yes they are a member of the conversation.

**Comment by rhunk** [comment]
Go to SnapEnhance app > settings gear > clean cache and try again

**Comment by dovisp** [comment]
sadly, it is still the same

**Comment by rhunk** [comment]
@dovisp please DM admins in the telegram group chat and give the logcat and all the necessary information which they will then be forwarded to me

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/477b13d3eb9767cc53d67f2be87b8427ba7fbf5e
