### ISSUE TITLE
Question: How to export chats 

### ISSUE THREAD

**Issue by s-sarathb** [rhunk/SnapEnhance#546]
### Description

so i saw that there is a feature to export chat as HTML. but, how do i do that. i searched for this feature in snap-enchance settings but i couldn't find it. 

So how do i do it?

### Reproduction steps

1.Open Snapchat
2.open snap-enhance settings menu

### Snapchat Version

12.68.0.25 beta

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Open the SnapEnhance app > click on the settings gear at top right

**Comment by RebeLrusheR** [comment]
Unsubscribe

**Comment by s-sarathb** [comment]
where is rhe option to export?
![Screenshot_20240101-171608_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/88707943/3255ad11-a39d-444e-ae8e-445cecd8650b)

**Comment by rhunk** [comment]
@s-sarathb I recommend using version 2.0
You can download it [here](https://t.me/snapenhance_ci)
