### ISSUE TITLE
feature request: Sorting option for exporting chats

### ISSUE THREAD

**Issue by s-sarathb** [rhunk/SnapEnhance#547]
### **what feature?:-**

while i export my chats from snap. i noticed that the chat sorting is from newest to oldest. i mean that newest appear at top and oldest at the bottom and there is no option for changing it. so it would be nice if u add that option for sorting chats

### **what i expect to add in chat export dialogue:-**

Sorting:-

Option 1:- newest to oldest
option 2:- oldest to newest

Thanks!!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/ebee8f2ef85d238355483917766ccbf496a11e14
However, this only works on HTML exports for optimization reasons

**Comment by s-sarathb** [comment]
okay add it for html alone
