### ISSUE TITLE
feat: Detect who unfriended and blocked you

### ISSUE THREAD

**Issue by CanerKaraca23** [rhunk/SnapEnhance#548]
### Description

Automatically detect and log who has unfriended and blocked you, and send a notification.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/275

**Comment by CanerKaraca23** [comment]
> #275

Isn't it's different? It's related to friend score i think.

**Comment by rhunk** [comment]
@CanerKaraca23 I just mentioned this issue on the friend tracker because it will be part of the same feature.
