### ISSUE TITLE
Zoom Slider

### ISSUE THREAD

**Issue by cybr47** [rhunk/SnapEnhance#550]
### Description

Option to zoom using a slider instead of pinching in or out. 

I am using Pixel 7 Pro and Snapchat zoom is pure garbage on this. Zoom is weird. I pinch a bit and it goes to like 10x+. It's also clunky and not smooth at all. If possible, please make these improvements.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
I don't see the point of doing this. However, you can always do it through an external script with the necessary knowledge.
