### ISSUE TITLE
feat: SNAPS NUMBER

### ISSUE THREAD

**Issue by arbatash** [rhunk/SnapEnhance#551]
### Description

It would be nice to see how many snaps you have to open. Snapchat het capped at 99+ but I think that it might be helpful and also cool to see the exact number.

Keep up the good work!
![Screenshot_20240103-182610_Snapchat](https://github.com/rhunk/SnapEnhance/assets/11338187/07d3422f-fd0d-4cb0-87e0-4bba1a8eb8b7)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
If it's displayed this way, there isn't enough space to display it properly.
However, feel free to contribute by writing an external script or opening a pull request.
