### ISSUE TITLE
bug: Logged deleted messages cause chat to not scroll

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#552]
### Description

I'm not sure if this is actually fixable, but if a person deletes a message and I have Message Logger on, the chat scroll point (idk what else to call it) stays at that deleted message.
Is there a way this can be fixed?

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.65.0.38

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
I've spent a long time looking for it and I haven't found a fix. I don't think it's really disturbing though
