### ISSUE TITLE
Visibility Issues: Filters and 'Try Lens' Option Not Displaying in Sent Snaps

### ISSUE THREAD

**Issue by jerry-619** [rhunk/SnapEnhance#555]
### Description

When we send some snaps from the camera roll, the applied filter is not visible to the recipient. Additionally, the 'Try Lens' option is not visible.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.65.038

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/418
