### ISSUE TITLE
Hide From launcher

### ISSUE THREAD

**Issue by tahirjamil** [rhunk/SnapEnhance#556]
### Description

Please make a option to hide snapenchance from home and launcher like vanced microg, it will feel better cause lot of launcher shows both apps side to side.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
In version 2.0.0 SE is designed to be launched from the launcher to manage tasks or scripts

**Comment by CompuGenius** [comment]
> In version 2.0.0 SE is designed to be launched from the launcher to manage tasks or scripts

I actually have the app hidden using OneUI's hide app feature and if I want to access the interface, I can use the Settings button and Export.
