### ISSUE TITLE
feat: Community Story Unlocker

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#557]
### Description

If you're in a community such as a school you can only post onto the story for the grade youre in, the ability to post on other grade's stories would be cool

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
We don't have access to any communities so it'd be hard for us to develop something for it without being able to test anything

**Comment by CompuGenius** [comment]
> We don't have access to any communities so it'd be hard for us to develop something for it without being able to test anything

I have access to a school's community on two accounts, I can help test. Rhunk knows how to contact me.
