### ISSUE TITLE
Unsended snap disappears

### ISSUE THREAD

**Issue by Marek1807** [rhunk/SnapEnhance#558]
### Description

If you take a picture and then switch app or close the phone your unsended snap will disappear after opening snap again. This doesn't happen to normal Snapchat 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.67.0.24

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [x] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by authorisation** [comment]
This is not related to SnapEnhance
https://dontkillmyapp.com/
