### ISSUE TITLE
I have problems 

### ISSUE THREAD

**Issue by Alfredofj05** [rhunk/SnapEnhance#560]
### Description

Are this and the other project the same name?  because I feel that the other one gives me more problems.  This one works well for me.  But I don't know if they closed this project and now only the other one will be used.  since this has not had an update since October

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
We have no idea what you are talking about

**Comment by Alfredofj05** [comment]
I'm talking about the apk that they published in their telegram group.  since the functions everything is different from this
![Screenshot_20240107_183713_Telegram](https://github.com/rhunk/SnapEnhance/assets/120024722/1757b167-dfd6-4e86-bbf4-e6291c165e0a)

**Comment by sestuff** [comment]
> I'm talking about the apk that they published in their telegram group. since the functions everything is different from this ![Screenshot_20240107_183713_Telegram](https://private-user-images.githubusercontent.com/120024722/294789712-1757b167-dfd6-4e86-bbf4-e6291c165e0a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjgyODQsIm5iZiI6MTcwNDY2Nzk4NCwicGF0aCI6Ii8xMjAwMjQ3MjIvMjk0Nzg5NzEyLTE3NTdiMTY3LWRmZDYtNGU4Ni1iYmY0LWU2MjkxYzE2NWUwYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QyMjUzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZWQyYjI1YjA1NTAyMWM3ZGZlMmIzN2U4YjI5NzFmMTU4MTEzNWIzMjM3MDdkNGViNDhiMzc5OGU1MTkxZTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UctbR4uYB2f0GS_HrwgWqQ88kLwD3o77wqN4EUqM8iQ)

It's the same thing, but the CI builds are v2. the latest github release is v1.2.5. You can also find the [latest](https://github.com/rhunk/SnapEnhance/actions/runs/7404141820) v2 CI builds in the [action run logs](https://github.com/rhunk/SnapEnhance/actions).
