### ISSUE TITLE
feat: TITLE Hide typing Status 

### ISSUE THREAD

**Issue by IamNickerson** [rhunk/SnapEnhance#561]
### Description

When the User is online and active in the chat when enabled the feature the other user cannot identify if he is typing or not. This was also a feature provided in one Betterdiscord plugin called Hide typing Status.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by CompuGenius** [comment]
Uh...that's already a feature lol

**Comment by IamNickerson** [comment]
oh damn ok
