### ISSUE TITLE
bug: Download folder not selecting snapenhance v2

### ISSUE THREAD

**Issue by nikhilan21** [rhunk/SnapEnhance#563]
### Description

the saving folder is not getting selected in the snapenhance v2, I tried with v1 there is the same issue and same with v 2 also 

### Reproduction steps

check to the video attached[

https://github.com/rhunk/SnapEnhance/assets/156161641/d6107c4c-23fe-4fd6-9540-a4a7c0b491c0

### Snapchat Version

snapenhance-2.0.0-armv8-83fd108.apk

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [x] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by CompuGenius** [comment]
I had this issue if using the app with Dual Messenger, but it works if you select the folder with the main profile. Unfortunately this means you can't use two different folders.

**Comment by nikhilan21** [comment]
No I'm using only a single profile

**Comment by Batman313v** [comment]
I am having a similar but different issue. I may need to open a new thread but. I can select the folder but it still saves media to my "Camera" folder instead like it didn't register that a different folder was selected.

**Comment by RevealedSoulEven** [comment]
You can try remove the spaces in the folder name

**Comment by nikhilan21** [comment]
Telegram group is there for snapenhance 2
