### ISSUE TITLE
Collection contains no element matching the predicate error after patching 

### ISSUE THREAD

**Issue by lostinmusic222** [rhunk/SnapEnhance#564]
### Description

I'm using the latest snapchat beta and I keep getting this error after patching my android 14 device. (Samsung galaxy z flip 4) I have repatched, Uninstalled and reinstalled snapchat, and cleared the cache and nothing has worked. 

### Reproduction steps

1. Open snapenhance
2. Generate mappings
3. The error should show 

### Snapchat Version

12.70.0.24 beta

### Agreement

- [ ] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by lostinmusic222** [comment]
![Screenshot_20240111_000634_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/26557725/43a0bbac-7528-4743-9484-ac83d8d44a72)

**Comment by rhunk** [comment]
Use a stable version of snapchat because beta version mappings change quite often
