### ISSUE TITLE
bug: snapchat crashes when trying download snap

### ISSUE THREAD

**Issue by bidenfelloffhisbike** [rhunk/SnapEnhance#566]
### Description

When trying to save a snap to gallery using the "download media" feature on a snap or story, snapchat just crashes and doesn't end up doing anything else. The snap is left on read/viewed when you re-open snapchat, but nothing is saved to gallery. I am using the latest version of snapchat, and snapenhance. Video provided here: 

https://github.com/rhunk/SnapEnhance/assets/114791284/e48b32a4-63b2-4550-bbaa-6fe927126f77

### Reproduction steps

1. Go to an `unopened snap or person's story`
2. Click on `the snap`
3. Click on `the three dots at the top right`
4. Click on `Download Media`
5. See crash and get kicked out to home screen.

### Snapchat Version

com.snapchat.android_12.
68.0.26-108172_minAPI2
1(arm64-v8a,armeabi-v7a)

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Refresh mappings/clear SE app data should fix the issue
I recommend you use latest v2.0.0 build as v1 is no longer updated

**Comment by bidenfelloffhisbike** [comment]
Ok thx

**Comment by rhunk** [comment]
@bidenfelloffhisbike https://t.me/snapenhance_ci
