### ISSUE TITLE
Persistent half-swipe indicator

### ISSUE THREAD

**Issue by bobbleheadhobo** [rhunk/SnapEnhance#567]
### Description

This is almost and enhancment to the peek a peek feature. Where the 👀 indicator becomes persistent once a user half-swipes a message. Unlike the current functionality where the indicator disappears once the user stops peeking. So you can always see if someone half swiped your message from the moment you sent it.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bobbleheadhobo** [comment]
It only send a notification that someone half swiped if they do it when I am on the chat screen. It doesn't notify me if I am on any other screen like the camera or if the app is closed. Is there a fix for this?

**Comment by rhunk** [comment]
@bobbleheadhobo https://github.com/rhunk/SnapEnhance/issues/405
