### ISSUE TITLE
Custom Color Notifications

### ISSUE THREAD

**Issue by PerfeCtion2901** [rhunk/SnapEnhance#568]
### Description

I'd like to be able to change the colors of notification icons and texts on Snapchat. Instead of just red for snaps and blue for chats, we could pick our own colors. This way, Snapchat notifications can be more personal and fun, with your choice of colors like purple for snaps or orange for chats

I love snapenhance but it would be awesome if we could change more colors. For example my whole phone theme is purple and id love to have snapchat like that too.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by PerfeCtion2901** [comment]
I would pay for this honestly. A lot even

**Comment by rhunk** [comment]
I have no interest in doing this and you're probably the only one who needs it, nevertheless you can always make a pull request or create your own script via the scripting engine. The documentation can be found [here](https://github.com/SnapEnhance/docs)

**Comment by bocajthomas** [comment]
> I would pay for this honestly. A lot even

If you have a samsung use " goodlock  " and download theme park with in goodlock 

Open goodlock -> find themepark -> open themepark -> go to quick panel-> add new -> customs how u like then save -> apply 

Make sure you have the colour pallet off If your on OneUI6
