### ISSUE TITLE
hide story section doesnt work

### ISSUE THREAD

**Issue by McFaul4** [rhunk/SnapEnhance#569]
### Description

The "hide story section" option doesnt work with "following" and "for you" since the last update.
Let me now, if you need aditional information!

### Reproduction steps

1. enable these 2 settings
2. go to the story page
3. the sections wont be hidden

### Snapchat Version

12.65.0.38

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
SnapEnhance version?

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/5d8cdc3cfce8408ade7d2abbc885659383d19c2a

**Comment by McFaul4** [comment]
Sorry, i havent got a notification, when you asked me about my snapenhance version. it's 1.2.5. any updates, since you closed the issue?

**Comment by rhunk** [comment]
@McFaul4 you can try the latest ci build [here](https://t.me/snapenhance_ci)

**Comment by McFaul4** [comment]
on v. 1.2.6 and snapchat v. 12.71.0.30 the feature still doesn't work. let me know if you need any logs?

**Comment by rhunk** [comment]
@McFaul4 SE versions 1.x.x only receive important stability updates. However, if you want the latest features and fixes, you can download beta versions here: https://t.me/snapenhance_ci
