### ISSUE TITLE
feat: Individual camera resolution and frame rate

### ISSUE THREAD

**Issue by Brightburn07** [rhunk/SnapEnhance#570]
### Description

A feature that would allow you to change the frame rate and resolution individually for each different camera. When I change the camera frame rate it reduces resolution of the front camera and if I don't, the frame rate for both the cameras is really low. I change the frame rate to 60Hz from disabled and I have a Pixel 6 which supports 60Hz. When I change the resolution to a value supported by my camera it works for the back camera but when I change to the front camera it causes the app the crash and it doesn't open after until I disable the custom resolution feature. Would it be possible to add a feature like this. It would be really appreciated. Thank you

Device:Pixel 6 on stock Android 14, Non-rooted

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/1f4eb18aa832630ee88951cad1d50d259c4228f2
https://github.com/rhunk/SnapEnhance/commit/2905fe6e2dd21fba1d494e695e0921a15660e50c

**Comment by Brightburn07** [comment]
I meant to be able to change the resolution for each camera, just like the frame rate feature I suggested above, rather than disable them since I would like to use both the front and back cameras on the phone
