### ISSUE TITLE
Can't download snaps

### ISSUE THREAD

**Issue by thekalangatangadvocacy** [rhunk/SnapEnhance#571]
### Description

Every time I try to download a snap, I get a java.NullPointError toast, and a failed download appears in the Snapenhanced APK

Using armv8 version

### Reproduction steps

1. Attempt to download a snap
2. See error

### Snapchat Version

12.68.0.26

### SnapEnhance Version

1.2.5

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/441
