### ISSUE TITLE
feat: Auto add friends from Quick Add

### ISSUE THREAD

**Issue by Kittyxox** [rhunk/SnapEnhance#574]
### Description

Hey, i am not sure if this already implemented like whenever there is new quick add, it should auto add them.
If possible it can add only females but not males.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
no automation will be implemented for adding friends as this may result in bans. As always, feel free to create your own scripts via the script engine

**Comment by Kittyxox** [comment]
i can pay for it if you can do it.

**Comment by rhunk** [comment]
@Kittyxox Sorry, I don't get paid to do an opensource project that I do for fun but you can always make donations if you want
