### ISSUE TITLE
feat: Stealth Mode Icon 

### ISSUE THREAD

**Issue by theycallmemonkey** [rhunk/SnapEnhance#575]
### Description

Having an icon in the friend feed where u could see  what friend u have the stealth mode option enabled with 
Idk like a tiny 👻 icon somewhere next to their name or anything that can point it out

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/93490c323c7f39a0945f3aa1b325c0c76d484292
