### ISSUE TITLE
Downloading a message with multiple photos only downloads the first one.

### ISSUE THREAD

**Issue by fakepepsilol** [rhunk/SnapEnhance#576]
### Description

I have auto download on, and i received a message containing two images. I clicked on it, and it only downloaded the clicked one, and didn't download the second one. I got around it by enabling duplicate downloads.

### Reproduction steps

1. Go to `chats`
2. Click on a message containing more than one image.
3. Only the first image clicked is downloaded, the rest are "duplicates".

### Snapchat Version

12.68.0.26 (108172)

### SnapEnhance Version

1.2.5

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Hey this bug has been fixed in v2.0.0, which is currently under development. You can download the latest build [here](https://t.me/snapenhance_ci)
