### ISSUE TITLE
feat: Message Logger DB Viewer

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#580]
### Description

Have a tab in the snapenhance app to view a list view styled representation of the message logger db, it could be sorted by user. You could click on a user and open either their logged stories or messages. Its different than using the social tab because it would be the "raw" data but in a slightly friendlier ui

It would also have the option to look through logged stories from any communities you've joined

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/540
