### ISSUE TITLE
feat: persistent settings across logouts

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#583]
### Description

Snapchat resets settings when logging out and logging back in, even to the same account.
You already added an option to force Dark Mode and Main Page, but would you be able to add a way to "export" snapchat's settings so that it'll stay persistent?
In particular, I always turn off Wake Screen for notifications and it's really annoying when I forget to turn it off.
Thank you!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by melbarouzi** [comment]
> ### Description
> Snapchat resets settings when logging out and logging back in, even to the same account. You already added an option to force Dark Mode and Main Page, but would you be able to add a way to "export" snapchat's settings so that it'll stay persistent? In particular, I always turn off Wake Screen for notifications and it's really annoying when I forget to turn it off. Thank you!
> 
> ### Agreement
> * [x]  There is no issue already suggesting my feature.
I think this option is already exist in snapenhance

**Comment by CompuGenius** [comment]
>  I think this option is already exist in snapenhance

If so, where?

**Comment by melbarouzi** [comment]
> > I think this option is already exist in snapenhance
> 
> If so, where?

Go to the features  tab  > 3 dot and voila export , import and reset are there

**Comment by CompuGenius** [comment]
> Go to the features tab > 3 dot and voila export , import and reset are there

...that's for exporting SnapEnhance's settings. Not Snapchat's.

**Comment by rhunk** [comment]
Go to Android settings > Apps > Special App Access > Turn screen on
