### ISSUE TITLE
bug: Hide Streak Restore Button from Friend Feed doesn't work

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#584]
### Description

^

### Reproduction steps

1. Enable Hide Streak Restore Button from Friend Feed
2. Lose a streak
3. See button in Friend Feed

### Snapchat Version

12.68.0.26

### SnapEnhance Version

Latest CI build

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/8e36425a369a0fd6d621c5f71d6b2e1fddf59e2b

**Comment by CompuGenius** [comment]
I created a build with this commit, yet it still doesn't hide the button.
![Screenshot_20240117_120328_Snapchat](https://github.com/rhunk/SnapEnhance/assets/39806174/a4b3ed9a-8959-479c-b547-238a445297a9)
