### ISSUE TITLE
bug: Hiding Friends from Friends Feed only works sometimes

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#585]
### Description

I'm not exactly sure a common cause, but it seems to only work when I only just sign after being logged out, if I have only a few friends and I swipe down to refresh, or on occasional app starts.
I'm not sure exactly how this feature works, hopefully these "logs" help direct you.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.68.0.26

### SnapEnhance Version

Latest CI build

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [x] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/83ce06d50d552a5d054a5bf09fadb18a75ccc18d
