### ISSUE TITLE
Crash with specific config on startup

### ISSUE THREAD

**Issue by L3-N0X** [rhunk/SnapEnhance#588]
### Description

I'm currently experiencing a crash when I start Snapchat. When reseting the config, snapchat starts again. In the logs of the app there are no hints what could cause the crash. Clearing Cache and Stopping the Application doesn't do anything 

### Reproduction steps

1. Apply my config
[snapEnhaceMain#1.json](https://github.com/rhunk/SnapEnhance/files/13969137/snapEnhaceMain.1.json)
2. Open Snapchat (Maybe restart a couple times or so, after I reseted and reapplied my configs, the app worked a few minutes and then I opened it again 1h later and it crashes again.)
3. [Use German translation] and newest CI Build from Telegram (armv8)

### Logs

```markdown
(Nothing Special, Script folder fails to load, but also does so when config is reset)
```

### Snapchat Version

Version 12.69.0.26

### SnapEnhance Version

2.0.0 newest CI Build (12.01.2024)

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/fe9164b423cbaa4ff6af6cb3e9d89b4d83ed0b5e
