### ISSUE TITLE
Turning spoofing location when coming home feat: TITLE

### ISSUE THREAD

**Issue by Sitolam** [rhunk/SnapEnhance#591]
### Description

It would be great that I can configure when I come home that my Snapchat location is spoofed, so that people don't know where I exactly live.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
A feature that could probably be done using the Scripting Engine. I don't see the point of this.

**Comment by Sitolam** [comment]
> A feature that could probably be done using the Scripting Engine. I don't see the point of this.

I don't understand, what is a Scripting Engine and are privacy concerns not a big point?
