### ISSUE TITLE
Turn off Call Confirmation Dialog when clicking the Resume button in chat

### ISSUE THREAD

**Issue by CompuGenius** [rhunk/SnapEnhance#592]
### Description

When a call is in progress, the resume button in the app bar when inside the chat caused a confirmation dialog as well.

### Reproduction steps

1. Enable Call Confirmation Dialog
2. Start call
3. Go into chat of call
4. Click Resume button in app bar
5. See issue.

### Snapchat Version

Latest

### SnapEnhance Version

Latest CI build

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by CompuGenius** [comment]
Uh. @authorisation you're wrong lol

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/07d1760a73468a4c6b4958a4b2d57932f4bd8ead
