### ISSUE TITLE
Fake Flames

### ISSUE THREAD

**Issue by PerfeCtion2901** [rhunk/SnapEnhance#593]
### Description

A feature that allows you to fake Flames (clientsided of course) in your app. it would just Print the Flame emoji and a number of choice next to someone.

for example I just choose someone and type 999 flames and if someone sees my phone or on Screenshots it looks real

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
You could do this with the Scripting Engine, we have no interest in making something like this.

**Comment by PerfeCtion2901** [comment]
> You could do this with the Scripting Engine, we have no interest in making something like this.

what is the reason for this feature suggestion??? on every fucking Suggestion u say "you can make that yourself. we have no interest in that".

I can't. I fucking can't. im using snapenhance and not my own shit bcs I can't. if there was something better that is paid with more Features I pay but I dont get ur fucking Methode ngl

**Comment by rhunk** [comment]
@PerfeCtion2901 SnapEnhance is an opensource project that I'm working on in my spare time. As I'm the only person working on the project and a volunteer, the suggestions remain suggestions, so it's up to us to choose which are possible to reproduce and which are worth the effort.
As the source code is available, feel free to open pull requests to introduce new features, we'd be delighted to integrate them.

**Comment by authorisation** [comment]
^^ :)
