### ISSUE TITLE
Mutual friends and online detection

### ISSUE THREAD

**Issue by jerry-619** [rhunk/SnapEnhance#594]
### Description

Add an option to view the mutual friends of someone who added me.

2. Add an option to know who is online right now.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment]
Seems Similar to https://github.com/rhunk/SnapEnhance/issues/275

**Comment by rhunk** [comment]
Duplicate of https://github.com/rhunk/SnapEnhance/issues/527
