### ISSUE TITLE
Missing interval in streaks reminder

### ISSUE THREAD

**Issue by xahem** [rhunk/SnapEnhance#596]
### Description

In the streaks reminder section there is an option called Remaining Time, but it is unclear what interval it is. Since the option above it has the interval hours it can be assumed it's hours, but it can be confusing.

### Reproduction steps

1. Go to Snapenhance settings
2. Press on Streaks Reminder
![Screenshot_20240120-160503](https://github.com/rhunk/SnapEnhance/assets/97387346/d94c9989-f308-478e-b2cf-94bd4d0d7cdc)

### Snapchat Version

12.69.0.26

### SnapEnhance Version

2.0 beta build

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
05a495d
