### ISSUE TITLE
Discover feed title incorrect theme

### ISSUE THREAD

**Issue by xahem** [rhunk/SnapEnhance#598]
### Description

When disabling spotlight, the discover page that replaces it has a white bar even though snapchat is in dark mode.
![Screenshot_20240121-183757~2](https://github.com/rhunk/SnapEnhance/assets/97387346/a8177d92-8b34-49eb-b790-a4a155adbed9)

### Reproduction steps

1. Go to Snapenhance settings
2. Click on User Interface
3. Scroll down and press "Disable spotlight"
4. Open snapchat and set dark mode
5. Go to the discover page that replaced spotlight
6. Check the title bar color
![Screenshot_20240121-183757~2](https://github.com/rhunk/SnapEnhance/assets/97387346/da3291d5-d2a9-4b35-aaa3-f14f484c9319)

### Snapchat Version

12.69.0.26

### SnapEnhance Version

Snapenhance 2 beta

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/111
