### ISSUE TITLE
feat: Opera download button for new story layout

### ISSUE THREAD

**Issue by TheTrueDonDotta** [rhunk/SnapEnhance#603]
### Description

snapchat have updated the story ui only in the stories section and I'd like to have the opera download button back. example shown in screenshot as im someone who seems to get Snapchat updates earlier than others.

![Screenshot_20240123_013923_Snapchat.png](https://github.com/rhunk/SnapEnhance/assets/144651375/6e879d40-260f-4127-97f4-42f18a1e081f)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Can't fix since composer is now used in story viewer
