### ISSUE TITLE
feat: Recents Removal Feature

### ISSUE THREAD

**Issue by TheTrueDonDotta** [rhunk/SnapEnhance#604]
### Description

I am suggesting a feature to remove/stop the recents feature when you scroll up to see your camera roll in the camera section. it literally just shows what you recently saved in your camera roll as a story 🤣 useless feature. screenrecording attached below refering to the feature.

https://github.com/rhunk/SnapEnhance/assets/144651375/4ede6616-e5df-4a2f-b056-b1b721b3fa49

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/eb3ea2675b06cbd0f53361349b7a108c49e0643c
