### ISSUE TITLE
bug: Information Preview friendship 

### ISSUE THREAD

**Issue by TheTrueDonDotta** [rhunk/SnapEnhance#605]
### Description

i notice when you try preview the information on someone you havent added it'll say  "Friendship: mutual" despite you clearly not having them added.
screenshot provided below of this.

![Screenshot_20240123_020522_Snapchat](https://github.com/rhunk/SnapEnhance/assets/144651375/93e460e7-a44d-4444-8f80-87687dbc59d0)

### Reproduction steps

1. Search someone you havent got added.
2. Long press and click preview
3. Press 'profile info'
4. See error.

### Snapchat Version

12.70.0.34

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/234fe2c2aa0ddfee086d8d9a5aa9dcc0eb2ce9b2
