### ISSUE TITLE
feat: Local message hider

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#608]
### Description

Could have a context menu button for individual messages in chats to hide and unhide them, they would only be hidden if the selected chat was whitelisted.

This is different from the already implemented chat hider as it hides individual messages you select and not the whole chat.

When marking messages to be hidden they would be hidden the next time chat is opened up, acting somewhat like the "delete chats after viewing" mode in normal snapchat

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/SnapEnhance/docs
