### ISSUE TITLE
bug: - Snaps sent from gallery can't be saved by user

### ISSUE THREAD

**Issue by RevealedSoulEven** [rhunk/SnapEnhance#61]
### Description

I literally trues sending from cameraroll, in-chat gallery menu, but still the user can't save snaps in chat. Although they can save the ones sent from snapchat camera as normal snaps

### Reproduction steps

```bash
...
```

### Snapchat Version

12.37.0.43

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by tycoon420** [comment]
is this issue fixed in the debug version???

**Comment by RevealedSoulEven** [comment]
Not yet

**Comment by RevealedSoulEven** [comment]
not yet. Still waiting

**Comment by authorisation** [comment]
This will require a lot of work and we think it's not that important as of right now, therefore this will be moved to the low priority list

**Comment by RevealedSoulEven** [comment]
brooooo

**Comment by kumarasmit** [comment]
Sorry if this seems rude, but can we move this up the priority list a bit? ಥ_ಥ

**Comment by RevealedSoulEven** [comment]
+1

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/d7bdfa7cddb1922b099de2ba8357eb7ee87cd012

**Comment by rhunk** [comment]
@jerry-619 use v2.0.0 with Native Hooks enabled

**Comment by rhunk** [comment]
@jerry-619 https://t.me/snapenhance_ci
