### ISSUE TITLE
Social bug

### ISSUE THREAD

**Issue by RSR1337** [rhunk/SnapEnhance#610]
### Description

Thanks for the latest update, But there is an issue that you cannot add selected friends or groups and still empty 

### Reproduction steps

Go to social and try add an friend or group 

### Snapchat Version

12.70.0.34

### SnapEnhance Version

2.0 Latest dev build eb3ea26

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/5563418d79596e7185a47fb51f65f14f9828d8d2
