### ISSUE TITLE
Bug: no Snap preview

### ISSUE THREAD

**Issue by TheTrueDonDotta** [rhunk/SnapEnhance#611]
### Description

there seems to be no little snap preview beside the snap when the feature is turned on, not sure if this is because Snapchat are updating things. screenshots provided below.

![Screenshot_20240123_210434_Snapchat](https://github.com/rhunk/SnapEnhance/assets/144651375/fa069910-a8b3-4644-b305-635aaeaafeef)
![Screenshot_20240123_210355_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/144651375/3e360da2-b588-4f15-9752-b311ae886287)

### Reproduction steps

1. Open a chat with a friend that has sent you a snap
2. See error.

### Snapchat Version

12.70.0.34

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
This has been fixed in newer beta build, if it doesn't work try to refresh mappings
