### ISSUE TITLE
feat: screenshot notification spam

### ISSUE THREAD

**Issue by Felting** [rhunk/SnapEnhance#613]
### Description

A button over the chat that sends 100 (preferably customisable) screenshot notifications.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment]
@Felting Bad idea as users from wicked get banned with this. Because it spams snapchats backend

**Comment by rhunk** [comment]
Same as https://github.com/rhunk/SnapEnhance/issues/581#issuecomment-1892672604
