### ISSUE TITLE
Stopped working after updating Snapchat

### ISSUE THREAD

**Issue by aintyourcupoftea** [rhunk/SnapEnhance#618]
### Description

It used to work perfectly fine and I updated my Snapchat to latest version from Play Store and Snap Enhance Stopped working.

The below is the screenshot of the error.
![Screenshot_20240126-010718](https://github.com/rhunk/SnapEnhance/assets/79439692/c81c2bdb-a48f-48f0-9d70-46b8ff5ea26a)

I tried clearing data and logging in again but it didn't solve the issue.

### Reproduction steps

1. Go to Play Store and Update Snapchat 
2. Force Stop and reopen Snapchat.

### Snapchat Version

12.70.0.34

### SnapEnhance Version

1.2.5

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by CompuGenius** [comment]
> ### Agreement
> 
>     * [x]  This is not a bug regarding Snapchat+.

Bruh 😂

**Comment by rhunk** [comment]
@aintyourcupoftea use SE [v2.0.0](https://t.me/snapenhance_ci)
