### ISSUE TITLE
feat: See WHO rewatches your story, not just the count

### ISSUE THREAD

**Issue by mkwiimaster7** [rhunk/SnapEnhance#619]
### Description

I'm like 65% sure this is probably impossible, but will suggest nonetheless 

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
You are correct

**Comment by RevealedSoulEven** [comment]
Bro let it be whoever watches it. It doesn't matters🥲
(Meanwhile I need it too but that's not possible)
