### ISSUE TITLE
bug: weird number besides streak 

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#62]
### Description

After the streak number (which is 5 in this case) it shows another number (36) and I have absolutely no clue what that could stand for?
![Screenshot_20230613-211523](https://github.com/rhunk/SnapEnhance/assets/12681440/92158c1a-f36a-402f-8d41-71fe3e6321f1)

Tried a reinstall but doesnt help.
Happens on latest SnapEnhance 1.0.2

### Reproduction steps

```bash
See above
```

### Snapchat Version

12.39.0.38 Beta

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by RevealedSoulEven** [comment]
I think you got it 😂
