### ISSUE TITLE
SnapchatPlus

### ISSUE THREAD

**Issue by hakemdamer222** [rhunk/SnapEnhance#621]
### Description

I'am facing a bug called "failed to init SnapchatPlus feature"

### Reproduction steps

1. Just when you open snapchat
2. With SnapchatPlus feature turned on
3. Its gonna show this message

### Snapchat Version

12.70.0.34

### SnapEnhance Version

1.2.5

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
Duplicate of https://github.com/rhunk/SnapEnhance/issues/618
