### ISSUE TITLE
feat: Gallery adjustable image / video size

### ISSUE THREAD

**Issue by Trozzi** [rhunk/SnapEnhance#622]
### Description

Some videos and images are not in the same size that Snapchats send as. Having an option to size to the Snapchat bezels might be a nice option to have.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
After some research, I've noticed that this feature will require a lot of work and won't be useful for most users. You can always use the built-in crop tool though
