### ISSUE TITLE
bug: Bitmoji Bug

### ISSUE THREAD

**Issue by RSR1337** [rhunk/SnapEnhance#626]
### Description

When the feature Native Hooks is enabled, Bitmoji is forced to disable, even if the option Disable Bitmoji is not enabled 

### Reproduction steps

Go to Experimental then enable Native Hooks 

### Snapchat Version

12.70.0.34

### SnapEnhance Version

2.0 Latest dev build 3b0ed89

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
It's related to bootstrap override which is unstable
