### ISSUE TITLE
My account keeps doing this reset thing.

### ISSUE THREAD

**Issue by agarfa433** [rhunk/SnapEnhance#627]
### Description

So this is like the third time it's done it in about 4 months, but I'll go back into the app, and it like immediately closes so I swipe it out and open it up again but this time it works, except all my private storys are deleted, and Im not in like my schools shared story and when I try to rejoin it I can't. 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.57.0.55

### SnapEnhance Version

1.2.5

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by sestuff** [comment]
Version 1.2.5 is no longer supported and/or updated try updating to v2 and then get help if it still does it.

**Comment by authorisation** [comment]
v1 will get a hotfix update soon

**Comment by authorisation** [comment]
Try 1.2.6, let me know if it works.

**Comment by authorisation** [comment]
Closed due to inactivity
