### ISSUE TITLE
bug: Notification blocklist doesn't work properly

### ISSUE THREAD

**Issue by NMBlanco** [rhunk/SnapEnhance#63]
### Description

I noticed when I block the typing notification within the notification blocklist menu, my phone still lights up when someone is typing. It just doesn't show the notification until the person sent the message. 
I think that's somewhat annoying, always getting a blank notification when someone is typing. 
This wasn't an issue with SnapMod back then iirc.

SnapEnhance v 1.0.2 

### Reproduction steps

```bash
Enable "block typing notification"
Let someone type a message to you
```

### Snapchat Version

12.39.0.38 Beta

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by RevealedSoulEven** [comment]
Yaaa even sometimes it doesn't shows message content in it and shows "Your girlfriend sent a chat"

**Comment by rhunk** [comment]
This bug seems to be already fixed
@NMBlanco can you try the latest ci build to check if this is the case?

**Comment by NMBlanco** [comment]
> This bug seems to be already fixed @NMBlanco can you try the latest ci build to check if this is the case?

Sorry for the late response, but no, it's still broken for me on the latest CI build along with Snapchat 12.41.0.37 Beta.
My phone always lights up when someone is typing, just with no notification.

**Comment by NMBlanco** [comment]
@rhunk still doesn't seem to be fixed, just fyi.
Using latest Snapenhance Ci Build with 12.43.0.36 Beta

**Comment by rhunk** [comment]
Can you try the latest ci build and let me know whether it's fixed or not

**Comment by NMBlanco** [comment]
Yes its fixed now. Thank you
