### ISSUE TITLE
Where can I get a Snapchat app to work with SnapEnhance?

### ISSUE THREAD

**Issue by fileiraq** [rhunk/SnapEnhance#630]
### Description

Hi there,
I tried apkpure to download snapchat version, but didn't work in combination with SnapEnhance.

Where can I get the version that does work with SnapEnhance V 1.2.5?

Thank you so much 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.70.0.34

### SnapEnhance Version

1.2.5

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
This is not a support page.
