### ISSUE TITLE
Preview ➡️ Profile Info in quick add issue

### ISSUE THREAD

**Issue by Edward-Bakker** [rhunk/SnapEnhance#643]
### Description

I'm trying to preview someone's profile info in my quick add under add friends, but I am unable to open the preview menu which has the `Profile Info` button.

### Reproduction steps

1. Go to `Add Friends`
2. Long press on someone in `quick add`.
3. Press `preview`.
4. See error `No messages found`.
5. Does not open anything, causing the issue of not being able to open `Profile Info` through the preview.

### Snapchat Version

v12.70.0.34

### SnapEnhance Version

1.2.6 (latest debug from Telegram)

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
This is already fixed in v2.0.0
