### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by JorDead187** [rhunk/SnapEnhance#645]
### Description

I've been using SnapEnhance with Lspatch on a non rooted Galaxy S21 for 3 months and it's worked perfectly fine. But after I updated it yesterday I can't login to any account and get the message "Your access to Snapchat is disabled due to repeated failed login attempts or other suspicious activity." This happens on every version of Snapchat and SnapEnhance I use, new or old. I can login on any non patched Snapchat so I don't think it's an account problem. 

### Reproduction steps

1. Attempt to login or type anything in email and password box in patched app.
2. See error message.

### Snapchat Version

12.71.0.30 - 12.68.0.26

### SnapEnhance Version

2.0.0 - 1.2.4

### Agreement

- [x] This is not a bug regarding Snapchat+.
- [x] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by RevealedSoulEven** [comment]
Same with everyonr

**Comment by RevealedSoulEven** [comment]
Even without snapenhance too

**Comment by Anshu-Bijarnia** [comment]
Are you using custom rom or stock ?

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/637
