### ISSUE TITLE
[NOT WORKING] Unlimited Snap View Time

### ISSUE THREAD

**Issue by Hogor007** [rhunk/SnapEnhance#650]
### Description

Recently just like other non-root users, I have faced the login error issue, so I rollbacked to an old version apk, logged in, patched SE 1.2.5 on version 12.69 stable apk (from apkmirror) and have been using it as of January 30th.

While trying to download a snap that my friend sent, i encountered a toast notification saying:

```Failed to save to gallery```

```java.lang.NullpointerException```

After facing this problem I downloaded SE v1.2.6 from [Releases](https://github.com/rhunk/SnapEnhance/releases) and 12.70.0.34 Snapchat apk as instructed.

I force stopped the current app I have on my phone, opened LSpatch, selected the 12.70.0.34apk from storage, embedded SE 1.2.6, and then installed the app after patching.

After this I installed SE v1.2.6 apk. I didnt uninstall SE v1.2.5 so the v1.2.6 installed as an update I guess.

Then I opened snapchat app, it said "generating mappings" then restarted.
after that I started using the app as usual.
While using the app I noticed that the snaps that were sent with a limited timer are not being repeated in a loop. then i checked snaps sent by others, it's still the same issue. 

I'm using Xiaomi Mi A3, AOSPA custom rom android 13, non-rooted.

### Reproduction steps

1. Open  `SnapEnhance Settings`
2. Turn on `Unlimited Snap View Time`
3. Open `Snapchat app`
4. Try opening a snap with a timer.
5. Snaps that are sent with a timer aren't being played in a loop, instead, the next snap opens up. if there are no snaps, it just closes.

### Logs

```markdown
I do not know if there are ways to export logs, however I would add one if provided the steps.
```

### Snapchat Version

12.70.0.34

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Fixed in v2.0.0
