### ISSUE TITLE
Replay snap still getting sent

### ISSUE THREAD

**Issue by NotApex** [rhunk/SnapEnhance#651]
### Description

When prevent sending snap replayed is enabled the message still gets sent.

### Reproduction steps

1. Go to `SE Settings`
2. Click on `messaging`
3. Scroll down to `prevent message sending`
4. Enable `Snap Replay`.
5. Replay a snap
6. See error

### Snapchat Version

12.70.0.34

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Enable native hooks

**Comment by NotApex** [comment]
Native hooks is enabled

**Comment by rhunk** [comment]
@NotApex It works fine on latest version, perhaps you've chosen the wrong architecture?
