### ISSUE TITLE
SnapEnhance on... IOS? 😏

### ISSUE THREAD

**Issue by AliAlayat** [rhunk/SnapEnhance#652]
### Description

will SnapEnhance ever be a thing on IOS? I had a Samsung S23 for a while and used SnapEnhance for months, but recently "upgraded" (more like downgraded) to an iPhone. Also, is there a way to convert .APK to .IPA? That would be life saving.
Thanks for the great work team.
@oculv

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by CompuGenius** [comment]
> ### Description
> 
> will SnapEnhance ever be a thing on IOS? I had a Samsung S23 for a while and used SnapEnhance for months, but recently "upgraded" (more like downgraded) to an iPhone. Also, is there a way to convert .APK to .IPA? That would be life saving. Thanks for the great work team. @oculv
> ### Agreement
> 
>     * [x]  There is no issue already suggesting my feature.

Not even a tiny bit of a chance. iOS is extremely locked down besides the absolute nightmare it is to develop apps for it.

**Comment by rhunk** [comment]
No, snapenhance cannot be converted to IPA for iOS devices since Android and iOS are two different architectures.

**Comment by authorisation** [comment]
Maybe if I get a jailbreak and I’m in the mood for it, no guarantees though

**Comment by CompuGenius** [comment]
> Maybe if I get a jailbreak and I’m in the mood for it, no guarantees though

Even if you were to get a jailbreak, jailbreak is very different than root. Jailbreak opens up some parts of the system, but definitely does not give nearly as much access as root does with LSPosed.

**Comment by authorisation** [comment]
> > Maybe if I get a jailbreak and I’m in the mood for it, no guarantees though
> 
> Even if you were to get a jailbreak, jailbreak is very different than root. Jailbreak opens up some parts of the system, but definitely does not give nearly as much access as root does with LSPosed.

The only thing I'd really need is tweak injection and Xcode for comfort (which I don't have)

**Comment by CompuGenius** [comment]
> > > Maybe if I get a jailbreak and I’m in the mood for it, no guarantees though
> > 
> > 
> > Even if you were to get a jailbreak, jailbreak is very different than root. Jailbreak opens up some parts of the system, but definitely does not give nearly as much access as root does with LSPosed.
> 
> The only thing I'd really need is tweak injection and Xcode for comfort (which I don't have)

From my understanding, jailbreak doesn't enable injection, just simple system-level tweaks. Am I incorrect?
