### ISSUE TITLE
Get notification when someone opens Snap

### ISSUE THREAD

**Issue by Jaggenite** [rhunk/SnapEnhance#655]
### Description

Hi! I would like to make a suggestion on a function that would be great I think. Say that you wait for someone to open a Snap but dont want to open the app to check if the snap has been opened, wouldnt a notification that tells you that that person has opened your snap be a neat feature? Sometimes you dont expect an answer but just want to know if its been seen. Thank you!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/275
