### ISSUE TITLE
Hiding Friends from Friend Feed not working anymore

### ISSUE THREAD

**Issue by Ch0nkst3r** [rhunk/SnapEnhance#658]
### Description

Hiding friends doesn't work anymore, they still appear on the friend feed.

### Reproduction steps

1. Go to User Interface -> Hide Friend Feed Entry (Enable it)
2. Go to social tab and hide friend
3. Look onto your Friend Feed on Snapchat
4. Friend still appearing

### Snapchat Version

12.71.0.30

### SnapEnhance Version

2.0.0 Build d8d4f49

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Can't reproduce. You should refresh the friend feed to see the entries disappear obviously.

**Comment by Ch0nkst3r** [comment]
Refreshing still doesn't make the hidden friends disappear. I don't know if I can give any logs regarding that issue.
