### ISSUE TITLE
Spectacles Pairing Issue

### ISSUE THREAD

**Issue by HeyPortal** [rhunk/SnapEnhance#659]
### Description

When trying to pair a V2 spectacles to the app, the following text is displayed. 

Specs Settings Update
Connect to Wi-Fi to enable Spectacles pairing.

I'm already connected to WiFi and all the necessary location and nearby devices permissions are enabled. With this message present I'm unable to pair the spectacles with the mod installed.This only appears when the mod in installed. When I switch to the stock app on the exact same version, this issue doesn't appear and the spectacles pairs successfully.

### Reproduction steps

1. Go to Snapchat Settings
2. Scroll down to Spectacles and Select it
3. See text displayed "Specs Settings Update
Connect to Wi-Fi to enable Spectacles pairing."

### Snapchat Version

12.72.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
I can't help unfortunately, no code coming from snapenhance interacts with Spectacles functionality so I can't fix it.
