### ISSUE TITLE
Multiple Pictures not loading 

### ISSUE THREAD

**Issue by ayowhatthatscrazy** [rhunk/SnapEnhance#671]
### Description

I am only able to send one picture at a time from gallery, sending multiple will only allow the first one to be send while the rest say "oops something went wrong please try again" or "tap to load"  and when I tap they don't load

### Reproduction steps

1. Open any chat and select multiple images or videos from camera roll and send
2. Click on any image that isn't the first and it should give the warning

![Screenshot_20240210-165822](https://github.com/rhunk/SnapEnhance/assets/120840669/9903bbb8-8355-460d-a1f0-1790835c1932)
![Screenshot_20240210-165835](https://github.com/rhunk/SnapEnhance/assets/120840669/c77c91dd-a028-4cab-a6fe-9234f54fec8f)

### Snapchat Version

12.72.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/512
