### ISSUE TITLE
feat: Download multiple media from single message

### ISSUE THREAD

**Issue by axelkar** [rhunk/SnapEnhance#673]
### Description

You can send multiple images from your gallery to one message. Why not download using SnapEnhance?

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Already implemented in v2.0.0

**Comment by axelkar** [comment]
When is it going to get released on GitHub Releases?

**Comment by axelkar** [comment]
I checked out the weblate translations and found a bunch of new features. Is it possible to build v2 myself?

**Comment by rhunk** [comment]
@axelkar https://t.me/snapenhance_ci

**Comment by axelkar** [comment]
Thanks for the link! Could you make a pre-release or somehow give me the file since the artifacts on GitHub are expired and I can't login to my Telegram?

**Comment by axelkar** [comment]
Is there an option to put group chat downloaded media in their own directory?
