### ISSUE TITLE
feat: Friend removal - Sort by and show details

### ISSUE THREAD

**Issue by uBadRequest** [rhunk/SnapEnhance#675]
### Description

I don't want to remove someone I have been talking to or added before a certain period.

Can we show message count numbers, how, and when they were added with the ability to sort by them, while using the mass friend removal feature?

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/fa7071284ff012f831818fd668c06552d9bbb6bd
