### ISSUE TITLE
Snap text not appearing sometimes

### ISSUE THREAD

**Issue by SalamiSimon** [rhunk/SnapEnhance#678]
### Description

It has come to my knowledge that sometimes, if not often, when a friend sends me a snap with text the text isn't showing when I open the snap. Same thing when I send a snap containing text. 

I've always thought that they're simply ignoring my text so I'm unsure how frequent it happens, and I'm sure the recipient have thought the same when my text wasn't shown in the snap. I'm also unsure on how many times I've seemingly ignored others texts.

I've verified with a dozen friends and asked if they saw the text when they didn't reply and they did not.

The same issue has happened in both a higher and lower snapchat version with SnapEnhance enabled. 

This might be a Snapchat issue and not SnapEnhance, but I have never had this issue before, maybe I just didn't think about it but I haven't seen any discussion about it outside SnapEnhance. 

In my video you can see my alt account (without SnapEnhance) sending a snap with text and it arriving. When I send one back on my main account with SnapEnhance the text does not show up when viewed. 

Video:
https://drive.google.com/file/d/1PKS1Qgfakc0IDcOpBp1RhegXvlDprm0f/view?usp=drivesdk

### Reproduction steps

1. Take a snap
2. Add text
3. Send it
4. Recipient can't see text 

### Snapchat Version

12.70.0.34

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Try this : https://github.com/rhunk/SnapEnhance/issues/303#issuecomment-1757571146
