### ISSUE TITLE
SnapEnhance not working

### ISSUE THREAD

**Issue by BlueStarOne** [rhunk/SnapEnhance#679]
### Description

The first two times I open Snapchat, SnapEnhance works great, but the next times, it don't load into Snapchat, until I reboot my phone.
When I reboot it, SnapEnhance works great the two first time, but the next times, it don't load into Snapchat, until I reboot my phone... 

### Reproduction steps

1. Open Snapchat
2. See the error: SnapEnhance is not working

### Logs

```markdown
I don't know which logs I have to put here, just let me know and I'll post them
```

### Snapchat Version

12.72.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by BlueStarOne** [comment]
Okay... So the bug changed... 
Now SnapEnhance works only the first time I open Snapchat AFTER I send a message with Snapchat to someone. 
The second time I'll reopen the app, it won't work
Also now rebooting my phone don't make SnapEnhance works anymore

**Comment by authorisation** [comment]
Issues for v1 are no longer accepted
