### ISSUE TITLE
FEAT: default volume control in media player

### ISSUE THREAD

**Issue by TheMoonld** [rhunk/SnapEnhance#680]
### Description

Instead of the custom Snapchat volume bar when viewing media it would just show the phones system volume bar (the one that pops up ath the side of the screen)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
100% going to be " not planned " 😂

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/edda0d1488990bbaaa2bacb77f7b2310ef47d6be
