### ISSUE TITLE
Option snapchat 

### ISSUE THREAD

**Issue by Lours87** [rhunk/SnapEnhance#683]
### Description

Hello, how are you? I have a proposal for you to add options on Snapchat if you can do them that would be really nice of you.
Thank you very much.
Here are the suggestions...

Who looked at your profile?
Who saw your story again?
Who shared your story?
Changing the Time of History
Who opened your message to see what's written?

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Unfortunately I can't retrieve information that the server doesn't send to the client, so I can't add the features you're asking for

**Comment by Lours87** [comment]
Ok thanks you
