### ISSUE TITLE
Bug Messages vocal

### ISSUE THREAD

**Issue by Lours87** [rhunk/SnapEnhance#684]
### Description

I have a bug with voice messages.
Every time I want to send a voice message, it cuts me off and takes me out of the discussion.
Is this normal

### Reproduction steps

1. Allez à '...'
2. Cliquez sur '....'
3. Faites défiler jusqu'à '....'
4. Voir erreur. 

### Snapchat Version

12.54.0.67

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by TheVisual** [comment]
Please download dev build https://github.com/rhunk/SnapEnhance/actions/runs/7920500733

**Comment by Lours87** [comment]
How do you do it?

**Comment by Lours87** [comment]
How do you do it?Envoyé de mon mobile
-------- Message d'origine --------De : TheVisual ***@***.***> Date : 17/02/2024  10:39  (GMT+01:00) À : rhunk/SnapEnhance ***@***.***> Cc : Lours87 ***@***.***>, Author ***@***.***> Objet : Re: [rhunk/SnapEnhance] Bug Messages vocal (Issue #684) 
Please download dev build https://github.com/rhunk/SnapEnhance/actions/runs/7920500733

**Comment by rhunk** [comment]
@Lours87 download latest beta build [here](https://t.me/snapenhance_ci)

**Comment by Lours87** [comment]
I need to download which one please?Envoyé de mon mobile
-------- Message d'origine --------De : rhunk ***@***.***> Date : 17/02/2024  11:25  (GMT+01:00) À : rhunk/SnapEnhance ***@***.***> Cc : Lours87 ***@***.***>, Mention ***@***.***> Objet : Re: [rhunk/SnapEnhance] Bug Messages vocal (Issue #684) 
@Lours87 download latest beta build here

**Comment by rhunk** [comment]
@Lours87 It depends on the architecture of your device. If you don't know, I recommend you download the universal version

**Comment by Lours87** [comment]
Thanks, but I have another problem.I downloaded the universal but the problem is that it does absolutely nothing on snap?  No function and nothing at all It's like if I had downloaded snap from the play store, do I have to do anything? ThanksEnvoyé de mon mobile
-------- Message d'origine --------De : rhunk ***@***.***> Date : 17/02/2024  12:01  (GMT+01:00) À : rhunk/SnapEnhance ***@***.***> Cc : Lours87 ***@***.***>, Mention ***@***.***> Objet : Re: [rhunk/SnapEnhance] Bug Messages vocal (Issue #684) 
@Lours87 It depends on the architecture of your device. If you don't know, I recommend you download the universal version

**Comment by rhunk** [comment]
@Lours87 https://t.me/snapenhance_chat

**Comment by Lours87** [comment]
I'm sorry but I don't understand what to do in the link you sent me and I'm only talking to you to help me. Can you please tell me how to make my snap work with all the options? Thank you very muchEnvoyé de mon mobile
-------- Message d'origine --------De : rhunk ***@***.***> Date : 17/02/2024  13:21  (GMT+01:00) À : rhunk/SnapEnhance ***@***.***> Cc : Lours87 ***@***.***>, Mention ***@***.***> Objet : Re: [rhunk/SnapEnhance] Bug Messages vocal (Issue #684) 
@Lours87 https://t.me/snapenhance_chat

**Comment by Lours87** [comment]
I wrote about the band. My message was read but no one replied. Sorry to insistEnvoyé de mon mobile
-------- Message d'origine --------De : rhunk ***@***.***> Date : 17/02/2024  13:21  (GMT+01:00) À : rhunk/SnapEnhance ***@***.***> Cc : Lours87 ***@***.***>, Mention ***@***.***> Objet : Re: [rhunk/SnapEnhance] Bug Messages vocal (Issue #684) 
@Lours87 https://t.me/snapenhance_chat

**Comment by Lours87** [comment]
Bro please Envoyé de mon mobile
-------- Message d'origine --------De : rhunk ***@***.***> Date : 17/02/2024  13:21  (GMT+01:00) À : rhunk/SnapEnhance ***@***.***> Cc : Lours87 ***@***.***>, Mention ***@***.***> Objet : Re: [rhunk/SnapEnhance] Bug Messages vocal (Issue #684) 
@Lours87 https://t.me/snapenhance_chat
