### ISSUE TITLE
feat: Personal snap score change

### ISSUE THREAD

**Issue by Eatham532** [rhunk/SnapEnhance#685]
### Description

It would be cool and useful to have the feature in snapchat plus where you can view the change in snap score work for yourself. And then view statistics base and see average daily snaps etc...

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment]
Already a feature in snapchat click ur bitmoji then click ur score on profile

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/275
