### ISSUE TITLE
feat: Set default filter tab

### ISSUE THREAD

**Issue by Ch0nkst3r** [rhunk/SnapEnhance#687]
### Description

Similar to setting the home tab, being able to choose the default filter tab as seen in the screenshot. 

![IMG_20240217_164149](https://github.com/rhunk/SnapEnhance/assets/135751388/e4de4fb1-4ef3-425a-81b4-7a0a1afd7367)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/issues/541#issuecomment-1872487995
