### ISSUE TITLE
Févité: viewed your profile

### ISSUE THREAD

**Issue by Lours87** [rhunk/SnapEnhance#692]
### Description

Hi 

I have a suggestion for improvement which is to display the nickname of the person by a notification that has consulted our profile. 

Thanks

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Snapchat doesn't log this type event

**Comment by Lours87** [comment]
Ok thank youEnvoyé de mon mobile
-------- Message d'origine --------De : rhunk ***@***.***> Date : 19/02/2024  08:07  (GMT+01:00) À : rhunk/SnapEnhance ***@***.***> Cc : Lours87 ***@***.***>, Author ***@***.***> Objet : Re: [rhunk/SnapEnhance] Févité: viewed your profile (Issue #692) 
Snapchat doesn't log this type event
