### ISSUE TITLE
Cant send a picture as snap

### ISSUE THREAD

**Issue by Sinner11111111** [rhunk/SnapEnhance#695]
### Description

Hello, 
Please help out 
It used to ask me how would i like to send a snap - as original , snap, without audio but from today i updated it and it wont ask me that 
Tried installing older versions of snapEnhancer and snapchat it wont work
If anyone can help please do!

### Reproduction steps

1. Go to send a picture
2. Click on send 
3. And it will send as a picture without asking to send as a snap
4. See error.

### Snapchat Version

The newest one

### SnapEnhance Version

Newest one

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by Sinner11111111** [comment]
Sorry got it

**Comment by cookedfnm** [comment]
sorry how did u fix this?

**Comment by cookedfnm** [comment]
> Sorry got it

how did u fix the bug?
