### ISSUE TITLE
feat: Show Mutual Friends with snapchatter

### ISSUE THREAD

**Issue by TheTrueDonDotta** [rhunk/SnapEnhance#700]
### Description

Honestly I'm not sure how this would work or if it's even possible but I want a way to see who exactly are the mutual friends with different snapchatters. Whether that be when they try to add you ( which is when they tell you how many mutuals you share) or maybe another section that shows it like preview or maybe it can be included in preview?

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
It's server sided sadly
