### ISSUE TITLE
feat: Saving Public Stories/Public Profile Stories with username included

### ISSUE THREAD

**Issue by Nnaemsy** [rhunk/SnapEnhance#704]
### Description

There should be a feature of where save someone's story off their public profile and it should include the user's username intacted with the image or video info.
This will help identify who the person is/which profile/which user it came from. 
instead of it being: saved to losinggame.webp, it should be saved to losinggame_pubicstory_username.webp
saved to monkeyemoji.mp4 > monkeyemoji_publicstory_username.mp4

i will try to add images and context in the next suggestion, i'm currently on a laptop. my bad.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Already implemented in v2
