### ISSUE TITLE
Autosave not working even when turned on

### ISSUE THREAD

**Issue by aryanmcr** [rhunk/SnapEnhance#707]
### Description

Autosave doesn't work even when it's turned on. It only sometimes works and that's really rare. I tried turning it off and on again but same error. Usually doesn't fix until I restart my device but even then it probably won't work.

### Reproduction steps

1. Go to settings
2. find autosave
3. turn it on
4. select the messages you want to save
5. doesn't work

### Snapchat Version

12.74.0.40

### SnapEnhance Version

2.0.0 AND the latest stable one

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
1. Disable stealth mode to use it
2. Set auto save to blacklist mode

**Comment by aryanmcr** [comment]
I have
