### ISSUE TITLE
feat: Search for favourite Sounds

### ISSUE THREAD

**Issue by ErsterImChat** [rhunk/SnapEnhance#711]
### Description

It would be awesome to have a Search bar, that searches the saved (favourite, using the hearth button) sounds.

If you have a lot of them it can take really long to find the right one, because the normal search bar only searches official sounds.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Unfortunately, this is a composer module and I can't modify it.
