### ISSUE TITLE
Snap enhance is not compatible with latest version of android

### ISSUE THREAD

**Issue by Elytraisaqt** [rhunk/SnapEnhance#712]
### Description

When I go into snap enhance, it's says that it's not compatible with latest version of snap.

### Reproduction steps

1. Go to 'snap enhance'
2. Get pop up 'snap enhance is not compatible with latest version of Android'
3. See error.

### Snapchat Version

12.75.0.34

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
Outdated SE version
