### ISSUE TITLE
show streak expiration info not working

### ISSUE THREAD

**Issue by Hello2439** [rhunk/SnapEnhance#713]
### Description

When I activate it in the settings it seems like it's switched on but when I go back to chat area it's not showing the expiration info.

### Reproduction steps

1. Go to `snap enhance settings`
2. Click on `show  streak expiration info`
3. Go to ur chats
4. See error.

### Snapchat Version

12.75.0.42

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Please use [latest ci build](https://t.me/snapenhance_ci)
