### ISSUE TITLE
problem with message logger

### ISSUE THREAD

**Issue by Acid4t** [rhunk/SnapEnhance#714]
### Description

i'm on android 14 and 1.2.6 of snapenhance..message logger is not working.worked on android 13 ig

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.70..0.34

### SnapEnhance Version

1.2.6
also  i recently started using warden and app manager..maybe that's causing the problem

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Use SE 2.0.0

**Comment by Acid4t** [comment]
bbut the latest is 1.2.6

**Comment by rhunk** [comment]
@Acid4t https://t.me/snapenhance_ci
