### ISSUE TITLE
Snaps saved as a .dat file

### ISSUE THREAD

**Issue by xnvmx** [rhunk/SnapEnhance#717]
### Description

When I want to download snaps after some time, when I opened them earlier and they were also sent only to me, or download my snaps that I sent only to one person - they are saved as a .dat file

Why does it work like that? I tried changing to .jpg or .mp4, but it didn't help. These .dat files are the size of normal snaps. How I can decode these to see what's in them?

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.57.0.55

### SnapEnhance Version

Newest Beta

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Some encrypted snaps lose their encryption key when viewed, making it impossible to retrieve their original content (they are therefore downloaded as .dat, as the file format cannot be determined).

**Comment by FurhadTheNerd** [comment]
suffering from the same issue!
did you find a workaround?
