### ISSUE TITLE
2d bitmoji option does not work anymore on snapchat map nor stickers

### ISSUE THREAD

**Issue by Radical4ever** [rhunk/SnapEnhance#718]
### Description

So snapenchance 2d bitmoji now only works on the chats screen, not anymore on the map and the stickers

### Reproduction steps

1. Go to snapenchance
2. Enable 2d bitmoji
3. Reload snapchat (wipe cache & force quit)
4. See bug?

### Snapchat Version

12.74.0.40

### SnapEnhance Version

2.0.0 

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/ec12980571f5e53aa503d2a49f41a48f260351a5
