### ISSUE TITLE
Bug: block Memories snap feed feature not working.

### ISSUE THREAD

**Issue by TheTrueDonDotta** [rhunk/SnapEnhance#719]
### Description

it seems the "Disable Memories Snap Feed" has stopped working in the latest versions despite me having it on.
![Screenshot_20240229_225326_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/144651375/6bf1b093-e567-4b88-ae7c-b6aed06b4370)
![Screenshot_20240305_125933_Snapchat](https://github.com/rhunk/SnapEnhance/assets/144651375/c0521d83-89fc-40bd-a76e-1563bfa0bcbf)

### Reproduction steps

1. Snap camera
2. Swipe up and see bug

### Snapchat Version

12.76.0.38

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/b4f6e4f3bdeba0c48fa2eacd1a865a8717149d04
