### ISSUE TITLE
Snapchat crashes when downloading Snaps

### ISSUE THREAD

**Issue by ErsterImChat** [rhunk/SnapEnhance#720]
### Description

Since a few days, Snapchat crashes when downloading Snaps to local Storage.
I have already updated to 1.2.6, changed the Download Location to SD-Card, rebuilt the APK, and reinstalled the App.

### Reproduction steps

1. Open any Snap
2. Hold the Picture to open the Menu
3. Select "Download Media"
4. = App crashes, the Snap isnt downloaded

(I dont know where to save Logs, i will add them, if somebody is able to explain where to get them from.)

### Snapchat Version

12.76.0.38 (also happened on older Versions)

### SnapEnhance Version

1.2.6 and 1.2.5

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Use [v2.0.0](https://t.me/snapenhance_ci)
