### ISSUE TITLE
feat: Save all snaps with the creation/sent date

### ISSUE THREAD

**Issue by xnvmx** [rhunk/SnapEnhance#722]
### Description

We can save snaps with the creation/sent date, but only those that we open at a given moment. If some are already open or we click "download" before opening the snap, it is saved with the download date.

I would like them to save with the creation/sent date in each case.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/79179356686c0f57243ddf4a459d7de5514af9de
