### ISSUE TITLE
New chat action menu

### ISSUE THREAD

**Issue by tycoon420** [rhunk/SnapEnhance#723]
### Description

When the new chat action menu is enabled in the experimental tab. The context menu doesn't show up(preview/download). 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.76.0.38

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Snapchat hasn't released it yet, so only activate it once it's officially released
