### ISSUE TITLE
feat: Number of saved snaps and any media on chat

### ISSUE THREAD

**Issue by xnvmx** [rhunk/SnapEnhance#724]
### Description

When we use SnapEnhance's "Preview" feature we can see the number of messages exchanged with a specific user.
Useful information, however what would be more useful would be the number of snaps and media saved in the chat (the number of objects in the gallery with another user in the friendship profile).
I have several thousand of them saved in the chat with one user and I would like to know if he deletes something from there sometimes, because it's hard to check it yourself with so many saved media.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Once the friend tracker is implemented, you'll be able to find out when your friend has deleted a message

**Comment by xnvmx** [comment]
> Once the friend tracker is implemented, you'll be able to find out when your friend has deleted a message

@rhunk When will this "friend tracker" be available approximately?
