### ISSUE TITLE
[Bug] Notification Blacklist not working on new snaps

### ISSUE THREAD

**Issue by Firebolt9907** [rhunk/SnapEnhance#725]
### Description

Some "New Snap" notifications are still being shown despite snaps being in the notification blacklist. These usually arrive right after a silent notification that says Snapchat is looking for notifications, and they always come 2 at a time, even if the snaps were received a while before the notification time. For context when reading the logs, the notification arrived at 17:04.

![image](https://github.com/rhunk/SnapEnhance/assets/83421723/7d408418-f379-4dcd-875d-fc750ea6b2e8)
![image](https://github.com/rhunk/SnapEnhance/assets/83421723/c809d96a-4c5c-4356-be3c-d4ac36560829)****

### Reproduction steps

1. Add new snaps to notification blacklist
2. Receive a snap from 2 different friends
3. Wait for Snapchat to check for new notifications

### Logs

```markdown
|D/2024-03-10 16:13:13/core/received message type: snap
|D/2024-03-10 16:23:13/core/received message type: snap
|D/2024-03-10 17:03:33/core/received message type: snap
|V/2024-03-10 17:05:15/manager/Loading RemoteSideContext
|W/2024-03-10 17:05:15/manager/Failed to get scripts folder
|W/2024-03-10 17:05:15/manager/Failed to get scripts folder
|V/2024-03-10 17:05:15/core/reloading config
|V/2024-03-10 17:05:15/manager/Syncing remote took 1 ms
|V/2024-03-10 17:05:15/core/database main.db integrity check passed
|V/2024-03-10 17:05:15/core/database arroyo.db integrity check passed
|V/2024-03-10 17:05:15/core/feature manager init took 29 ms
|W/2024-03-10 17:05:15/manager/Failed to get scripts folder
|V/2024-03-10 17:05:15/core/init took 475ms
|V/2024-03-10 17:05:15/core/Loaded 20 cached messages in 27ms
|V/2024-03-10 17:05:15/core/feature manager onActivityCreate took 50 ms
|V/2024-03-10 17:05:15/core/onActivityCreate took 50
|V/2024-03-10 17:05:16/core/reloading config
|V/2024-03-10 17:05:16/manager/Syncing remote took 0 ms
```

### Snapchat Version

12.75.0.42

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/bea8e796dcb074b6c4d9b3ffaa3725e334f8d0d2
