### ISSUE TITLE
Export memories doesn't work

### ISSUE THREAD

**Issue by xnvmx** [rhunk/SnapEnhance#727]
### Description

When I click export it crashes Snapchat and takes me immediately back to the SnapEnhance app.

### Reproduction steps

1. Go to SnapEnhance app.
2. Click on on the settings icon.
3. Click on `Export Memories`.
4. Select anything or leave as is.
5. Click on `Export`.
6. See `Exporting memories` for a millisecond and then automatically goes back to SnapEnhance settings.

### Logs

```markdown
|V/2024-03-11 03:54:05/core/reloading config
|V/2024-03-11 03:54:05/manager/Syncing remote took 20 ms
|V/2024-03-11 03:54:05/core/database main.db integrity check passed
|V/2024-03-11 03:54:05/core/database arroyo.db integrity check passed
|V/2024-03-11 03:54:05/core/feature manager init took 43 ms
|W/2024-03-11 03:54:05/manager/Failed to get scripts folder
|V/2024-03-11 03:54:05/core/init took 655ms
|V/2024-03-11 03:54:07/core/Loaded 20 cached messages in 164ms
|V/2024-03-11 03:54:07/core/feature manager onActivityCreate took 293 ms
|V/2024-03-11 03:54:07/core/onActivityCreate took 293
|V/2024-03-11 03:54:07/core/reloading config
|V/2024-03-11 03:54:07/manager/Syncing remote took 11 ms
```

### Snapchat Version

12.57.0.55

### SnapEnhance Version

2.0.0 (Latest CI Build: 9.03.2024) and previous version too

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Can't reproduce.
