### ISSUE TITLE
Auxiliary Camera Lens Support

### ISSUE THREAD

**Issue by Drammehh** [rhunk/SnapEnhance#729]
### Description

Greetings,
Is it possible to be able to add support for Auxiliary Lenses such as the Ultra Wide and Telephoto Lenses on older flagships/Mid Range phones? It would be cool to use the Ultra Wide camera, even if there won't be a smooth transition between the Ultra Wide and the Wide Lens.
Thanks!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
It's not up to me to implement this, it's up to Snapchat. It's a native feature that's constantly evolving, and it might not work in the future
