### ISSUE TITLE
bug: Ads Being Shown On Stories From Discovery

### ISSUE THREAD

**Issue by TheVisual** [rhunk/SnapEnhance#73]
### Description

Ads Being Shown On Stories From Discovery on certain ones ex.. Talkin Hoops

### Reproduction steps

```bash
1. Go to Talkin Hoops
2. Click on Story
3. Click Through Stories
4. See Ads
```

### Screenshots

```bash
https://freeimage.host/i/HPKxrAl
https://freeimage.host/i/HPKx4N2
https://freeimage.host/i/HPKxg94
```

### Snapchat Version

12.38.0.45

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/4c6fe17cedd378f6e7b0ee56bb206286f9f36989
