### ISSUE TITLE
Repair audio note

### ISSUE THREAD

**Issue by xnvmx** [rhunk/SnapEnhance#730]
### Description

When I send an audio note, it doesn't look like a real audio note. 

After sending the audio note via SnapEnhance, when I click play - there is no progress, the duration counter is broken and when I manually scroll forward, it restarts the audio and plays it from the beginning

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.57.0.55

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Long press to edit and just send, the duration will be fixed

**Comment by xnvmx** [comment]
> Long press to edit and just send, the duration will be fixed

@rhunk Your solution doesn't work. The duration counter is still broken and the voice cannot be scrolled like in a normal audio note. I tested this on different versions of snapchat and snapenhance app, with no success...
