### ISSUE TITLE
feat: Friend list export/import

### ISSUE THREAD

**Issue by reveh2** [rhunk/SnapEnhance#731]
### Description

Is it possible to add an option to export my friend list in an editable format? 
Importing such list could work similarly to "bulk messaging action", where I can manually send a friend request to previously saved usernames.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment]
This is indeed possible

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/f53e2db68d48feb5506d7fc7ef251b402ae24033

**Comment by reveh2** [comment]
Thank you for adding this! I'm testing it right now. 
There are two issues:

- in friend import window the "Add" button turns into greyed out "Added" button for every user as I just scroll through the list
- sending a friend invite while importing doesn't seem to work. Afer clicking "Add" button nothing happens and I'm still able to invite user in traditional way.

One question about the exported list. Is it intentional to export friends as userIDs instead of username, so there is no easy way to manually add or remove entries?
