### ISSUE TITLE
screenshot prevent not work

### ISSUE THREAD

**Issue by TheLinuxChoice5** [rhunk/SnapEnhance#736]
### Description

for me on my rooted device screenshot prevention is not working, i dont see where can i enable in the snapEnchance settings or its automatic?

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.77.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Outdated version, please use 2.0.0
