### ISSUE TITLE
Can't download snaps/stories

### ISSUE THREAD

**Issue by cyberastr4l** [rhunk/SnapEnhance#737]
### Description

Can't download any received snaps or stories, changing the download location did not do anything. Using most recent release version. 

### Reproduction steps

1. Go to Any Snap or Storie
2. Click on the three dots. 
3. Download button blacked out. (Not clickable) 

### Snapchat Version

12.70.0.34

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
This version is no longer updated. Please use [v2.0.0](https://t.me/snapenhance_ci)
