### ISSUE TITLE
Settings gear missing on 3 tab

### ISSUE THREAD

**Issue by LolekLiam** [rhunk/SnapEnhance#739]
### Description

When enabling 3 tab snapchat in the Snapchat+ settings, the settings gear goes missing.
![20240315_063323](https://github.com/rhunk/SnapEnhance/assets/63475764/656525f3-431b-4e05-b5f3-0bd2237f9e89)

### Reproduction steps

1. Enable beta/preview Snapchat+ features in snapenhance
2. Enable 3 tab snapchat in Snapchat+ settings
3. Settings gear goes missing

### Snapchat Version

12.77.0.37

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
SnapEnhance hasn't been updated / optimised for 3 Tab

**Comment by rhunk** [comment]
Fixed in https://github.com/rhunk/SnapEnhance/commit/b06c87c4643a15ecfa1a2e7526a5f2c8b5347a21
