### ISSUE TITLE
Unable to login to Snapchat after reinstalling

### ISSUE THREAD

**Issue by cookedfnm** [rhunk/SnapEnhance#742]
### Description

I've reinstalled latest v2 snapenhance and snapchat with the recommended v12.70.0.34.

### Reproduction steps

1. Go to Snapchat
2. Click on Login
3. Enter details
4. See error "We have temporarily locked your account due to repeated failed attempts or unusual activity. Your access to Snapchat is temporarily disabled."

### Snapchat Version

v12.70.0.34

### SnapEnhance Version

v2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by cookedfnm** [comment]
does anyone know how to get past this?

**Comment by bocajthomas** [comment]
> does anyone know how to get past this?

If you have installed via Google play 
Open Snapchat 
Clear data 
Then open snapchat back up 
Then login

**Comment by cookedfnm** [comment]
> > does anyone know how to get past this?
> 
> If you have installed via Google play 
> Open Snapchat 
> Clear data 
> Then open snapchat back up 
> Then login 

it's a nodded apk but I've tried that already

**Comment by cookedfnm** [comment]
@rhunk this error occurs because of the mod, please tell me to mod at their own risk. are u aware of this or has it only been me so far? I've tried on 2 devices so far.

**Comment by bocajthomas** [comment]
> @rhunk this error occurs because of the mod, please tell me to mod at their own risk. are u aware of this or has it only been me so far? I've tried on 2 devices so far.

The read me clearly states as unsafe

**Comment by cookedfnm** [comment]
> > @rhunk this error occurs because of the mod, please tell me to mod at their own risk. are u aware of this or has it only been me so far? I've tried on 2 devices so far.
> 
> The read me clearly states as unsafe 

In the FAQ it clearly states that nobody has ever gotten banned with the mod. Well I guess this is a first then.
