### ISSUE TITLE
feat: prevent group chat kick

### ISSUE THREAD

**Issue by TheMoonld** [rhunk/SnapEnhance#744]
### Description

Like the already present prevent force logout feature. This would prevent getting removed from group chats.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by aryanmcr** [comment]
yes I agree, it's rlly annoying when u get spam kicked

**Comment by Not-Smelly-Garbage** [comment]
+ once removed, you can still view the gc, thatd be cool

**Comment by rhunk** [comment]
It's not possible to rejoin the group, but I've implemented a way of always being able to view the group's information
https://github.com/rhunk/SnapEnhance/commit/26c850802b7f6751297a2f3b92ea1815cbad7322
