### ISSUE TITLE
feat: Remove/Change Splashscreen

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#746]
### Description

Instead of that blinding yellow splash screen when launchung the app, and optional black and white (black background, white Snapchat logo) screen would be nice

Additionally it could be activated at a set time, like at night

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
Not possible because I can't edit AndroidManifest.xml
