### ISSUE TITLE
feat: Bulk Delete Messages

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#748]
### Description

There could be an option in the chat drawer/friend/group details that when you press it, it asks for confirmation, then deletes all messages in a given time period that you sent.

There could be an option to delete only certain message types too, like snaps, chats, media, etc.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
This is already implemented
