### ISSUE TITLE
The app refuses to open after installing snapenhance

### ISSUE THREAD

**Issue by Britishblue** [rhunk/SnapEnhance#749]
### Description

I downloaded snap enhance on my non rooted phone using lspatch. I am aware this isnt recommended however it has worked well in the past for me. When opening the app after patching it it stays on the logo screen before eventually crashing. I used graphene OS on my pixel 7 with google play services installed. I have tried it on the newest beta CI and older versions of snap enhance / older versions of snap enhance and still the same issue. Im not sure if it has anything to do with my phones operating system or not.

### Reproduction steps

1. Open snapchat
2. Crash

### Snapchat Version

12.77.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [x] This is not a bug regarding Snapchat+.
- [x] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by Theonethom** [comment]
https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide

Check Installation Guide (GrapheneOS)

**Comment by bocajthomas** [comment]
https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide

Check " Installation Guide (GrapheneOS): "

**Comment by Ch0nkst3r** [comment]
I have had the same issue on my Pixel 7, after upgrading GrapheneOS to Android 14 QPR 2. After searching for the solution in the Telegram group I was recommended using the very latest LSPatch release 402. Try search for it, it may be found in some archives.

**Comment by Britishblue** [comment]
> I have had the same issue on my Pixel 7, after upgrading GrapheneOS to Android 14 QPR 2. After searching for the solution in the Telegram group I was recommended using the very latest LSPatch release 402. Try search for it, it may be found in some archives.

Did you ever find it? I cant find a newer release of LSPatch. The one on github is 3 months old and says v0.6

**Comment by Ch0nkst3r** [comment]
Yes indeed, at least this is the place I got it from. 
https://t.me/s/LSPatchArchives
Use at your own risk.
