### ISSUE TITLE
feat: Save chat messages/snap in app forever

### ISSUE THREAD

**Issue by Kloxified** [rhunk/SnapEnhance#751]
### Description

If this is already a feature I apologize, I'm sort of confused with what message logger and bypass message retention policy does.

Essentially what I'm looking for is for my chats to stay on snapchat on my end forever without having to save them, so chats won't disappear after 24 hrs like they usually do. Idk if this is possible or if it's a thing already and I'm just confused but if that could be done that would be an amazing feature.

Thanks!

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
In newer versions of Snapchat you can choose not to delete messages after 24 hours, even if they have not been saved.

**Comment by Kloxified** [comment]
> In newer versions of Snapchat you can choose not to delete messages after 24 hours, even if they have not been saved.

Thanks for the response, Im wondering In what versions of snapchat is this a thing? And is there somewhere where I need to turn it on?
