### ISSUE TITLE
feat: Theming feature or script

### ISSUE THREAD

**Issue by ahmedraza52** [rhunk/SnapEnhance#752]
### Description

If we can change theme of whole Snapchat App.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
make a pr

**Comment by ahmedraza52** [comment]
pr?

I don't understand 😅

**Comment by bocajthomas** [comment]
> pr?
> 
> I don't understand 😅

Theming is in testing stage
