### ISSUE TITLE
Whitelist feature in bulk delete/remove friends

### ISSUE THREAD

**Issue by ahmedraza52** [rhunk/SnapEnhance#756]
### Description

I mean, I have 4000 friends and I want to remove all of them except 20-30 friends. So,how can I search them and untick them from 4000 people :(

So, there should be option to search user and select and whitelist them. 

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
You can use feature " Bulk Messaging Action " 
Steps:
1. Open SnapEnhance 
2. Tap The Settings Icon 
3. Tap The Icon Next to " Bulk Messaging Action " 
4. Select The People You Want To Remove 
5. Tap " Remove "

**Comment by ahmedraza52** [comment]
Bro, I know that how I can use "Bulk messaging action" feature.

I am just suggesting that there should be option to search users and whitelist them from that bulk remove friends list.

Like I have 4000 friends and I want to remove all of them except 20-30 people, so how can I untick 20-30 people from those 4000 people?

**Comment by rhunk** [comment]
Added in https://github.com/rhunk/SnapEnhance/commit/4fd52c0c3c566b88260766eb7e44c012d055b359
