### ISSUE TITLE
feat: disable update from play

### ISSUE THREAD

**Issue by Mezous** [rhunk/SnapEnhance#757]
### Description

Snapchat appears in the list of updates in Play even though the version I am using is the same version as the one in Play. Please add the feature to hide the appearance of the update in Play forever.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
I can't do that unfortunately but you can always disable auto updates for a specific app in playstore

**Comment by bocajthomas** [comment]
This is a Google play bug
