### ISSUE TITLE
Message doesn't mark as red.

### ISSUE THREAD

**Issue by Tanron009** [rhunk/SnapEnhance#758]
### Description

So if someone sends me something and I open it, after closing the chat it doesn't mark as red, In the screenshot I sent, Ive opened these chats multiple times and scrolled all the way down to the most recent chats.
![Screenshot_2024-03-21-08-36-03-385-edit_com snapchat android](https://github.com/rhunk/SnapEnhance/assets/117080892/c320d90d-2443-432c-94ac-4c25639fc59c)

### Reproduction steps

Ion know

### Logs

```markdown
I don't have any logs
```

### Snapchat Version

12.77.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
Turn off prevent read receipts
