### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by dnlweijers** [rhunk/SnapEnhance#762]
### Description

I just installed SnapEnhance in Magisk (rooted) and used LSPosed for installing. Im on the newest version of everything. When i tried the feature to download a story, the app crashed, closed, and doesnt open again (closes directly). Im using an Samsung Galaxy S23 Ultra and I have snapchat+. My snapchat copy, using the Samsung dual messenger option, works.

### Reproduction steps

1. Go to snapchat
2. Click on a story
3. Hold the screen
4. Click download
5. If the app closes, see if it opens again

### Snapchat Version

12.78.0.43

### SnapEnhance Version

1.2 6

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
It says your on v1.2.6 
But you said your on the latest 
Please update to the beta v2
I am too on a samsung galaxy s23 ultra 
Non root
