### ISSUE TITLE
There is no option to prevent screenshot notifications?

### ISSUE THREAD

**Issue by Britishblue** [rhunk/SnapEnhance#763]
### Description

The description on the github says one of the features is "Prevent Screenshot Notification", but I cant see it anywhere in the snap enhance settings. I have everything else but not that.

### Reproduction steps

1. Go to Snapchat
2. Click on settings
3. There is no Prevent Screenshot Notification option

### Snapchat Version

12.78.0.43

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide
