### ISSUE TITLE
Black Screen on Story

### ISSUE THREAD

**Issue by juggermynuthoiya** [rhunk/SnapEnhance#764]
### Description

Hi. Thanks for making Snapenhancer. I have been using it for 4 months now.

Over the last 3 days, when I upload to my story it does that just fine. However, if I want to view my own story, I get a black screen. No audio either. 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
No output to paste.
```

### Snapchat Version

Latest on from APK mirror. 

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Fixed in v2.0.0 btw

**Comment by juggermynuthoiya** [comment]
We're already at 2.0. Well damn. Where can I get it. The telegram channel
is at 1.2.6

**Comment by rhunk** [comment]
@juggermynuthoiya https://t.me/snapenhance_ci

**Comment by juggermynuthoiya** [comment]
Thanks man.
