### ISSUE TITLE
Crashing bug when i open snapchat 

### ISSUE THREAD

**Issue by DARKPhewee** [rhunk/SnapEnhance#765]
### Description

Ok so after I got snapEnhance snapchat worked for a little bit then whenever I opened it it kept crashing or not opening up

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
It just opens and kicks me out...
```

### Snapchat Version

The newest up date March 13th 2024 don't have the exact version 

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by TheVisual** [comment]
Use Version 2 1.2.6 isn't updated mate

**Comment by authorisation** [comment]
v1 is deprecated
