### ISSUE TITLE
Prevent Screenshot option is not in the SnapEnhance settings

### ISSUE THREAD

**Issue by siiidhan** [rhunk/SnapEnhance#767]
### Description

The "Prevent Screenshot notifications" option said in `readme.md` does not exist.

**Please don't just close this issue by saying "not planned", I just want a quick answer.**

### Reproduction steps

1. Go to `SnapEnhance settings`
2. Try to find `Prevent Screenshot notifications`
3. Cannot be found, but is mentioned in `readme.md`

### Snapchat Version

12.78.0.43

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Update to v2 
https://t.me/snapenhance_ci

**Comment by Acid4t** [comment]
hey i'm from pakistan and our army(which controls the country ) has banned telegram..so can you give me another option to download CI builds?? TIA
