### ISSUE TITLE
Gear settings icon

### ISSUE THREAD

**Issue by Arceus-X** [rhunk/SnapEnhance#770]
### Description

With the latest beta version of SnapEnhance 2.0, it has not been showing the gear settings icon any version passed the Snapchat 12.79.0.36 Beta version

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.79.0.36 Beta and above

### SnapEnhance Version

2.0.0 (latest beta)

### Agreement

- [x] This is not a bug regarding Snapchat+.
- [x] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Why are you using beta version of Snapchat use stable
