### ISSUE TITLE
Friend import bugs

### ISSUE THREAD

**Issue by reveh2** [rhunk/SnapEnhance#771]
### Description

Two issues with friend import feature:

1. While importing the friend list, the "Add" button turns into greyed out "Added" button for almost every user as I simply scroll through the list. 
I've noticed that the "Add" button does not turn into "Added" button while scrolling for people who were invited but have not accepted yet.

2. Sending a friend invite while importing doesn't seem to work. Nothing happens afer clicking the "Add" button and afterward I'm still able to invite this user in traditional way.

One question about the exported list. Exporting friends as userIDs makes it really hard to manually edit friend list entries. Is it intentional or there is possibility you could change it to usernames in the future?

### Reproduction steps

1. Import friend list
2. Scroll through the list
3. As you scroll Add button turns into Added button. Clicking Add doesn't send a friend request.

### Snapchat Version

12.77.0.37

### SnapEnhance Version

2.0.0 run 51a2fe88

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by Theonethom** [comment]
> 1. While importing the friend list, the "Add" button turns into greyed out "Added" button for almost every user as I simply scroll through the

For "1." You already have the users added so it won't turn to " add " if there already added

**Comment by bocajthomas** [comment]
For "1." You already have the users added so it won't turn to " add " if there already added

**Comment by bocajthomas** [comment]
> > For "1." You already have the users added so it won't turn to " add " if there already added
> 
> Yes, this part behaves correctly. I thought it'd be helpful to be precise what works correctly and what doesn't. I'm sorry it was poorly written.

○ Friend import is new there's going to be bugs 
○ For the " Question " open a new issue
And add "feat"

**Comment by bocajthomas** [comment]
> > > For "1." You already have the users added so it won't turn to " add " if there already added
> > 
> > 
> > Yes, this part behaves correctly. I thought it'd be helpful to be precise what works correctly and what doesn't. I'm sorry it was poorly written.
> 
> ○ Friend import is new there's going to be bugs 
○ For the " Question " open a new issue And add "feat"

**Comment by bocajthomas** [comment]
I have tested this and it does indeed added them. But it doesn't say after ( it only says added if the other user has accepted it ) 

They should be a feature were it says 
○ Friends ( if both users have each other on snap ) 

○ Added ( if you have added the user but the user hasn't accepted it yet 

○ Add ( if you haven't added & are not friends ) 
@rhunk

**Comment by reveh2** [comment]
> I have tested this and it does indeed add them. But it doesn't say after ( it only says add if the other user has accepted it )
> 
> They should be a feature were it says ○ Friends ( if both users have each other on snap )
> 
> ○ Added ( if you have added the user but the user hasn't accepted it yet )
> 
> ○ Add ( if you haven't added & are not friends ) @rhunk

Does the 'Add' button turn into an 'Added' button while you scroll the list? 
Here's what's happening to me: https://streamable.com/n66sw5

- For friends who haven't been invited yet: the "Add" button doesn't respond to clicking. After scrolling out of the screen, the button turns into "Added", regardless of whether I click "Add" or not. The actual invite is never sent.

- For friends who were invited before but have not accepted yet: The "Add" button doesn't change after scrolling. It shows the processing animation after clicking (I understand that adding a person already added is pointless. Just explaining the current behavior).

**Comment by bocajthomas** [comment]
> > I have tested this and it does indeed add them. But it doesn't say after ( it only says add if the other user has accepted it )
> > They should be a feature were it says ○ Friends ( if both users have each other on snap )
> > ○ Added ( if you have added the user but the user hasn't accepted it yet )
> > ○ Add ( if you haven't added & are not friends ) @rhunk
> 
> Does the 'Add' button turn into an 'Added' button while you scroll the list? Here's what's happening to me: https://streamable.com/n66sw5
> 
> * For friends who haven't been invited yet: the "Add" button doesn't respond to clicking. After scrolling out of the screen, the button turns into "Added", regardless of whether I click "Add" or not. The actual invite is never sent.
> * For friends who were invited before but have not accepted yet: The "Add" button doesn't change after scrolling. It shows the processing animation after clicking (I understand that adding a person already added is pointless. I'm only explaining the differences in behavior).

Yes I get the same thing 
Import/ Export friends as some flaws 
Hopefully they will be fixed

**Comment by bocajthomas** [comment]
This is an experimental feature 
This will mostly be fixed in the future
