### ISSUE TITLE
Failed to init the feature media downloader

### ISSUE THREAD

**Issue by AlliUmarr** [rhunk/SnapEnhance#772]
### Description

I reinstall both me Snapchat and snap enhance after reinstalling few feature of of snap enhance not working 
1 media downloader
2 Snapchat plus
3 no friends score delay

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

 12.80.0.35 Beta

### SnapEnhance Version

1.2.6

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Use stable version of Snapchat &
And use v2.0.0 ( SnapEnhance )
