### ISSUE TITLE
Snapchat Crashing

### ISSUE THREAD

**Issue by CryticalBomb1** [rhunk/SnapEnhance#774]
### Description

Unrooted. I installed the Module and All that but as soon as i open Snapchat, it just closes.

### Reproduction steps

1. Patch snapchat
2. Open snapchat
3. See crash

### Snapchat Version

12.78.0.43

### SnapEnhance Version

1.2.6 armv7

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
> Update to v2 https://t.me/snapenhance_ci
> 
> Also Avoid LSPatch unless you wanna get banned basically just root safer

Works perfectly for non root
