### ISSUE TITLE
How do I set an anti-download?

### ISSUE THREAD

**Issue by IkkixD** [rhunk/SnapEnhance#775]
### Description

I don't see anywhere in any settings to be able to set it to not download snaps from certain users. I only want to save one users, but it saves them all atm.

### Reproduction steps

Search anywhere for the setting

### Snapchat Version

12.63.0.55

### SnapEnhance Version

1.2.5

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Please update your Snapchat to the latest version 
You are about 3 months behind the current stable version!

Also update your SnapEnhance version to v2.0.0
V1.x.x is no longer being worked on!
