### ISSUE TITLE
TITLE

### ISSUE THREAD

**Issue by tpzo6** [rhunk/SnapEnhance#776]
### Description

Some features do not work and this message appears every time I enter Snapchat  
![Screenshot_٢٠٢٤٠٣٢٢-١٦١٣٣٦_Snapchat](https://github.com/rhunk/SnapEnhance/assets/164991623/c3be28bb-c812-48a9-8c9d-868ba0051822)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.79.0.37

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
Please provide SE logs (open snapenhance app and click on bug icon)
