### ISSUE TITLE
Bypass Screenshot Protection not working

### ISSUE THREAD

**Issue by siiidhan** [rhunk/SnapEnhance#778]
### Description

I recently created an issue saying I can't find the option. I finally installed the v2.0.0 version via Telegram. At first, the Bypass Screenshot Detection feature worked fine, after few days it announces that I took screenshot of the chat, I tried turning it off and on and still the problem continues.

### Reproduction steps

1. Turn on `Bypass Screenshot Detection`
2. Take a screenshot
3. Screenshot announcement is shown

### Snapchat Version

12.78.0.43

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
U need to turn on " Prevent Message Sending " ( screenshot )

Steps:
1. Open SnapEnhance 
2. Go to " Features " Tab
3. Tap " Messaging " 
4. Scroll And find " Prevent Message Sending " 
5. Tap the Icon next to the text 
6. Toggle On " Screenshot " 
7. Then press the save icon 
![Screenshot_20240326_160854_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/41988041/786c2a11-4f4a-4c4c-9e30-83bcbf5e3040)
![Screenshot_20240326_160900_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/41988041/5864af71-82e8-43d5-88f4-be0eb7503860)
![Screenshot_20240326_160909_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/41988041/239ea26f-649f-4211-86b6-fe482e9b2a6a)
![Screenshot_20240326_160912_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/41988041/f38407da-01db-4315-8c7f-b1b03bb7e3b1)
