### ISSUE TITLE
Features missing/not active

### ISSUE THREAD

**Issue by Nnaemsy** [rhunk/SnapEnhance#780]
### Description

This message keeps popping up every time I open the app. Which from experience from the last stable release, doesn't let u have access to all the features enabled.
![Screenshot_20240326_172936_Snapchat](https://github.com/rhunk/SnapEnhance/assets/161165813/5dce6dca-681a-4ede-a045-48cd45d7250a)

I am using a s24 ultra running android 14 one ui 6.1

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
Idk
```

### Snapchat Version

12.80.0.37

### SnapEnhance Version

2.00

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by authorisation** [comment]
No log provided

**Comment by Nnaemsy** [comment]
How can I provide log....

**Comment by bocajthomas** [comment]
Use stable Snapchat!
