### ISSUE TITLE
Snapchat public profile isnt working 

### ISSUE THREAD

**Issue by clux2** [rhunk/SnapEnhance#783]
### Description

Public profile cant be opened in the first time. The buttons not showing. Its al the way down.

![20240327_223911](https://github.com/rhunk/SnapEnhance/assets/165200556/e660af20-4b53-4858-985a-a8560d59d301)

### Reproduction steps

.

### Snapchat Version

Latest 

### SnapEnhance Version

Latest

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://help.snapchat.com/hc/en-us/requests/new
