### ISSUE TITLE
Fails to save any image or video to camera roll.

### ISSUE THREAD

**Issue by JamPat17** [rhunk/SnapEnhance#784]
### Description

Every time I try to use the 'download' option it returns a toast saying 'Failed to save to gallery java.lang.NullPointerException'

### Reproduction steps

1. Go to a chat.
2. Click on download
4. See error.

### Snapchat Version

12.79.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Please update your SnapEnhance To the Latest 
Beta version ( V2.0.0 )

V1 is deprecated
