### ISSUE TITLE
snapenhance Cl build

### ISSUE THREAD

**Issue by Acid4t** [rhunk/SnapEnhance#785]
### Description

ik this is not the right thing to do ...but since i live in Pakistan..i dont have access to telegram(all hate to the army)..can you post builds on pling maybe or some other way? TIA

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/actions

**Comment by Acid4t** [comment]
can you guide me what to do from here? please?

**Comment by Theonethom** [comment]
> can you guide me what to do from here? please?

Check the Wiki
https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide

**Comment by Acid4t** [comment]
thanks...but  can you think of a way to let me know what version of snapchat to use with each Cl build?

**Comment by Theonethom** [comment]
> thanks...but can you think of a way to let me know what version of snapchat to use with each Cl build?

I allways use the latest stable but you can use any

**Comment by Acid4t** [comment]
thanks brother(unless you are jew)
