### ISSUE TITLE
Bride error

### ISSUE THREAD

**Issue by axrrow22** [rhunk/SnapEnhance#786]
### Description

I went to update snap and tried to reinstall snap enhance and the first few times it gave me an install error now its a bridge error and i cannot install an apk from my files when i try it it says, ( no such file or directory) plz help im on android 13

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.77.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Please update to v2.0.0 
V1 is no longer in development 

Also update your Snapchat to latest version ( stable )
