### ISSUE TITLE
Cant fint version 2.0.0

### ISSUE THREAD

**Issue by axrrow22** [rhunk/SnapEnhance#787]
### Description

where do i fond ver 2.0.0

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

latest

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/actions or https://t.me/snapenhance_ci
