### ISSUE TITLE
updated everything nd it still wont install

### ISSUE THREAD

**Issue by axrrow22** [rhunk/SnapEnhance#790]
### Description

updated everything nd it still wont install
![Screenshot_20240330_082421](https://github.com/rhunk/SnapEnhance/assets/147211512/6f7fc135-b419-4f03-8228-c21521af34d0)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.77.0.39

### SnapEnhance Version

2.0.0

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide
