### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by axrrow22** [rhunk/SnapEnhance#792]
### Description

need help logging in keep giving me suspicous error

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

latest

### SnapEnhance Version

2.0.0

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment]
https://t.me/snapenhance_chat
