### ISSUE TITLE
Hide "My Stories" Section

### ISSUE THREAD

**Issue by Not-Smelly-Garbage** [rhunk/SnapEnhance#794]
### Description

Add a toggle to hide the "my stories" section on the stories page
![Screenshot_2024-04-01-14-09-01-20_a63b0f8076346d26cbdc1b971a1da2a7](https://github.com/rhunk/SnapEnhance/assets/62516050/0350ab00-3e43-4028-a5de-6c6d24d95653)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
https://github.com/rhunk/SnapEnhance/commit/7bf80723c4d275f66b2b65e90824113981be90a0
