### ISSUE TITLE
Snap crashes when i turn on dark mode and cant be opened

### ISSUE THREAD

**Issue by berreJona** [rhunk/SnapEnhance#795]
### Description

Snapchat crashes when i turn on dark mode and cant be opened so i have reinstall snap
I use the LsPatch 

### Reproduction steps

1. Go to `Settings` then `app appearance`
2. Click on `Dark mode` then `restart now
3. Snap closes
4. See error. `snapchat closed because this app has a bug` 
5 try to open snap and it just closes after 2 seconds 

### Logs
![image0](https://github.com/rhunk/SnapEnhance/assets/122868921/45f63e21-6282-4a70-a9dd-60f8433cc837)

```markdown
dont know how to find that
```

### Snapchat Version

The latest version of snap for google play store

### SnapEnhance Version

SnapEnhance 1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment]
Outdated SE

**Comment by berreJona** [comment]
> Outdated SE
its marked as the latest release. where do i find the new one then?

**Comment by bocajthomas** [comment]
> > Outdated SE
> > its marked as the latest release. where do i find the new one then?
https://github.com/rhunk/SnapEnhance/actions/workflows/beta.yml or https://t.me/snapenhance_ci

**Comment by berreJona** [comment]
> > > Outdated SE
> > > its marked as the latest release. where do i find the new one then?
> > > https://github.com/rhunk/SnapEnhance/actions/workflows/beta.yml or https://t.me/snapenhance_ci

How dose cl work i have only used the apk before
