### ISSUE TITLE
Stretched video...

### ISSUE THREAD

**Issue by Slavce124** [rhunk/SnapEnhance#797]
### Description

When I try to record a video as a streak the video gets stretched vertically I've tried every setting but nothing works and I didn't have this problem with the regular snapchat

### Reproduction steps

1. Go to camera
2. Record a streak
3. The video gets stretched

### Snapchat Version

12.79.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
v1 is obsolote
