### ISSUE TITLE
Failed to init feature MediaDownloader

### ISSUE THREAD

**Issue by notHankCraft** [rhunk/SnapEnhance#798]
### Description

Whenever opening the snap, a notification at the bottom pops up and says "Failed to init MediaDownloader" Also, when opening snaps and trying to download it wont work. Downloading only works when you go into chat and hold down and press download media.

### Reproduction steps

1. Open Snapchat
2. See the notification saying "Failed to init MediaDownloader"

### Snapchat Version

12.80.0.39

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [x] I have attached a log if deemed neccessary.
- [x] This issue is not a duplicate.

**Comment by authorisation** [comment]
v1 is obsolote
