### ISSUE TITLE
bug: unable to lunch Snap Enhance

### ISSUE THREAD

**Issue by Prateeksingh13** [rhunk/SnapEnhance#80]
### Description

I am not able to open sanp enhance. I have install ARMv8 version can anyone suggest me the solution

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Snapchat Version

12.36.0.53

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by snapboss** [comment]
Same here. I am using LSPatch, SnapEnhance doesn't open
