### ISSUE TITLE
Features Guide

### ISSUE THREAD

**Issue by ahmedraza52** [rhunk/SnapEnhance#811]
### Description

There should be a "feature guide" tab in SnapEnhance module so people can know that how this feature works exactly. Cause there are many features available in SnapEnhance which we can't understand that what is the use of this feature. I also don't know about some features like "Session Events", "Add friend source spoof", "Disable composer modules" and many features like that.

If there is guide available in SnapEnhance for every feature which shows how this works. It will be easy to use all available features for users.

And many users requests here already available features in SnapEnhance cause they don't know that this feature is already available and don't know how they can use it. So they request here again and again.

In guide you can add brief description about feature and also add screenshot or screen recording.

Benefits of adding "features guide" :
• User-experience will be improve of SnapEnhance cause no need to ask in SE Telegram group that how this feature works.
• Less duplicate or already added feature request for developer.

And the last thing I want to say that,Big Thanks for this beautiful and powerful Snapchat module. It really helps lot to me. There are so many modifications available in this Mod 🔥. Now you just have to make them more stable and powerful. You're great sir.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment]
If you don't really know what a feature is for then there is no need for you to use them.

**Comment by bocajthomas** [comment]
> If you don't really know what a feature is for then there is no need for you to use them.
> 
> I agree that some features could be explained a little bit better but there will not be a Fully-fledged Guide written by me or rhunk anytime soon.

I'll do it

**Comment by bocajthomas** [comment]
https://github.com/rhunk/SnapEnhance/wiki/Features-Explained
This is already planned 
You can find it here ( link above )
This will be completed By Tmz

**Comment by ahmedraza52** [comment]
> https://github.com/rhunk/SnapEnhance/wiki/Features-Explained You can find it here ( link above ) This will be completed By Stable Release ( V2.0.0 )

Thanks bro, Its really needed thing for SE users.

**Comment by bocajthomas** [comment]
@ahmedraza52  you can now find it on [Features-Explained](https://github.com/rhunk/SnapEnhance/wiki/Features-Explained)

**Comment by ahmedraza52** [comment]
> @ahmedraza52 you can now find it on [Features-Explained](https://github.com/rhunk/SnapEnhance/wiki/Features-Explained)

Thank you so much 🥺

But there is still many features which we can't understand like "Disable Composer Module", "Add friend source spoof", "Session Events", "Better locations", "Enhance Friend map Nametags" etc. 🙁
