### ISSUE TITLE
Snapenhance doesnt allow me ro activate snapchat plus feature.

### ISSUE THREAD

**Issue by hajimon54** [rhunk/SnapEnhance#819]
### Description

It doesnt allow me to access Snapchat plus feature anymore. I literally just updated the snapchat app from the official Google playstore and now that i am trying to use the activate snapchat plus feature for Snapchat it just says its been disabled and doesnt work at all. This literally happened just now so im wondering what the fix for this should be?

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.80.1.0

### SnapEnhance Version

1.2.6

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
V1 Is Officially Obsolete
Please use v2.0.0
