### ISSUE TITLE
feat: number of snaps progress bar 

### ISSUE THREAD

**Issue by iBasim** [rhunk/SnapEnhance#82]
### Description

Hi!
A few weeks ago, a feature was added to my account on Snapchat, which is knowing the number of snaps for anyone I follow that appeared in the form of dots or small lines at the top of the screen, but this feature only lasted for days and then disappeared, I hope you will add it
![20230622_105319](https://github.com/rhunk/SnapEnhance/assets/57762287/eb738530-ad78-4803-b4e0-8514868f6785)
![Screenshot_20230622_105716_com twitter android](https://github.com/rhunk/SnapEnhance/assets/57762287/e551e3ad-c04b-4e7a-95f7-6763f165a81e)
![Screenshot_20230622_105818_com twitter android](https://github.com/rhunk/SnapEnhance/assets/57762287/f34b6073-a94a-4224-9912-bdc6894be769)
![20230622_105921](https://github.com/rhunk/SnapEnhance/assets/57762287/77984d31-8d8c-4fe6-9aab-cfefbf5edefb)
![Screenshot_20230622_110042_com twitter android_edit_294084636638457](https://github.com/rhunk/SnapEnhance/assets/57762287/74d10d60-1399-42c0-880c-d8f2d6814ab5)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
added in https://github.com/rhunk/SnapEnhance/commit/2d49a2a8ddad6e0c444ee3d1c4c51d4fdebe7429

**Comment by iBasim** [comment]
> added in [2d49a2a](https://github.com/rhunk/SnapEnhance/commit/2d49a2a8ddad6e0c444ee3d1c4c51d4fdebe7429)

Thank You

But there is a problem after enable "Vertical Story Viewer", if you Swipe up, it moves to another user, and it is not like the previous one. When you Swipe up, you can write


https://github.com/rhunk/SnapEnhance/assets/57762287/5d76316d-a660-4bd1-8940-c4b7ebee1c26
