### ISSUE TITLE
MOST features fail to init in newest snap version 

### ISSUE THREAD

**Issue by TechLionDev** [rhunk/SnapEnhance#824]
### Description

After installation of SnapEnhance on the latest Snapchat Updateost features fail to init

### Reproduction steps

1. Install Snap Enhance Mod
2. Start Snapchat 
3. Log in
4. See error.

### Snapchat Version

12.80.1.0

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
V1 IS Officially Obsolete
Please use [V2.0.0](https://t.me/snapenhance_ci)
