### ISSUE TITLE
snapchat plus...

### ISSUE THREAD

**Issue by matejj489** [rhunk/SnapEnhance#825]
### Description

i can't get a snapchat plus 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.80.1.0

### SnapEnhance Version

1.2.6

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
V1 IS Officially Obsolete
Please update To [V2.0.0](https://t.me/snapenhance_ci)
