### ISSUE TITLE
Application crashing

### ISSUE THREAD

**Issue by BrokenOG** [rhunk/SnapEnhance#826]
### Description

I have a device with 12 gb ram (high end device) but when i enable message logger the application crashes after few moments i experienced it on 3 different mobile 2 low end and 1 high end but the problem is same in every device 1st i thought it was becoz of low end device but when i tested it on high end device the result was same.

### Reproduction steps

1. Open snapchat 
2. Go on setting menu (of snap enhance)
3. Enable message logger 
4. Restart application 
5. Works fine for few minutes and then crashes 

### Snapchat Version

12.79.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
V1 IS Officially Obsolete
Please update To [V2.0.0](https://t.me/snapenhance_ci)
