### ISSUE TITLE
Export chats

### ISSUE THREAD

**Issue by BrokenOG** [rhunk/SnapEnhance#828]
### Description

Please readd the exports chats feature in future updates it is really helpful nd convenient to many users.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
Export Chats Is All ready A feature in V2

**Comment by BrokenOG** [comment]
> Export Chats Is All ready A feature in V2 
> 

Thanks for the response sir

**Comment by BrokenOG** [comment]
> Export Chats Is All ready A feature in V2 
> 

I just installed ci build you sent on tg on 3rd April it does has export chat feature will the final release of V2 have it?

**Comment by bocajthomas** [comment]
> > Export Chats Is All ready A feature in V2
> 
> I just installed ci build you sent on tg on 3rd April it does has export chat feature will the final release of V2 have it?

Yes The Stable Release Will have all the features but Ofc Stable Version of them features

**Comment by BrokenOG** [comment]
> > > Export Chats Is All ready A feature in V2
> > 
> > I just installed ci build you sent on tg on 3rd April it does has export chat feature will the final release of V2 have it?
> 
> Yes The Stable Release Will have all the features but Ofc Stable Version of them features

Thanks for the reply and clearing my doubt sir

**Comment by BrokenOG** [comment]
> > > Export Chats Is All ready A feature in V2
> > 
> > I just installed ci build you sent on tg on 3rd April it does has export chat feature will the final release of V2 have it?
> 
> Yes The Stable Release Will have all the features but Ofc Stable Version of them features

When will V2 stable version get released

**Comment by bocajthomas** [comment]
> > > > Export Chats Is All ready A feature in V2
> > > 
> > > 
> > > I just installed ci build you sent on tg on 3rd April it does has export chat feature will the final release of V2 have it?
> > 
> > 
> > Yes The Stable Release Will have all the features but Ofc Stable Version of them features
> 
> When will V2 stable version get released

Very Soon

**Comment by BrokenOG** [comment]
> > > > > Export Chats Is All ready A feature in V2
> > > > 
> > > > 
> > > > I just installed ci build you sent on tg on 3rd April it does has export chat feature will the final release of V2 have it?
> > > 
> > > 
> > > Yes The Stable Release Will have all the features but Ofc Stable Version of them features
> > 
> > When will V2 stable version get released
> 
> Very Soon 

Waiting eagerly

**Comment by bocajthomas** [comment]
> > > > > > Export Chats Is All ready A feature in V2
> > > > > 
> > > > > 
> > > > > I just installed ci build you sent on tg on 3rd April it does has export chat feature will the final release of V2 have it?
> > > > 
> > > > 
> > > > Yes The Stable Release Will have all the features but Ofc Stable Version of them features
> > > 
> > > 
> > > When will V2 stable version get released
> > 
> > 
> > Very Soon
> 
> Waiting eagerly

Yes Everyone is 

<details closed>
  <summary>Tap Me </summary>
</details>
> `👍`

**Comment by bocajthomas** [comment]
> Export chats feature is not available in pre release of V2 🥲

> - Yes Export Chats are In the Pre Release 

<details closed>
  <summary>How To Use</summary>

> 1. Open SnapEnhance
> 2. On Home Tab 
> 3. Tap The 3 Dots 
> 4. Tap The Icon Next to "Export chat Messages" 

</details>

**Comment by BrokenOG** [comment]
> > Export chats feature is not available in pre release of V2 🥲
> 
> > - Yes Export Chats are In the Pre Release 
> 
> <details closed>
>   <summary>How To Use</summary>
> 
> > 1. Open SnapEnhance
> > 2. On Home Tab 
> > 3. Tap The 3 Dots 
> > 4. Tap The Icon Next to "Export chat Messages" 
> 
> </details>
> 
> 

Found it thanks
