### ISSUE TITLE
feat: force enable dark mode

### ISSUE THREAD

**Issue by TGRush** [rhunk/SnapEnhance#83]
### Description

An option to force the Snap+ dark mode to be enabled, even when snap+ isn't spoofed or the option doesn't exist within the snap+ page.

I'm not sure when they'll decide to move this basic feature out of snap+, so I decided to suggest a force-enable toggle here.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment]
This feature has already been implemented in https://github.com/rhunk/SnapEnhance/commit/cbf2d41d7a4653a5b75549c3a0d0d6dc9d7eaae5

**Comment by TGRush** [comment]
> This feature has already been implemented in [cbf2d41](https://github.com/rhunk/SnapEnhance/commit/cbf2d41d7a4653a5b75549c3a0d0d6dc9d7eaae5)

Oh, apologies, I didn't see that.

Thanks! <3
