### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Zayedbj** [rhunk/SnapEnhance#831]
### Description

So when I did all the steps that I should do I pit a feature on to try it ex. If I turned on 
Snapchat + a message pops up and says Failed to innit Snapchatplus .And nothing is working out for me I tried re-installing nothing happened can someonebody help?
![VideoCapture_20240408-022751](https://github.com/rhunk/SnapEnhance/assets/161506445/56eda241-e00c-4f40-b9f6-e4b33ffcd7ab)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.80.1.0

### SnapEnhance Version

1.2.6

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
V1 IS Officially Obsolete
Please Use [V2.0.0](https://t.me/snapenhance_ci)
