### ISSUE TITLE
How to patch new version

### ISSUE THREAD

**Issue by bogzyeet** [rhunk/SnapEnhance#839]
I am new to this... How do i patch the source code from snapenhance v2 to a APK i can use with LSPatch..

### Snapchat Version

12.80.1.0

### SnapEnhance Version

1.2.6

Sorry but this isn't a bug... I just need help patching it... I have no idea on it nor I can find how to do it

**Comment by JustOnne** [comment]
Hey! Im having troubles too, how did you manage to install the new version?

**Comment by bocajthomas** [comment]
> I am new to this... How do i patch the source code from snapenhance v2 to a APK i can use with LSPatch..
> 
> ### Snapchat Version
> 12.80.1.0
> 
> ### SnapEnhance Version
> 1.2.6
> 
> Sorry but this isn't a bug... I just need help patching it... I have no idea on it nor I can find how to do it

theres an [Installation Guide](https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide)
currently stable V2 hasn't been released you will need thel [CI Build channel ](https://t.me/snapenhance_ci)
or go to [Actions](https://github.com/rhunk/SnapEnhance/actions/workflows/beta.yml)

If you need help you can Talk On [SE Discussion](https://t.me/snapenhance_chat)
