### ISSUE TITLE
QOL suggestions 

### ISSUE THREAD

**Issue by Manny542** [rhunk/SnapEnhance#845]
### Description

Add a setting option that will automatically open addresses, coordinates, etc... in the default map app when you tap to open them rather than Snapchat asking if you want to open in snap maps or whatever other map app.

~~Also add a version number in the settings panel so you can see what version of snap enhance you have.~~

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
> Also add a version number in the settings panel so you can see what version of snap enhance you have.

1. What's the point in that Users Will know what version There On since they Installed It 

2. It's All ready In The App ( On Home Page ) 

3. The quick toggle On Snapchat is ment for quick adjustments

**Comment by Manny542** [comment]
> > Also add a version number in the settings panel so you can see what version of snap enhance you have.
> 
> 1. What's The Point In That Users Will Know What Version There On Since They Installed It 
> 
> 3. It's All ready In The App ( On Home Page )  V2.0.0
> 
> 5. The quick toggle On Snapchat is ment for quick adjustments 
> 
> 

I guess a version number isn't really necessary for bigger updates like this one but for smaller ones like bug fixes it might be. (I've only recently started using this so I'm not sure how small some of the updates are.) I tried downloading the newest version today but didn't realize it wasn't installed until I noticed I couldn't find any of the new features.

**Comment by bocajthomas** [comment]
> 1. I guess a version number isn't really necessary for bigger updates like this one but for smaller ones like bug fixes it might be. (I've only recently started using this so I'm not sure how small some of the updates are.) I tried downloading the newest version today but didn't realize it wasn't installed until I noticed I couldn't find any of the new features.

> 2. I'm not sure what you would consider quick adjustment as like I said I've only recently started using this but I feel it would be similar in a way to other qol features already in the mod like ad block or no snap score delay.

1. That's what the .0.0 Is for E.g. For a bug Fix v2.0.1 after bug fix E.g. Feature Got Added v2.1.1
2. The gear Icon ⚙️ in the snapchat app is used only for quick adjustment

**Comment by authorisation** [comment]
We decided not to implement this but if someone else would like to feel free to open a PR.
