### ISSUE TITLE
Error/Cant Log in

### ISSUE THREAD

**Issue by Zayedbj** [rhunk/SnapEnhance#846]
### Description

So when I used Snapenhance v.2.0.0 and I tried to log in this popep up I tried it a couple of times and nothing worked 
And yes I put my password but I just blurred it in the picture.
Can someone help?
![Screenshot_20240409_215126_Snapchat](https://github.com/rhunk/SnapEnhance/assets/161506445/b087016d-69c7-4555-950c-4c69d3df604b)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.0

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Check #637
