### ISSUE TITLE
The ability to see if a snap has been sent exclusively to you.

### ISSUE THREAD

**Issue by BubbaKel** [rhunk/SnapEnhance#852]
### Description

I can't find the option to enable the ability to see if a snap has been sent exclusively to you. 

### Reproduction steps

I've looked everywhere, can't find it

### Snapchat Version

Newest

### SnapEnhance Version

Newest

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by BubbaKel** [comment]
I found it

**Comment by BubbaKel** [comment]
I found the option, never mind

**Comment by YasefDogan** [comment]
> I found the option, never mind

Where is it

**Comment by bocajthomas** [comment]
> Where is it

<details closed>
  <summary>Message Indicators</summary>

### Explanation
> **Allows Users To Add Specific Indicators Icons To Messages**

## Note
> **Indicators Might Not Be 100% Accurate**

### Message Indicators Include 
>  - `Adds a 🔒 icon next to messages that have been sent only to you`
>  - `Adds the platform icon from which a media was sent (e.g. Android, ioS, Web)`
>  - `Adds a 📍 icon to snaps when they have been sent with location enabled`
>  - `Indicates if a snap has been sent using OVF Editor`
>  - `Adds a ✏️ icon to snaps when they have been sent using Director Mode, which can be used to send gallery images as snaps`

### How To Enable/Setup
  1. Open The SnapEnhance App
  2. Go To "Features" Tab 
  3. Tap "User Interface"
  4. Tap The Icon Next To "Message Indicators"
  5. Toggle On Your Prefered Choice 

### How To Use
  1. Open Snapchat
  2. Look In Chat At A Snap
  3. You Will See These Icons 
</details>
