### ISSUE TITLE
Add the lock icon and other icons onto the snap after it's opened and onto the snap when you open it

### ISSUE THREAD

**Issue by BubbaKel** [rhunk/SnapEnhance#853]
### Description

The lock icon and other icons (such as what platform they use, etc.) Only show on the snap message whenever you haven't opened it yet and disappear after its opened. It i sn't really helpful bc most of the time you aren't in the chat waiting for the snap, you open it from the main page. So, it would be useful to add the icons to the message after the snap is opened and onto the snap image when it's opened.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
This is in v2

**Comment by BubbaKel** [comment]
I have v2, but the lock icon only shows on the message fir the snap and not after. It disappears after and almost no one is going ti be sitting in chat when they are waiting for a snap to be able to see the icon
