### ISSUE TITLE
FFMPEG with hardware acceleration

### ISSUE THREAD

**Issue by MaixGit** [rhunk/SnapEnhance#854]
### Description

Most devices would be using relatively recent Qualcomm chips, which have support for hardware accelerated AVC and HEVC video encoding and decoding, via [Qualcomm PDF download](https://developer.qualcomm.com/download/hevc/hevc-video-encoder-user-manual.pdf).

Encoding overlay merged videos with libx265 is super slow (like a whole 60 seconds slow), and libx264 is also quite slow unless you drop the quality to ultrafast and ~30 CRF, at which point the quality of the video and the file size is super unoptimised.

I'm not sure if it would be possible to achieve this, since I've only found one reference of someone else trying to do this via [Reddit](https://www.reddit.com/r/ffmpeg/comments/nyirum/libqhevcc_filelibrary_for_ffmpeg_on_qualcomm/). But if it is possible, then it would provide a huge boost to the speed and quality, and maybe even Exynos processor hardware acceleration could be implemented, however I'm on a Qualcomm 865.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment]
Definitely possible with a flag most likely the more of the issue would be determining if your CPU supports it. We could make it a option tho.

**Comment by TheVisual** [comment]
Build and test this https://github.com/rhunk/SnapEnhance/pull/899

**Comment by MaixGit** [comment]
I tried building it, but couldn't figure it out because I just kept encountering errors first with the Android SDK missing, and then "Task :native:configureCMakeDebug[arm64-v8a] FAILED". Is it possible that I use the artifacts from an actions run on your pull request? Sorry, I'm not the most experienced with coding.

**Comment by MaixGit** [comment]
Hi, I tested the artifact from the actions build, and unfortunately it doesn't seem to do anything on my Snapdragon 865 5G. Over multiple trials, the results were within margin of error when compared to the build without the -hwaccel flag. I also tried both libx264 and libx265 before and after, again, the results for both were within margin of error. I'm not exactly sure how FFMPEG's -hwaccel flag works, but I doubt that by default it would be able to detect Snapdragon or Exynos hardware acceleration capabilities.

**Comment by TheVisual** [comment]
> Hi, I tested the snapenhance-armv8-debug artifact from the actions build, and unfortunately it doesn't seem to do anything on my Snapdragon 865 5G. Over multiple trials, the results were within margin of error when compared to the build without the -hwaccel flag. I also tried both libx264 and libx265 before and after, again, the results for both were within margin of error. I'm not exactly sure how FFMPEG's -hwaccel flag works, but I doubt that by default it would be able to detect Snapdragon or Exynos hardware acceleration capabilities.

I tested multiple times on a less powerful CPU and saw 10-20 FPS increase

Before:
![image](https://github.com/rhunk/SnapEnhance/assets/132447890/2970e8c4-3941-4618-b0a0-b5bd474c8ab5)


After:
![image](https://github.com/rhunk/SnapEnhance/assets/132447890/3345b644-06a2-4e90-a40b-070aaf7bd8f8)

**Comment by MaixGit** [comment]
How'd you get the debug stats to show up there?

**Comment by TheVisual** [comment]
> How'd you get the debug stats to show up there?

I don't know if it depends on how you build but i went to a public profile and clicked download all segements

**Comment by MaixGit** [comment]
> > How'd you get the debug stats to show up there?
> 
> I don't know if it depends on how you build but i went to a public profile and clicked download all segements

Hmm, I can't seem to get the stats to show up, no matter where I download from. Also, I don't have the option to "Download all segments", I just have "Download media".

**Comment by MaixGit** [comment]
If you didn't change the number of threads to 4 before also adding the -hwaccel flag, then your fps increase may be due to the additional 3 threads that are used.

Throughout all my tests I always manually put the threads to 8.

**Comment by TheVisual** [comment]
> If you didn't change the number of threads to 4 before also adding the -hwaccel flag, then your fps increase may be due to the additional 3 threads that are used.
> 
> In my tests I always manually put the threads to 8.

-hwaccel auto defaults to media codec aka androids

Also snapdragon 865 is 4 years old don't expect superior performance even with the 5G slapped on it

If your worried about speed i recommend buying a new phone sir

**Comment by MaixGit** [comment]
@authorisation That last message was a bit unnecessarily rude, don't you think?

**Comment by MaixGit** [comment]
@authorisation Also, after further testing, I compared encode times when using 1 thread versus 4 threads (encoding the same video), and the results match up directly and proportionally with @TheVisual 's results on the pixel 5.
Meaning that the -hwaccel flag does absolutely nothing in this case.

Since I didn't have the exact encode fps values, I instead encoded a long video to get a more accurate measurement of the time it took to encode and thus the proportion of 1 thread vs 4 threads. I did the test on both the regular 2.0.1 build, and the build with the -hwaccel flag, they gave the same results within a margin of 1 second.


As you can see in the screenshots below, the first run was with 1 thread and it took 47 seconds to encode (marked in red), and the 2nd run, where I downloaded the same video and all I changed was the number of threads to 4, it took 35 seconds to encode (marked in blue).
![Screenshot_20240415_015910_SnapEnhance](https://github.com/rhunk/SnapEnhance/assets/43832909/7bac02f4-841f-4cf0-b178-758c639b783b)

That means:
For @TheVisual 's run, it went from 80.65 fps to 106.91 fps, which is an increase of 32.56%
For my run, it went from 47 sec to 35 sec to encode, which is a speed up of 34.29%

Which is quite the direct correlation if you ask me.
Hardware acceleration is also generally multiple times faster, such as NVENC with my GTX 1080, it's 4x as fast as if I encoded a video on my CPU.

Just wanted to let you know @authorisation :)

**Comment by bocajthomas** [comment]
> @authorisation That last message was a bit unnecessarily rude, don't you think?

That's not rude though 
The word `OLD` refers To Outdated Technology 
Your Device Is Outdated 
4 Years Is When you should upgrade 

You Got To remember 
Technology Moves Quickly Very Quickly!

**Comment by TheVisual** [comment]
> @authorisation That last message was a bit unnecessarily rude, don't you think?

https://github.com/rhunk/SnapEnhance/pull/906

I have upgraded to FFMPEG 6 (Full support for media codec) this is as new as you can get with media codec after this there's not many more improvements possible and I'm not being rude just a 4 year old chip can't pump 170+ FPS unfortunately it just how it is.

**Comment by MaixGit** [comment]
> > @authorisation That last message was a bit unnecessarily rude, don't you think?
> 
> #906
> 
> I have upgraded to FFMPEG 6 (Full support for media codec) this is as new as you can get with media codec after this there's not many more improvements possible and I'm not being rude just a 4 year old chip can't pump 170+ FPS unfortunately it just how it is.

Well thank you very much for the latest build. File size down from 137mb to 22mb with h264_mediacodec in the same quality

**Comment by TheVisual** [comment]
> > > @authorisation That last message was a bit unnecessarily rude, don't you think?
> > 
> > 
> > #906
> > I have upgraded to FFMPEG 6 (Full support for media codec) this is as new as you can get with media codec after this there's not many more improvements possible and I'm not being rude just a 4 year old chip can't pump 170+ FPS unfortunately it just how it is.
> 
> Well thank you very much for the latest build. File size down from 137mb to 22mb with h264_mediacodec in the same quality

Glad to help 👍
