### ISSUE TITLE
Settings don't open

### ISSUE THREAD

**Issue by Eatham532** [rhunk/SnapEnhance#860]
### Description

Clicking the Snap enhance settings opens the menu but then it closes instantly. Could be because I used Lspatch. 

### Reproduction steps

1. Open settings
2. Observe

### Logs

```markdown
Not sure how to provide logs.
```

### Snapchat Version

12.80.1.0 and 12.81.0.44

### SnapEnhance Version

v2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Use SnapEnhance App

**Comment by Eatham532** [comment]
Hold up... The snap enhance app doesn't have all the settings.

**Comment by Eatham532** [comment]
My bad, yes there are settings in Features. However the SnapEnhance gear still doesnt work like how it is meant to.

**Comment by bocajthomas** [comment]
> My bad, yes there are settings in Features. However the SnapEnhance gear still doesnt work like how it is meant to.

Your simply Not patching correctly 
i have tested both 12.79 & 12.80 & 12.81
( It Works ) 

please see the [installation guide](https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide)

**Comment by Eatham532** [comment]
> > My bad, yes there are settings in Features. However the SnapEnhance gear still doesnt work like how it is meant to.
> 
> Your simply Not patching correctly i have tested both 12.79 & 12.80 & 12.81 ( It Works )
> 
> please see the [installation guide](https://github.com/rhunk/SnapEnhance/wiki/Installation-Guide)

What do you mean I am not patching it correctly??? I used Lspatch and Shizuku. This is like the 5th time I have updated SnapEnhance. And it works every time. This is the only time it doesn't work. 

Because you don't have an issue, it is most likely an issue with my device.
