### ISSUE TITLE
temporary ban from logging in

### ISSUE THREAD

**Issue by krone0001** [rhunk/SnapEnhance#861]
### Description

trying to login to your snapchat account just instantly gets you temporarily disabled from logging in

### Reproduction steps

![Screenshot_20240410-050340](https://github.com/rhunk/SnapEnhance/assets/114771216/dd4edc4d-67d2-4c78-a7e8-78044796e216)

### Logs

```markdown
none
```

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by krone0001** [comment]
help ngl

**Comment by RSR1337** [comment]
You can't login on patched Snapchat or If you installed  custom rom or custom kernel, This is not a ban

**Comment by bocajthomas** [comment]
Please Check & Read #637
