### ISSUE TITLE
No read recipients option available

### ISSUE THREAD

**Issue by ProfessionalSk1t** [rhunk/SnapEnhance#863]
### Description

In the previous version there was an option to let no one know if you've viewed their message or not

### Reproduction steps

1. Go to `Features Tab`
2. No option...

### Snapchat Version

12.80.1.0

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
> It does exist

I think @ProfessionalSk1t Is Talking About `Stealth Mode` 
Or Talking About V1.2.6

**Comment by ProfessionalSk1t** [comment]
Thanks @bocajthomas
