### ISSUE TITLE
Where is the see if a Snap has been sent exclusively to you option

### ISSUE THREAD

**Issue by YasefDogan** [rhunk/SnapEnhance#865]
### Description

İn enhance 2.0 patch notes there is simeyhing called The ability to see if a Snap has been sent exclusively to you. But i cant find this inside the app i cant find what this feture called, can anyone help

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
> what this feture called

This Feature Is called `Message Indicators`

<details closed>
  <summary>Message Indicators</summary>

### Explanation
> **Allows Users To Add Specific Indicators Icons To Messages**

## Note
> **Indicators Might Not Be 100% Accurate**

### Message Indicators Include 
>  - `Adds a 🔒 icon next to messages that have been sent only to you`
>  - `Adds the platform icon from which a media was sent (e.g. Android, ioS, Web)`
>  - `Adds a 📍 icon to snaps when they have been sent with location enabled`
>  - `Indicates if a snap has been sent using OVF Editor`
>  - `Adds a ✏️ icon to snaps when they have been sent using Director Mode, which can be used to send gallery images as snaps`

### How To Enable/Setup
  1. Open The SnapEnhance App
  2. Go To "Features" Tab 
  3. Tap "User Interface"
  4. Tap The Icon Next To "Message Indicators"
  5. Toggle On Your Prefered Choice 

### How To Use
  1. Open Snapchat
  2. Look In Chat At A Snap
  3. You Will See These Icons 
</details>

**Comment by bocajthomas** [comment]
> Indicators
