### ISSUE TITLE
something about adb...

### ISSUE THREAD

**Issue by sherifboudyy** [rhunk/SnapEnhance#866]
### Description

i am no expert in rooting or adb commanding and followed a video to use lspatch to install snapenhance, now my phone's (pixel 7 in my case) storage won't appear on my laptop wwhen connected with a usb and when i go to eject it, it is named 'acer adb interface' , i can't connect my phone to a car via usb either. only reason i am suspecting it is snapenhance that it is the only modded app i am using.

### Reproduction steps

1.connect phone to laptop

### Snapchat Version

12.80.1.0

### SnapEnhance Version

2.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by authorisation** [comment]
This has nothing to do with SE.

**Comment by sherifboudyy** [comment]
> This has nothing to do with SE.

Where can i find help?
