### ISSUE TITLE
Snap notifications

### ISSUE THREAD

**Issue by BubbaKel** [rhunk/SnapEnhance#867]
### Description

Whenever you get a notification for a snap, in the notification is says "[Snap]" instead of like before when it said "(user) sent you a snap"

### Reproduction steps

Whenever someone sends you a snap

### Snapchat Version

Newest

### SnapEnhance Version

Newest

### Agreement

- [x] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment]
This is normal behavior.

**Comment by BubbaKel** [comment]
Well it looked like it was a bug bc it's in brackets and it's not like what it normally says when you receive a snap so
