### ISSUE TITLE
Can't seem to find 'Snap only sent to you' feature

### ISSUE THREAD

**Issue by Anmolparmar66** [rhunk/SnapEnhance#876]
### Description

Searched the entire app...can't really find the feature...also m not getting popup on holding an already opened snap to preview or download which I got in older features 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

2.0

### SnapEnhance Version

2.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
> ### Reproduction steps
> 1. Go to `...`
> 2. Click on `....`
> 3. Scroll down to `....`
> 4. See error.
> 
> ### Logs
> _No response_
> 
> ### Snapchat Version
> 2.0

Above is missing ^
