### ISSUE TITLE
Snapchat App will not open when patched with SnapEnhance on Android 15 Beta 1...

### ISSUE THREAD

**Issue by thelolinator2000** [rhunk/SnapEnhance#878]
### Description

I just updated to the android 15 public beta and Snapchat will not open when patched with SnapEnhance. Opens perfectly fine without patch from play store.

### Reproduction steps

1. Update to Android 15 Beta 1
2. Patch the App with either LSPatch or SE Manager
3. Try to open the installed Snapchat

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
> I just updated to the android 15 public beta and Snapchat will not open when patched with SnapEnhance. Opens perfectly fine without patch from play store.

Unfortunately @thelolinator2000  LSPatch Has been discontinued therefore not "Optimized" For Android 15 

You can ether Try and Use NPatch or ONpatch ( Both Are Forks )
