### ISSUE TITLE
Login...

### ISSUE THREAD

**Issue by IvyOwO06** [rhunk/SnapEnhance#879]
### Description

When i downloaded the module and patched it, it wouldn't let me log in it said suspicious activity. So i deleted the module and it let me log in right away

### Reproduction steps

1. Download al the needed app
2.  Patch snapenhance
3. Open snapchat and login
4.  Get denied bc of suspicious activity detected on your account

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by BrokenOG** [comment]
> ### Description
> 
> When i downloaded the module and patched it, it wouldn't let me log in it said suspicious activity. So i deleted the module and it let me log in right away
> 
> ### Reproduction steps
> 
> 1. Download al the needed app
> 2.  Patch snapenhance
> 3. Open snapchat and login
> 4.  Get denied bc of suspicious activity detected on your account
> 
> ### Logs
> 
> _No response_
> 
> ### Snapchat Version
> 
> 12.81.0.44
> 
> ### SnapEnhance Version
> 
> 2.0
> 
> ### Agreement
> 
> - [X] This is not a bug regarding Snapchat+.
> - [X] I have provided a detailed description of the issue.
> - [X] I have attached a log if deemed neccessary.
> - [X] This issue is not a duplicate.

Same happened with me you can stop the app from background and then try to login in my case when i restarted it and filled my mobile number instead of username nd after filling password i was able to login so try number email and username one by one by restarting the app as well it should work.

**Comment by bocajthomas** [comment]
Please Read #637
