### ISSUE TITLE
Non-root instant crash when starting

### ISSUE THREAD

**Issue by vvirtues** [rhunk/SnapEnhance#880]
### Description

I deleted and reinstalled both snapchat and snapenhance v2. When I patch and open using LSPatch the app closes insanely fast that all I see is yellow, no sign in or anything

### Reproduction steps

1. Download SnapEnhance v2
2. Download Snapchat latest non-beta
3. Patch using LSPatch
4. Uninstall Snapchat
5. Reinstall the patched version
6. open snapchat

### Logs

```markdown
No relevant logs
```

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

NOTE: I've also tried regenerating mappings and clearing cache/data (using SnapEnhance). App has no data/cache

**Comment by vvirtues** [comment]
might be because I chose to not use shizuku and uninstall/reinstall manually

**Comment by vvirtues** [comment]
testing, will respond later

**Comment by vvirtues** [comment]
nevermind, using steps in the wiki fixed it. Great job 💖

**Comment by BrokenOG** [comment]
> ### Description
> 
> I deleted and reinstalled both snapchat and snapenhance v2. When I patch and open using LSPatch the app closes insanely fast that all I see is yellow, no sign in or anything
> 
> ### Reproduction steps
> 
> 1. Download SnapEnhance v2
> 2. Download Snapchat latest non-beta
> 3. Patch using LSPatch
> 4. Uninstall Snapchat
> 5. Reinstall the patched version
> 6. open snapchat
> 
> ### Logs
> 
> ```markdown
> No relevant logs
> ```
> 
> 
> ### Snapchat Version
> 
> 12.81.0.44
> 
> ### SnapEnhance Version
> 
> 2.0.0
> 
> ### Agreement
> 
> - [X] This is not a bug regarding Snapchat+.
> - [X] I have provided a detailed description of the issue.
> - [X] I have attached a log if deemed neccessary.
> - [ ] This issue is not a duplicate.
> 
> NOTE: I've also tried regenerating mappings and clearing cache/data (using SnapEnhance). App has no data/cache

Your device may be slow try to wait on that yellow screen for few moments

**Comment by vvirtues** [comment]
Like I said it closes instantly i barely see it, but the issue is fixed already

**Comment by BrokenOG** [comment]
> Like I said it closes instantly (10 ms) i barely see it, but the issue is fixed already

That's good but you can check if you might have enabled unstable features it can be because of them to

**Comment by vvirtues** [comment]
> > Like I said it closes instantly (10 ms) i barely see it, but the issue is fixed already
> 
> That's good but you can check if you might have enabled unstable features it can be because of them too

I had uninstalled the app to reset all of the features

**Comment by bocajthomas** [comment]
> I had uninstalled the app to reset all of the features

You can export your features

**Comment by BrokenOG** [comment]
> > nevermind, using steps in the wiki fixed it. Great job 💖
> 
> Your Welcome 🙏 

How can i learn coding i also want to do coding and make amazing stuff like this (i have 0 knowledge about how coding work)

**Comment by bocajthomas** [comment]
> How can i learn coding i also want to do coding and make amazing stuff like this (i have 0 knowledge about how coding work)

Most Of SnapEnhance Is Programmed With [kotlin](https://kotlinlang.org/docs/basic-syntax.html) kotlin is an Android programming language
