### ISSUE TITLE
Unable to find preview option 

### ISSUE THREAD

**Issue by BrokenOG** [rhunk/SnapEnhance#882]
### Description

In V1 when we are in a chat we may hold on a snap and see a preview option in the options but in V2 i am unable to find this feature can someone tell me how to enable this feature or is it in V2 ot not

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.79.0.37

### SnapEnhance Version

V2

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
<details closed>
  <summary>Download Context Menu</summary>

### Explanation
> **Allows Users To Download & Preview Messages Or Snaps Directly From The Context Menu**

### How To Enable/Setup
>  1. Open The SnapEnhance App
>  2. Go To "Features" Tab 
>  3. Tap "Downloader"
>  4. Toggle On "Download Context Menu"

### How To Use
>  1. Open Snapchat 
>  2. Open A Chat 
>  3. Hold Down On A Snap Or Message 
>  4. Press Preview Or Download 
 
</details>
