### ISSUE TITLE
Can i get banned

### ISSUE THREAD

**Issue by BrokenOG** [rhunk/SnapEnhance#885]
### Description

The features with the note "this feature may cause ban" will my  account really get banned if yes for how much time and after how much time when i will enable that feature 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.79.0.37

### SnapEnhance Version

V2

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
SE Discussion!! [Telegram](https://t.me/snapenhance_chat)
