### ISSUE TITLE
Snap not working... ...

### ISSUE THREAD

**Issue by Modcal** [rhunk/SnapEnhance#888]
### Description

Today the issue has started
![Screenshot_20240412-204613](https://github.com/rhunk/SnapEnhance/assets/166858047/6976c373-b4b0-4fe6-aa19-5a637de5d63f)
![Screenshot_20240412-204604](https://github.com/rhunk/SnapEnhance/assets/166858047/78804949-fabd-4f66-b0a1-a38ab03a4af2)
 the Snapchat is not working and a message of force close the same for snap enhance 2.0
Even after I reinstalled 1.2.6 the same issue remain the picture stock in. Snapchat logo then a message of closing the app

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.80

### SnapEnhance Version

2.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
NO logs !!!
