### ISSUE TITLE
bug: Infinite Story Boost No Longer Working

### ISSUE THREAD

**Issue by TheVisual** [rhunk/SnapEnhance#90]
### Description

Infinite Story Boost No Longer Working

### Reproduction steps

```bash
1. Go to Setting
2. Enable Infinite Story Boost
3. Refresh App
4. Swipe up and try to boost story.
```

### Screenshots

```bash
https://freeimage.host/i/HPjCcV1
https://freeimage.host/i/HPjCaoP
```

### Snapchat Version

12.39.0.48

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by RevealedSoulEven** [comment]
They have implemented server side checks. It is yet to be bypassed

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/b7422d97957ff7d2ea6c15ef720d9d2d5f0d0c3c
