### ISSUE TITLE
Programming messages

### ISSUE THREAD

**Issue by MXC48** [rhunk/SnapEnhance#902]
### Description

Just as an idea for a new feature, it would be nice to be able to schedule messages using the mod in snap :)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
The `Scripting Engine` Can Do This

**Comment by TheVisual** [comment]
As @bocajthomas scripting is main way.

Please refer to https://github.com/SnapEnhance/docs there's some examples that can get you started
