### ISSUE TITLE
Not sure why...

### ISSUE THREAD

**Issue by Yahoo302** [rhunk/SnapEnhance#904]
### Description

This is what is written upon opening snapchat...

Snapchat can't connect to the SnapEnhance app. Make sure you have the latest version installed on your device. You can download the latest stable version on github.com/ rhunk/SnapEnhance

I am using the latest compatible snapchat. 
![Screenshot_20240414_141808_Snapchat](https://github.com/rhunk/SnapEnhance/assets/121044978/0b96f285-ab71-4d81-8979-62cd01a6b5b9)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by TheVisual** [comment]
https://github.com/rhunk/SnapEnhance/releases/tag/v2.0.1

You running this?

**Comment by Yahoo302** [comment]
> https://github.com/rhunk/SnapEnhance/releases/tag/v2.0.1
> 
> You running this?

Yes

**Comment by TheVisual** [comment]
> > https://github.com/rhunk/SnapEnhance/releases/tag/v2.0.1
> > You running this?
> 
> Yes

Can you try this build aswell and see if occurs?: https://github.com/rhunk/SnapEnhance/actions/runs/8679660113

**Comment by Yahoo302** [comment]
> > > https://github.com/rhunk/SnapEnhance/releases/tag/v2.0.1
> > > You running this?
> > 
> > 
> > Yes
> 
> Can you try this build aswell and see if occurs?: https://github.com/rhunk/SnapEnhance/actions/runs/8679660113

How do I run it? I can't run anything in the zips

**Comment by TheVisual** [comment]
> > > > https://github.com/rhunk/SnapEnhance/releases/tag/v2.0.1
> > > > You running this?
> > > 
> > > 
> > > Yes
> > 
> > 
> > Can you try this build aswell and see if occurs?: https://github.com/rhunk/SnapEnhance/actions/runs/8679660113
> 
> How do I run it? I can't run anything in the zips

select Armv7 / Armv8 and Unzip and install

**Comment by Yahoo302** [comment]
> > > > > https://github.com/rhunk/SnapEnhance/releases/tag/v2.0.1
> > > > > You running this?
> > > > 
> > > > 
> > > > Yes
> > > 
> > > 
> > > Can you try this build aswell and see if occurs?: https://github.com/rhunk/SnapEnhance/actions/runs/8679660113
> > 
> > 
> > How do I run it? I can't run anything in the zips
> 
> select Armv7 / Armv8 and Unzip and install

Worked! Ty!
