### ISSUE TITLE
Unable to use Snapchat+/ solar system features...

### ISSUE THREAD

**Issue by Sujalsahu05** [rhunk/SnapEnhance#905]
### Description

I have been using Snapchat+ but even after turning on the solar system, the solar system features are not working.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

2.81.66 Beta

### SnapEnhance Version

2.0.1

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by TheVisual** [comment]
It may be server sided this is why we have the agreement 
![image](https://github.com/rhunk/SnapEnhance/assets/132447890/73ddd426-2a13-44f8-8982-c266579eb65a)

Furthermore @authorisation @rhunk please correct me if I'm wrong if this is serversided or not

**Comment by authorisation** [comment]
Yes I'm pretty sure that is the case
