### ISSUE TITLE
Call Recorder

### ISSUE THREAD

**Issue by ahmedraza52** [rhunk/SnapEnhance#910]
### Description

We can't hear our voice in recorded voice call. I can only hear other person's voice :(

Please fix this issue if possible or tell me if there any solution available

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
Duplicate of #791
