### ISSUE TITLE
Dialogue box with "App  stopped working" after LOS 21 April security patch

### ISSUE THREAD

**Issue by regcyb1** [rhunk/SnapEnhance#921]
### Description

Since i have been using this module in my phone with custom rom for a while, i have never had any issue. With the latest Lineage os 21 security patch it just crashes patched app moment after it gets installed.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

Well for every possible verison

### SnapEnhance Version

For all snapenhance version

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
@regcyb1 you have ticked logs but haven't provided any ?
