### ISSUE TITLE
The Streak Restore button still appears even with the setting active.

### ISSUE THREAD

**Issue by NicoaraAlex** [rhunk/SnapEnhance#925]
### Description

The restore button only appears after I open the snap received from my friend. It's visible, and I believe it disappears after the streaks are restored. When I press it, nothing happens. From further testing, the button disappears if the friend sends another snap (without the streak being restored).
[snapenhance-logs-1713447896150.zip](https://github.com/rhunk/SnapEnhance/files/15025777/snapenhance-logs-1713447896150.zip)
![1](https://github.com/rhunk/SnapEnhance/assets/82382328/3e66fac8-8225-449e-bb3f-b1f4fd60893c)
![2](https://github.com/rhunk/SnapEnhance/assets/82382328/44c2eefa-cb01-4221-915e-b0d88a3d2a2f)

### Reproduction steps

1. Go to `Find a friend with whom you think you've lost the streaks.`
2. Click on `On that unopened snap, then, after the snap is closed, the non-functional button appears in the conversations tab.`

### Logs

```markdown
Attached above
```

### Snapchat Version

12.82.0.51

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
@NicoaraAlex are you Rooted?

**Comment by NicoaraAlex** [comment]
Yup

**Comment by bocajthomas** [comment]
> Yup

Have you tried with the past version of Snapchat?  ( v12.79 , v12.80, v12.81 ) ?

Also try the beta [v2.0.2](https://t.me/snapenhance_ci/444)

**Comment by NicoaraAlex** [comment]
> > Yup
> 
> Have you tried with the past version of Snapchat? ( v12.79 , v12.80, v12.81 ) ?
> 
> Also try the beta [v2.0.2](https://t.me/snapenhance_ci/444)

I haven't tried the older versions, only yesterday I installed this mod for Snapchat

**Comment by bocajthomas** [comment]
Did you turn on `Hide Streak Restore`

<details closed>
  <summary>Hide Streak Restore</summary>

### Explanation
> **Allows Users To Hide The Streak Restore Button**

### How To Enable/Setup
>  1. Open The SnapEnhance App
>  2. Go To "Features" Tab 
>  3. Tap "User Interface"
>  4. Toggle On "Hide Streak Restore"

### How To Use
>  1. Open Snapchat
>  2. You Will Now See The "Restore Streaks Button" Is No Longer Visible 
</details>

**Comment by NicoaraAlex** [comment]
Check the picture attached above, I tried to activate the function, to deactivate it, to restart snapchat and SnapEnhance, I cleared the cache of both, it doesn't work, if you want other data stored in place, I can check it (explain to me where I can find it or how I generate them)

**Comment by bocajthomas** [comment]
> Check the picture attached above, I tried to activate the function, to deactivate it, to restart snapchat and SnapEnhance, I cleared the cache of both, it doesn't work, if you want other data stored in place, I can check it (explain to me where I can find it or how I generate them). If it helps, I can send the SnapEnhance settings as they are now

It's mostly Snapchat has changed stuff around

**Comment by bocajthomas** [comment]
@rhunk what do you think ?

**Comment by NicoaraAlex** [comment]
@bocajthomas here is https://we.tl/t-8vZjIo1AjE

**Comment by Ch0nkst3r** [comment]
Same goes for me, tried restarting, reactivating, mapping... button still appears to be there

**Comment by bocajthomas** [comment]
@NicoaraAlex try the previous versions

**Comment by NicoaraAlex** [comment]
@bocajthomas I tried the previous version (2.0.0) but it still doesn't work

https://github.com/rhunk/SnapEnhance/assets/82382328/2d35e2af-40c6-469f-ad5b-fb580aaba963

**Comment by bocajthomas** [comment]
> @bocajthomas I tried the previous version (2.0.0) but it still doesn't work

i am talking about snapchat versions 
try use an other snapchat version

**Comment by NicoaraAlex** [comment]
> > @bocajthomas I tried the previous version (2.0.0) but it still doesn't work
> 
> i am talking about snapchat versions try use an other snapchat version

Can you please give me a site where I could download it? there are more but probably some sites are better :)
