### ISSUE TITLE
Where can I find snapenhance custom scripts?...

### ISSUE THREAD

**Issue by aryanmcr** [rhunk/SnapEnhance#926]
### Description

Not a feature but idk where to ask

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by aryanmcr** [comment]
oh I was talking about finding working scripts that u like import but thanks anyway, I found out there's only one and it's broken rn

**Comment by Acid4t** [comment]
let's just appreciate dude's list of girlfriends
