### ISSUE TITLE
Instant delete not working

### ISSUE THREAD

**Issue by aryanmcr** [rhunk/SnapEnhance#928]
### Description

Instant delete shows:

delete chat? friends can see you deleted something

### Reproduction steps

1. Enable instant delete
2. Send a message
3. Delete message
4. See error.

### Snapchat Version

424030708

### SnapEnhance Version

Latest Build 2.0.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by NicoaraAlex** [comment]
It works for me, at least, or it probably shouldn't look like that

https://github.com/rhunk/SnapEnhance/assets/82382328/14b416b9-bfb0-467a-99de-3b1387d8ace1

**Comment by bocajthomas** [comment]
Please update To [v2.0.1](https://github.com/rhunk/SnapEnhance/releases/tag/v2.0.1)

**Comment by aryanmcr** [comment]
Oh, I'm sorry. I was using version 2.0.2 and I just realised. It shouldn't say 2.0.0 it's 2.0.2 sorry
