### ISSUE TITLE
Can't update from Debug CI builds. I have to delete current version to install new one.

### ISSUE THREAD

**Issue by StupidRepo** [rhunk/SnapEnhance#929]
### Description

Hey, so each time I try to update to a new Debug CI build, I have to delete the current version of SnapEnhance and then install the one I wanted to install.

Every time I just press "Update" after tapping on the APK, it always fails. I was wondering if you knew how to force install the APK regardless so I don't have to export my config, delete old SnapEnhance, install new SnapEnhance then import the config just to update it.

**Comment by bocajthomas** [comment]
@StupidRepo you can use termux to use adb commands to force Uninstall SnapEnhance

**Comment by bocajthomas** [comment]
> Yeah I found that out. But I don't like uninstall and then reinstalling because it resets my config file. I know I can reimport my config but it's so annoying to do this each time! being able to force update the app would be helpful, do you know how to do that?

Then don't use "beta"

**Comment by bocajthomas** [comment]
> being able to force update the app would be helpful, do you know how to do that?

Use mt manager to sign the apk file then do this every time
