### ISSUE TITLE
Snapchat temporary restricted my account

### ISSUE THREAD

**Issue by NicoaraAlex** [rhunk/SnapEnhance#932]
### Description

When I try to login, show: Because there were multiple failed attempts
 or other unusual activities, your access to
 Snapchat is temporarily disabled.  Learn more here.
![Screenshot_20240419_233332_Snapchat](https://github.com/rhunk/SnapEnhance/assets/82382328/78be8a1d-8c9a-4739-95b2-bf85bcdfcf82)

### Reproduction steps

1. Disconnect
2. Clear snapchat memory
3. Try to login with user in password
4. See error.

### Snapchat Version

12.82.0.51

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by NicoaraAlex** [comment]
If I try to connect from another device, it leaves me

**Comment by bocajthomas** [comment]
Check the thread #637
