### ISSUE TITLE
Cant find the a button

### ISSUE THREAD

**Issue by M1-K1** [rhunk/SnapEnhance#934]
### Description

How do I suspend location updates in the snapchat setting when I have the setting on

### Reproduction steps

.

### Snapchat Version

Idk

### SnapEnhance Version

Idk

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
<details closed>
  <summary>Better Location</summary>

### Explanation
> **Allows Users To Enhance The Snapchat Location**

### Better Location Includes 
>  - `Spoof Location`
>  - `Coordinates`
>  - `Always Update Location`
>  - `Suspend Location Updates`
>  - `Spoof Battery Level`
>  - `Spoof Headphones`

### How To Enable/Setup
>  1. Open SnapEnhance App 
>  2. Go To "Features" Tab 
>  3. Tap "Global"
>  4. Toggle On "Better Location"

### How To Use
>  1. Open Snapchat
>  2. Check The Snapmap 
</details>

**Comment by M1-K1** [comment]
No 

I want to suspend location updates like in the map settings

I already have it switched on in the globals tab in the snapenhanced menu but I ca t seem to find the supposed button in the map setting which it's telling to do
