### ISSUE TITLE
Story logger issues

### ISSUE THREAD

**Issue by dudecop34** [rhunk/SnapEnhance#939]
### Description

Only a few storys are actually logged and a bunch of them just say failed to load and the time frames on them are messed up they all say December 31 1969

### Reproduction steps

Just turn on story logger and go through someone who posts 5+ stories and you will see almost all of them failed to load

### Logs

```markdown
n/a
```

### Snapchat Version

Latest

### SnapEnhance Version

Latest

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
@dudecop34 currently testing
