### ISSUE TITLE
Post from galary...

### ISSUE THREAD

**Issue by laka3ah** [rhunk/SnapEnhance#941]
### Description

When i post pic or video from galary it is going directly without showing me if it is snap or original it shows only in private massage...
![IMG_20240420_215352_406](https://github.com/rhunk/SnapEnhance/assets/61008084/7844e218-2136-4522-936c-7fa2350bfaf4)

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.82.0.51 

### SnapEnhance Version

2.0.2

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
@laka3ah can't reproduce since there's no reproduce steps
