### ISSUE TITLE
Bulk Friend Remover

### ISSUE THREAD

**Issue by CanerKaraca23** [rhunk/SnapEnhance#942]
### Description

When i want to remove my friend list "it's huge like 4000 people" in the progress of removing, the action stops and Snapchat crash, and not any my friend removed. No crash log.

![Screenshot_20240421-013623_Snapchat](https://github.com/rhunk/SnapEnhance/assets/37447503/48198bc7-e4f6-4acd-a729-5677d2c8276b)

### Reproduction steps

1. Go to `Bulk Message`
2. Click on `Remove Friend and wait`

### Snapchat Version

12.82.0.51

### SnapEnhance Version

2.0.2

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
> I can't remove friend on Snapchat manually now, i guess there is a limit by server.

That maybe the cause 
Close now ?

**Comment by bocajthomas** [comment]
> Nah, crash isn't related to this i think. It happened on my first remove run. I guess crash related to RAM or CPU.

@CanerKaraca23 you said Related to Your Devices hardware meaning it's not a software issue so it's not a bug

**Comment by bocajthomas** [comment]
> Bro, it's just my "guess" did you tried that if you also encounter? Why closing the issue? Dev not even see to debug/test it. I have SD870. LOL.

It's an issue. If it's an issue that doesn't need fixing 

Just delete 2000 at a time 
+ who in the right mind would delete 4000+ 
Nobody 

Doesn't need fixing 
It's a waste of time

**Comment by NicoaraAlex** [comment]
I have the same problem, I tried to select between 10-20 friends to delete, or business profiles, it doesn't work, it's not because of the phone..

**Comment by authorisation** [comment]
The same thing happens when downloading too many Snaps using the export function, no idea why

**Comment by NicoaraAlex** [comment]
I'm thinking, would it work on an older version of snapchat? And if so, which version would it be?
