### ISSUE TITLE
Can not get unlimited snap replays

### ISSUE THREAD

**Issue by Batninja789** [rhunk/SnapEnhance#946]
### Description

On the older version I was able to select the option to leave messages as unread and was able to view snaps as many times as I wanted. In the new update I do not if this feature was removed or changed because I am unable to view snaps as many times as I wanted too. 

### Reproduction steps

I do not know if this feature is removed or changed.

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
@Batninja789 this was never a feature 
You can use `Stealth Mode`

**Comment by Batninja789** [comment]
Is there a way to leave your messages as unread? On the latest version.

**Comment by bocajthomas** [comment]
> Is there a way to leave your messages as unread? On the latest version. Also how do you enable ghost mode?

https://github.com/rhunk/SnapEnhance/wiki/Features-Explained
