### ISSUE TITLE
SnapEnhance does not load.

### ISSUE THREAD

**Issue by gigacastelo** [rhunk/SnapEnhance#95]
### Description

Someone please help me.  I'm using LSPatch and trying to run version "app-1.0.1-armv8"

Can anyone please help me? I've seen people commenting recently that they were able to successfully run on LSPatch but nothing I do seems to work.
Everytime I patch the app, it installs successfully but it doesn't chance anything at all on Snapchat. It's like SnapEnhance is not installed.
I'm using the tested Snapchat version 

### Reproduction steps

```bash
1. Successfully installed LSPatch
2. Installed the Latest Vesion of SnapEnhance "v1.0.1-hotfix"
3. Patched the installed app using LSPatch sucessfully.
4. Clicked on SnapEnhance icon, Snapchat opens but nothing changed at all.
```

### Snapchat Version

12.36.0.53

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [ ] There is no issue already describing my problem.

**Comment by ryu0q** [comment]
How did you fix this?
