### ISSUE TITLE
Screenshots Detected 

### ISSUE THREAD

**Issue by ha2ked** [rhunk/SnapEnhance#951]
### Description

It knows when I take a screenshot simple as.

### Reproduction steps

1. Enable "Bypass Screenshot Detection
2. Go to Snapchat 
3. Take a screenshot
4. It detects a screenshot and sends the alert in chat that you took a screenshot

### Snapchat Version

12.82.0.51

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
@ha2ked you need to use `Prevent Message Sending`

**Comment by ha2ked** [comment]
> @ha2ked you need to use `Prevent Message Sending`

Oh ok tx
