### ISSUE TITLE
Where do I find mappings?

### ISSUE THREAD

**Issue by StupidRepo** [rhunk/SnapEnhance#965]
### Description

I wanted to make a feature, but I have no idea where to start, in terms of finding the name of the thing I need to hook. How can I find the names of the methods I can hook on classes?

(Note: can't update title because I'm editing this post on mobile currently, whoops)

**Comment by bocajthomas** [comment]
> Decompile the Snapchat APK using something like [jadx](https://github.com/skylot/jadx)

Or MT manager
