### ISSUE TITLE
Amoled dark mode for snapenhance & Snapchat amoled dark mode fix

### ISSUE THREAD

**Issue by Brokoli5191** [rhunk/SnapEnhance#985]
### Description

Please add amoled dark mode to SnapEnhance and fix amoled dark mode on Snapchat bc it looks buggy sometimes.
![Screenshot_20240502_072218_Snapchat](https://github.com/rhunk/SnapEnhance/assets/119419930/6e435f0c-3436-47e6-b23f-16ecfda914f4)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
@Brokoli5191 colors feature will allow you to make your own themes ( text color, Background color ) etc 
please wait for v2.1.0
