### ISSUE TITLE
NullPointerException when using sendChatMessage

### ISSUE THREAD

**Issue by demostanis** [rhunk/SnapEnhance#992]
### Description

im fetching conversationIds (SELECT key FROM Feed ..) using rawQuery() and passing them to messaging.sendChatMessage in a loop

im try{}catch'ing the block and shortToasting any error, which leads to the following toast: NullPointerException: null receiver

its a bit hard to diagnose the problem, i dont know how to get a get real logs with a traceback, and the scripting documentation is poor on the subject

what could be the issue? the UUIDs are not null 

### Reproduction steps

fetch UUIDs from main.db
pass them to sendChatMessage
boom

### Snapchat Version

12.81.0.44

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment]
@demostanis please open an issue on the docs 

[Quick access](https://github.com/SnapEnhance/docs/issues)
