### ISSUE TITLE
Feature Suggestion...

### ISSUE THREAD

**Issue by BearrXW** [rhunk/SnapEnhance#995]
### Description

Please add a feature so that you can view a message in chat without it saying that the message has been opened. Also add a feature so that u can send more snaps at once as their is currently a multi snap limit on how much u can send

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by bocajthomas** [comment]
@BearrXW this has all ready been impemented `Stealth mode`

**Comment by BearrXW** [comment]
@bocajthomas there is no multi snap bypass feature

**Comment by bocajthomas** [comment]
> @bocajthomas there is no multi snap bypass feature

That's because muti Snap is NOT a feature anymore on standard Snapchat 

So it got removed off SnapEnhance

**Comment by BearrXW** [comment]
> > @bocajthomas there is no multi snap bypass feature
> 
> That's because muti Snap is NOT a feature anymore on standard Snapchat
> 
> So it got removed off SnapEnhance

Is there anyway to add a snap feature that mimics multi snap so you could just enter an amount of that message/snap to send to someone.

**Comment by bocajthomas** [comment]
> Is there anyway to add a snap feature that mimics multi snap so you could just enter an amount of that message/snap to send to someone.

for snaps no and will never be 
messages yes ( Scripting engine ) 
use this script [ozzspam.js](https://t.me/snapenhance_chat/24067/49600)
